Repository openshift/rosa, pull requests merged in 2020-12, with the labels that each got.

#192 [rosa create cluster] Verify provided subnets for Existing VPC exist in AWS
  cmd/create/cluster/cmd.go
Labels: approved, lgtm, ok-to-test

#177 Remove paid AMI flag and finalize ROSA transition
  README.md
  cmd/create/cluster/cmd.go
  cmd/login/cmd.go
  docs/rosa_login.md
  pkg/cluster/cluster.go
  pkg/ocm/properties/properties.go
  pkg/ocm/versions/versions.go
Labels: approved

#191 add taints to machinepool commands
  cmd/create/machinepool/cmd.go
  cmd/list/machinepool/cmd.go
  docs/rosa_create_machinepool.md
Labels: approved, lgtm

#193 upgrades: Allow scheduling, listing, canceling cluster upgrades
  cmd/dlt/cmd.go
  cmd/dlt/upgrade/cmd.go
  cmd/list/cmd.go
  cmd/list/upgrade/cmd.go
  cmd/rosa/main.go
  cmd/upgrade/cluster/cmd.go
  cmd/upgrade/cmd.go
  docs/rosa.md
  docs/rosa_delete.md
  docs/rosa_delete_upgrade.md
  docs/rosa_list.md
  docs/rosa_list_upgrades.md
  docs/rosa_upgrade.md
  docs/rosa_upgrade_cluster.md
  go.mod
  go.sum
  pkg/ocm/upgrades/upgrades.go
  pkg/ocm/versions/versions.go
Labels: approved

#194 Release v0.1.3
  CHANGES.adoc
  pkg/info/info.go
Labels: approved

#167 Adding Orange team members to OWNERS file
  OWNERS
Labels: approved, lgtm

#195 Advise user to run 'rosa init' for failed credentials check
  pkg/aws/client.go
  pkg/cluster/cluster.go
Labels: approved, lgtm

#196 user: Determine if user exists before revoking role
  cmd/revoke/user/cmd.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#200 login: Hide 'env' parameter
  cmd/login/cmd.go
  docs/rosa_init.md
  docs/rosa_login.md
Labels: approved, lgtm

#199 multi-az: Validate that compute nodes are multiple of 3
  cmd/create/cluster/cmd.go
  cmd/edit/machinepool/cmd.go
Labels: approved, lgtm

#198 create-cluster: Set default version
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#201 cluster: Show warnings when user makes cluster private
  cmd/create/cluster/cmd.go
  cmd/create/cmd.go
  cmd/describe/cluster/cmd.go
  cmd/edit/cluster/cmd.go
  docs/rosa_create.md
  docs/rosa_create_admin.md
  docs/rosa_create_cluster.md
  docs/rosa_create_idp.md
  docs/rosa_create_ingress.md
  docs/rosa_create_machinepool.md
Labels: approved

#203 describe-cluster: Display scheduled upgrades
  cmd/describe/cluster/cmd.go
Labels: approved

#202 replicas: Fix local validation for worker nodes and machinepool replicas
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/cmd.go
  cmd/edit/machinepool/cmd.go
Labels: approved

#206 Disable `maligned` linter
  .golangci.yml
Labels: approved, lgtm
