Repository openshift/rosa, pull requests merged in 2020-10, with the labels that each got.

#122 idp: Add support for certificate bundles
  cmd/create/idp/cmd.go
  cmd/create/idp/github.go
  cmd/create/idp/ldap.go
  cmd/create/idp/openid.go
  docs/moactl_create_idp.md
  pkg/interactive/interactive.go
Labels: approved

#130 Added New Error Message Implementation
  cmd/describe/cluster/cmd.go
  go.mod
  go.sum
Labels: approved, lgtm, needs-ok-to-test

#120 idp: Add support for GitLab
  cmd/create/idp/cmd.go
  cmd/create/idp/gitlab.go
  cmd/list/idp/cmd.go
  docs/moactl_create_idp.md
Labels: approved

#128 Support dry-run parameter for 'init' and 'create cluster'
  cmd/create/cluster/cmd.go
  cmd/initialize/cmd.go
  docs/moactl_create_cluster.md
  go.mod
  go.sum
  pkg/cluster/cluster.go
Labels: approved

#127 Makefile: only download go-bindata when not available
  Makefile
  go.mod
  go.sum
Labels: approved, lgtm

#104 Move main.go to moactl directory, add make install target
  Makefile
  README.md
  cmd/moactl/main.go
Labels: approved, lgtm

#134 Release v0.0.14
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm

#138 github: Provide guidance on using GitHub organizations when creating IdP
  cmd/create/idp/github.go
Labels: approved, lgtm

#132 Add CONTRIBUTING.md file, with some details about CI
  CONTRIBUTING.md
Labels: approved, lgtm

#135 init: Ensure osdCcsAdmin exists before attempting cluster dry-run
  cmd/create/cluster/cmd.go
  cmd/initialize/cmd.go
Labels: approved, lgtm

#140 logs: Show example command for install logs
  cmd/logs/cmd.go
  docs/moactl_logs.md
Labels: approved, lgtm

#146 aws: Allow using AWS_PROFILE env var
  pkg/aws/profile/flag.go
Labels: approved, lgtm

#145 ocm: Keep error opIds and codes behind debug flag
  cmd/create/idp/cmd.go
  cmd/create/ingress/cmd.go
  cmd/create/user/cmd.go
  cmd/dlt/idp/cmd.go
  cmd/dlt/ingress/cmd.go
  cmd/dlt/user/cmd.go
  cmd/edit/ingress/cmd.go
  cmd/whoami/cmd.go
  pkg/cluster/cluster.go
  pkg/ocm/helpers.go
  pkg/ocm/logs.go
  pkg/ocm/machines/machines.go
  pkg/ocm/regions/regions.go
  pkg/ocm/versions/versions.go
Labels: approved, lgtm

#148 nodes: Bring the default number of nodes down
  README.md
  cmd/create/cluster/cmd.go
  cmd/edit/cluster/cmd.go
  docs/moactl_create_cluster.md
  docs/moactl_edit_cluster.md
Labels: approved, lgtm

#143 Adding missing advanced options to IdP
  cmd/create/idp/cmd.go
  cmd/create/idp/ldap.go
  cmd/create/idp/openid.go
  docs/moactl_create_idp.md
Labels: approved

#142 idp: Provide help link for mapping method
  cmd/create/idp/cmd.go
  cmd/create/idp/github.go
  cmd/create/idp/gitlab.go
  cmd/create/idp/google.go
  cmd/create/idp/ldap.go
  cmd/create/idp/openid.go
Labels: approved

#141 idp-google: Make hosted_domain required unless mapping method is lookup
  cmd/create/idp/google.go
Labels: approved

#147 cluster: Default to using paid AMI
  cmd/create/cluster/cmd.go
  docs/moactl_create_cluster.md
Labels: approved

#136 cluster: Add flag to disable SCP checks
  cmd/create/cluster/cmd.go
  docs/moactl_create_cluster.md
  pkg/cluster/cluster.go
Labels: approved

#149 Init test cluster name to less than 15 char
  cmd/initialize/cmd.go
Labels: approved, lgtm

#150 Release 0.0.15
  CHANGES.adoc
  pkg/info/info.go
Labels: approved

#152 Added Display Name and Domain name to describe
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm, needs-ok-to-test

#153 cluster: Fail name check before calling API
  cmd/create/cluster/cmd.go
  pkg/cluster/cluster.go
Labels: approved, lgtm

#156 admin: Advise user to store password securely
  cmd/create/admin/cmd.go
Labels: approved, lgtm

#154 errors: Fall back to full error message
  pkg/cluster/cluster.go
  pkg/ocm/helpers.go
  pkg/ocm/logs.go
  pkg/ocm/machines/machines.go
  pkg/ocm/regions/regions.go
  pkg/ocm/versions/versions.go
Labels: approved, lgtm

#155 aws: Check region after profile credentials have been validated
  pkg/aws/client.go
Labels: approved, lgtm

#139 describe-cluster: Display Provision Shard if available
  cmd/describe/cluster/cmd.go
Labels: approved

#157 openid: Always show help text for claims
  cmd/create/idp/openid.go
Labels: approved

#160 users: Do not show cluster-admin user
  cmd/list/user/cmd.go
Labels: approved

#161 ccs: Ensure CCS is enabled before asking to disable SCP checks
  pkg/cluster/cluster.go
Labels: approved

#162 edit-cluster: Fallback to interactive mode
  cmd/edit/cluster/cmd.go
Labels: approved

#151 Osd 5227
  cmd/initialize/cmd.go
  pkg/aws/client.go
  pkg/aws/client_test.go
  templates/cloudformation/iam_user_osdCcsAdmin.json
Labels: approved, lgtm

#137 Fix idp name generation
  Makefile
  cmd/create/idp/cmd.go
  cmd/create/idp/cmd_test.go
  cmd/create/idp/idp_suite_test.go
  cmd/create/idp/mocks/identityprovider.go
Labels: approved, lgtm

#165 aws: Default to free AMI
  README.md
  cmd/create/cluster/cmd.go
  cmd/initialize/cmd.go
Labels: approved

#166 Release v0.0.16
  CHANGES.adoc
  assets/bindata.go
  pkg/info/info.go
Labels: approved

#172 Remove shard info from describe cluster
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm

#159 admin: Rename IDP to Cluster-Admin
  cmd/create/admin/cmd.go
  cmd/describe/admin/cmd.go
  cmd/dlt/admin/cmd.go
  cmd/list/idp/cmd.go
  pkg/ocm/helpers.go
Labels: approved

#163 ingress: Enable interactive mode
  cmd/create/ingress/cmd.go
  cmd/edit/ingress/cmd.go
Labels: approved

#175 Release v0.1.0
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm
