Repository openshift/rosa, pull requests merged in 2020-11, with the labels that each got.

#176 refactor(init): verify permissions for osdccsadmin using ValidateSCP
  cmd/initialize/cmd.go
  cmd/verify/permissions/cmd.go
  pkg/aws/client.go
  pkg/aws/permissions.go
Labels: approved, lgtm

#179 Added validation for name
  cmd/create/idp/cmd.go
Labels: approved, lgtm, ok-to-test

#173 Added Details Page Link
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm, ok-to-test

#178 machinepools: Support full CRUD operations for machine pools
  cmd/create/cluster/cmd.go
  cmd/create/cmd.go
  cmd/create/machinepool/cmd.go
  cmd/dlt/cmd.go
  cmd/dlt/machinepool/cmd.go
  cmd/edit/cmd.go
  cmd/edit/machinepool/cmd.go
  cmd/list/cmd.go
  cmd/list/machinepool/cmd.go
  docs/rosa_create.md
  docs/rosa_create_machinepool.md
  docs/rosa_delete.md
  docs/rosa_delete_machinepool.md
  docs/rosa_edit.md
  docs/rosa_edit_machinepool.md
  docs/rosa_list.md
  docs/rosa_list_machinepools.md
  pkg/ocm/helpers.go
  pkg/ocm/machines/machines.go
  pkg/ocm/regions/regions.go
Labels: approved

#118 Rotate osdCcsAdmin credentails on creation of each cluster
  assets/bindata.go
  cmd/create/cluster/cmd.go
  cmd/validations/validations.go
  pkg/aws/client.go
  pkg/aws/client_test.go
  pkg/aws/utils.go
  pkg/cluster/cluster.go
  pkg/ocm/regions/regions.go
  templates/cloudformation/iam_user_osdCcsAdmin.json
Labels: approved, lgtm, tide/merge-method-squash

#180 machinepool: Allow managing 'default' machinepool
  cmd/dlt/machinepool/cmd.go
  cmd/edit/cluster/cmd.go
  cmd/edit/machinepool/cmd.go
  cmd/list/machinepool/cmd.go
  docs/rosa_edit_cluster.md
Labels: approved

#181 Release v0.1.1
  CHANGES.adoc
  pkg/info/info.go
Labels: approved

#158 idp: Always use interactive mode on unset required flags
  cmd/create/idp/cmd.go
  cmd/create/idp/github.go
  cmd/create/idp/gitlab.go
  cmd/create/idp/google.go
  cmd/create/idp/ldap.go
Labels: approved

#185 Remove API ingress when listing ingress
  cmd/list/ingress/cmd.go
Labels: approved, lgtm, ok-to-test

#182 Enabling Interactive mode if no arguments specified
  cmd/create/cluster/cmd.go
  pkg/interactive/flag.go
Labels: approved, lgtm, ok-to-test

#186 machinepool: Fix interactive mode
  cmd/create/machinepool/cmd.go
  cmd/edit/machinepool/cmd.go
  docs/rosa_create_machinepool.md
Labels: approved

#183 Added Confirmation option for default network parameters
  cmd/create/cluster/cmd.go
  pkg/ocm/helpers.go
Labels: approved, lgtm, ok-to-test

#184 Add support for existing VPC
  Makefile
  cmd/create/cluster/cmd.go
  docs/rosa_create_cluster.md
  go.mod
  go.sum
  pkg/aws/client.go
  pkg/aws/client_test.go
  pkg/aws/mocks/ec2api.go
  pkg/aws/utils.go
  pkg/cluster/cluster.go
  pkg/interactive/interactive.go
Labels: approved, lgtm, ok-to-test

#187 Return clear error message when no version is found
  cmd/create/cluster/cmd.go
Labels: approved, lgtm, ok-to-test

#188 Release v0.1.2
  CHANGES.adoc
  pkg/info/info.go
Labels: approved

#189 create: Ask user before showing subnets
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#190 Dont ignore subnets from command line args if provided
  cmd/create/cluster/cmd.go
  docs/rosa_create_cluster.md
  pkg/interactive/interactive.go
Labels: approved, lgtm, ok-to-test
