Repository openshift/rosa, pull requests merged in 2020-09, with the labels that each got.

#97 verify-permissions: Do not check ViewBilling policy
  assets/bindata.go
  templates/policies/osd_scp_policy.json
Labels: approved, lgtm

#98 Add 'Channel Group' attribute to 'moactl describe cluster'
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm, needs-ok-to-test

#99 tests: Fix expected text comparison
  pkg/aws/client.go
  pkg/aws/client_test.go
Labels: approved

#92 Use default region for CloudFormation stack
  cmd/initialize/cmd.go
  pkg/aws/client.go
  pkg/cluster/cluster.go
  pkg/ocm/regions/regions.go
Labels: approved, lgtm

#94 refactor(create): add credential check for osdCcsAdmin when cluster starts to be created
  .gitignore
  cmd/create/cluster/cmd.go
  pkg/aws/client.go
  pkg/aws/client_test.go
Labels: approved, lgtm

#103 Added Timestamp to created date
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm, ok-to-test

#100 login: Ensure token is required
  cmd/login/cmd.go
Labels: approved

#102 versions: Allow querying for channel-groups
  cmd/create/cluster/cmd.go
  cmd/list/version/cmd.go
  pkg/ocm/versions/versions.go
Labels: approved

#105 Release v0.0.10
  CHANGES.adoc
  pkg/info/info.go
Labels: approved

#107 verify-quota: Avoid nil pointer dereferencing
  pkg/aws/client.go
  pkg/aws/quota.go
Labels: approved, lgtm

#106 verify-oc: Only warn when oc client missing
  cmd/verify/oc/cmd.go
Labels: approved

#101 create-cluster: Allow selective override of the marketplace AMI
  cmd/create/cluster/cmd.go
  docs/moactl_create_cluster.md
  go.mod
  go.sum
  pkg/ocm/properties/properties.go
  pkg/ocm/versions/versions.go
Labels: approved, lgtm

#110 Correct typos and incorrect commands in README
  README.md
Labels: approved, lgtm

#112 versions: Expose channel-group
  cmd/create/cluster/cmd.go
  cmd/list/version/cmd.go
  docs/moactl_create_cluster.md
  docs/moactl_list_versions.md
  go.mod
  go.sum
  pkg/cluster/cluster.go
  pkg/ocm/versions/versions.go
Labels: approved

#114 Use OCM SDK to get token expiration
  go.mod
  go.sum
  pkg/ocm/config/config.go
Labels: approved, lgtm

#115 Release v0.0.11
  CHANGES.adoc
  pkg/info/info.go
Labels: approved

#116 verify-quota: Check for only 100 vCPU
  pkg/aws/quota.go
Labels: approved

#111 README: Update based on output of newer commands
  README.md
  cmd/verify/oc/cmd.go
Labels: approved

#117 Release v0.0.12
  CHANGES.adoc
  pkg/info/info.go
Labels: approved

#119 Add Provision Type and Reason for error cluster
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm, ok-to-test

#109 OSD-4972
  cmd/create/cluster/cmd.go
  cmd/create/cmd.go
  cmd/dlt/cmd.go
  cmd/validations/validations.go
  pkg/aws/client.go
Labels: approved, lgtm

#126 remove validations from create command
  cmd/create/cmd.go
Labels: approved, lgtm

#121 idp: Warn the user that it will take about 1 minute to add IdP
  cmd/create/idp/cmd.go
Labels: approved

#124 logs: Improve warnings when cluster is pending
  cmd/logs/install/cmd.go
Labels: approved

#125 aws: Split configuration to ensure early failure
  pkg/aws/client.go
Labels: approved

#129 Release v0.0.13
  CHANGES.adoc
  pkg/info/info.go
Labels: approved
