Repository openshift/rosa, pull requests merged in 2021-05, with the labels that each got.

#319 Enable PrivateLink on clusters
  cmd/create/cluster/cmd.go
  cmd/create/ingress/cmd.go
  cmd/edit/ingress/cmd.go
  go.sum
  pkg/cluster/cluster.go
Labels: approved

#334 PrivateLink: Hide references to PrivateLink
  cmd/create/cluster/cmd.go
Labels: approved

#335 Correctly handle --disable-scp-checks argument in rosa init
  cmd/initialize/cmd.go
Labels: approved, lgtm, ok-to-test

#339 describe: Output OIDC Endpoint URL if available
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm

#340 Release v1.0.6
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm

#341 Updated the details link
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm

#331 Allow setting 0 replicas to autoscaling machine pool (Not default)
  cmd/create/machinepool/cmd.go
  cmd/edit/machinepool/cmd.go
Labels: approved, lgtm

#342 Added custom IAM Roles
  cmd/create/cluster/cmd.go
  go.mod
  go.sum
  pkg/cluster/cluster.go
  vendor/github.com/AlecAivazis/survey/v2/terminal/LICENSE.txt
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.adoc
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/resource_quota_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/resource_quota_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/resource_quota_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/custom_iam_roles_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/custom_iam_roles_list_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/custom_iam_roles_list_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/custom_iam_roles_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/custom_iam_roles_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/sts_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/sts_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/sts_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/jobqueue/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/jobqueue/v1/queue_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/jobqueue/v1/queue_resource_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/jobqueue/v1/queue_server.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm

#338 Remove default region
  cmd/initialize/cmd.go
  pkg/aws/client.go
  pkg/aws/tags/tags.go
Labels: approved, lgtm

#345 describe: Display description during Pending state
  cmd/create/cluster/cmd.go
  cmd/describe/cluster/cmd.go
  pkg/cluster/cluster.go
Labels: approved

#346 Release v1.0.7
  CHANGES.adoc
  pkg/info/info.go
Labels: approved

#344 Added SSO Validation
  pkg/ocm/connection.go
Labels: approved, lgtm

#348 Disable IAM user checks for STS
  cmd/initialize/cmd.go
Labels: approved

#343 we do our best to validate quotas, but due to limitations in certain …
  cmd/verify/quota/cmd.go
Labels: approved, lgtm

#352 Fix tests with missing TagUser call
  pkg/aws/client_test.go
Labels: approved, lgtm

#350 Added wait for accountclaims for the clusters in the same user ARN to get ready
  pkg/cluster/cluster.go
Labels: approved, lgtm

#349 Added new rosa list instance-types api
  cmd/list/cmd.go
  cmd/list/instancetypes/cmd.go
Labels: approved, lgtm

#351 Support STS users
  cmd/create/cluster/cmd.go
  pkg/aws/client.go
  pkg/aws/permissions.go
  pkg/aws/utils.go
Labels: approved, lgtm, tide/merge-method-squash
