Repository openshift/rosa, pull requests merged in 2021-01, with the labels that each got.

#204 login: Add link to retrieve tokens
  cmd/login/cmd.go
  docs/rosa_init.md
  docs/rosa_login.md
Labels: approved, lgtm, ok-to-test

#205 Add autoscaling support
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/cmd.go
  cmd/describe/cluster/cmd.go
  cmd/edit/machinepool/cmd.go
  cmd/list/machinepool/cmd.go
  docs/rosa_create_cluster.md
  docs/rosa_create_machinepool.md
  docs/rosa_edit_machinepool.md
  pkg/cluster/cluster.go
Labels: approved

#208 Release v0.1.4
  CHANGES.adoc
  pkg/info/info.go
Labels: approved

#210 Require min/max replicas iff existing machinepool autoscaling is disabled
  cmd/edit/machinepool/cmd.go
Labels: approved, lgtm

#212 add openshift version to describe output
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm

#216 Release v0.1.5
  CHANGES.adoc
  pkg/info/info.go
Labels: approved

#215 cluster-admins: Remove explicit enable
  cmd/edit/cluster/cmd.go
  cmd/list/user/cmd.go
  docs/rosa_edit_cluster.md
  pkg/cluster/cluster.go
Labels: approved, lgtm

#214 machines: Sort machine types by CPU cores
  pkg/ocm/machines/machines.go
Labels: approved

#217 add multi-az status to describe
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm

#218 init: Use explicit login flag checks
  cmd/initialize/cmd.go
Labels: approved

#219 Release v0.1.6
  CHANGES.adoc
  pkg/info/info.go
Labels: approved

#220 fix example
  docs/rosa_edit_machinepool.md
Labels: approved, lgtm

#221 Align command with auto-generated docs
  cmd/edit/machinepool/cmd.go
Labels: approved
