Repository openshift/rosa, pull requests merged in 2021-11, with the labels that each got.

#512 Clarify `verify permissions` cmd is only for non-STS clusters
  cmd/verify/permissions/cmd.go
Labels: approved, lgtm

#513 fix minor typo
  cmd/create/cluster/cmd.go
Labels: approved, needs-ok-to-test, lgtm

#506 updated pendo event for rosa
  cmd/create/accountroles/cmd.go
  cmd/create/oidcprovider/cmd.go
  cmd/create/operatorroles/cmd.go
  cmd/dlt/accountroles/cmd.go
  cmd/dlt/oidcprovider/cmd.go
  cmd/dlt/operatorrole/cmd.go
  cmd/initialize/cmd.go
  cmd/verify/permissions/cmd.go
  cmd/verify/quota/cmd.go
  go.mod
  go.sum
  pkg/ocm/helpers.go
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.adoc
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/add_on_installation_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/add_on_installation_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/add_on_installation_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/event_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/event_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/event_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/proxy_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/proxy_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/proxy_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/helpers/json_helpers.go
  vendor/github.com/openshift-online/ocm-sdk-go/retry/transport_wrapper.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm

#514 Check for pre-existing operator roles and error if they exist
  cmd/create/cluster/cmd.go
  pkg/aws/client.go
  pkg/aws/policies.go
Labels: approved, lgtm

#510 add rosa upgrade account/operator role
  cmd/create/accountroles/cmd.go
  cmd/create/operatorroles/cmd.go
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/cmd.go
  cmd/upgrade/operatorroles/cmd.go
  pkg/aws/client.go
  pkg/aws/helpers.go
  pkg/aws/policies.go
Labels: approved, lgtm

#511 removed --enable_proxy argument
  cmd/create/cluster/cmd.go
  pkg/ocm/clusters.go
Labels: approved, lgtm, ok-to-test

#515 changing cluster proxy attributes to pointers
  cmd/create/cluster/cmd.go
  pkg/ocm/clusters.go
Labels: approved, lgtm, ok-to-test

#509 validate sts roles on sts cluster upgrade
  cmd/create/accountroles/cmd.go
  cmd/create/cluster/cmd.go
  cmd/create/oidcprovider/cmd.go
  cmd/create/operatorroles/cmd.go
  cmd/dlt/accountroles/cmd.go
  cmd/dlt/oidcprovider/cmd.go
  cmd/dlt/operatorrole/cmd.go
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/cluster/cmd.go
  cmd/upgrade/operatorroles/cmd.go
  pkg/aws/client.go
  pkg/aws/flag.go
  pkg/aws/policies.go
Labels: approved, lgtm

#520 fix interactive setting of `mode` option
  cmd/create/accountroles/cmd.go
  cmd/create/oidcprovider/cmd.go
  cmd/create/operatorroles/cmd.go
  cmd/dlt/accountroles/cmd.go
  cmd/dlt/oidcprovider/cmd.go
  cmd/dlt/operatorrole/cmd.go
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/operatorroles/cmd.go
Labels: approved, lgtm

#517 aws: Add ROSACLI/version to User-Agent string
  pkg/aws/client.go
  pkg/info/info.go
Labels: approved, lgtm

#518 clean/fix role validation for upgrade
  cmd/create/operatorroles/cmd.go
  pkg/aws/client.go
  pkg/aws/helpers.go
  pkg/aws/policies.go
Labels: approved, lgtm

#523 Upgrade cluster bug fixes
  cmd/upgrade/cluster/cmd.go
  cmd/upgrade/operatorroles/cmd.go
Labels: approved, lgtm

#527 Added support for master-iam-role
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#525 Add ocm user role
  .gitignore
  assets/bindata.go
  cmd/create/cmd.go
  cmd/create/userrole/cmd.go
  cmd/link/cmd.go
  cmd/link/userrole/cmd.go
  cmd/rosa/main.go
  pkg/aws/helpers.go
  pkg/aws/policies.go
  pkg/aws/tags/tags.go
  pkg/ocm/helpers.go
  templates/policies/sts_ocm_user_trust_policy.json
Labels: approved, lgtm

#526 STS: Create OCM Role
  assets/bindata.go
  cmd/create/cmd.go
  cmd/create/ocmrole/cmd.go
  cmd/link/cmd.go
  cmd/link/ocmrole/cmd.go
  pkg/aws/helpers.go
  pkg/aws/policies.go
  pkg/aws/tags/tags.go
  pkg/ocm/helpers.go
  templates/policies/sts_ocm_permission_policy.json
  templates/policies/sts_ocm_trust_policy.json
Labels: approved, lgtm

#528 added support for operator prefix
  cmd/create/operatorroles/cmd.go
Labels: approved, lgtm

#530 add interactive mode for link user/ocm role
  cmd/link/ocmrole/cmd.go
  cmd/link/userrole/cmd.go
Labels: approved, lgtm

#529 added edit support for UVM
  cmd/create/cluster/cmd.go
  cmd/edit/cluster/cmd.go
  pkg/ocm/clusters.go
Labels: approved, lgtm

#531 Release v1.1.6
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm

#532 Fix crash when calling link cmd internally
  cmd/create/ocmrole/cmd.go
  cmd/create/userrole/cmd.go
  cmd/link/ocmrole/cmd.go
  cmd/link/userrole/cmd.go
Labels: approved, lgtm

#535 Add org external id to ocm role name
  cmd/create/ocmrole/cmd.go
  cmd/create/operatorroles/cmd.go
  cmd/create/userrole/cmd.go
  cmd/link/ocmrole/cmd.go
  pkg/aws/client.go
  pkg/aws/helpers.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#524 ROSA: Support editing cluster-wide proxy
  cmd/create/cluster/cmd.go
  cmd/edit/cluster/cmd.go
  pkg/interactive/validation.go
  pkg/ocm/clusters.go
Labels: approved, lgtm, ok-to-test

#537 link: Allow linking multiple role ARNs
  pkg/ocm/helpers.go
Labels: approved, lgtm

#538 ocm-role: Add permission to describe VPCs
  assets/bindata.go
  templates/policies/sts_ocm_permission_policy.json
Labels: approved, lgtm

#536 add org admin validation for ocm-role
  cmd/create/ocmrole/cmd.go
  cmd/create/userrole/cmd.go
  cmd/link/cmd.go
  cmd/link/ocmrole/cmd.go
  cmd/link/userrole/cmd.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#539 improve UX in ROSA edit cluster and ROSA delete roles
  cmd/dlt/accountroles/cmd.go
  cmd/dlt/oidcprovider/cmd.go
  cmd/dlt/operatorrole/cmd.go
  cmd/edit/cluster/cmd.go
Labels: approved, lgtm

#540 Change rosa init help message
  cmd/initialize/cmd.go
Labels: approved, lgtm, ok-to-test

#541 fix org admin validation
  cmd/link/ocmrole/cmd.go
  cmd/link/userrole/cmd.go
Labels: approved, lgtm
