Repository openshift/rosa, pull requests merged in 2022-12, with the labels that each got.

#959 Release v1.2.10
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm

#957 [SDA-3843] Align spacing listing users
  cmd/list/user/cmd.go
Labels: approved, lgtm

#958 [SDA-4515] Phrasing
  cmd/login/cmd.go
Labels: approved, lgtm

#960 [SDA-5825] Remove auth url info from LDAP idp when listing
  cmd/list/idp/cmd.go
  pkg/ocm/idps.go
Labels: approved, lgtm

#955 [SDA-7420] Check if any new operator roles have been created before hand
  cmd/upgrade/operatorroles/cmd.go
Labels: approved, lgtm

#961 [SDA-7474] Upgrading from pre release would fail to validate version
  cmd/create/cluster/cmd.go
  cmd/upgrade/cluster/cmd.go
  cmd/upgrade/roles/cmd.go
  pkg/ocm/versions.go
Labels: approved, lgtm

#963 Log a warning if the user's organization doesn't have the needed capability
  cmd/list/region/cmd.go
Labels: approved, lgtm, ok-to-test

#964 [OHSS-14855] Using unified path on upgrade roles/operator-roles
  cmd/upgrade/operatorroles/cmd.go
  cmd/upgrade/roles/cmd.go
  pkg/helper/roles/helpers.go
Labels: approved, lgtm

#966 [SDA-7233] Validating regex for machine pool label key and value
  cmd/create/machinepool/machinepool.go
Labels: approved, lgtm

#967 [SDA-3685] Add error message when CA is passed but github hostname is not
  cmd/create/idp/github.go
Labels: approved, lgtm

#968 Describe cluster - print `infra_id` to the output
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm

#969 Using lower case before comparing expected acc role arns
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#965 [OHSS-14855] Retrieve operator role prefix from backend
  pkg/helper/roles/helpers.go
Labels: approved, lgtm

#977 [SDA-7580] Adjust NodePool headers
  cmd/describe/cluster/cmd.go
  cmd/list/machinepool/nodepool.go
Labels: approved, lgtm

#971 Using LCP to retrieve operator policy prefix
  cmd/upgrade/roles/cmd.go
  pkg/aws/helpers.go
  pkg/helper/helpers.go
Labels: approved, lgtm

#974 Allow editing default machine pool labels
  cmd/edit/machinepool/machinepool.go
  pkg/ocm/clusters.go
Labels: approved, lgtm

#978 Enable day1 default machine pool labels
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/machinepool.go
  pkg/ocm/clusters.go
Labels: approved, lgtm

#980 [SDA-7565] Use default/in-place value for addon param first
  cmd/edit/addon/cmd.go
Labels: approved, lgtm

#981 Add default machine pool labels validations
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/machinepool.go
Labels: approved, lgtm

#979 make rosa describe upgrade
  cmd/describe/cmd.go
  cmd/describe/upgrade/cmd.go
  pkg/ocm/upgrades.go
Labels: approved, needs-ok-to-test, lgtm

#983 [SDA-7633] Remove channel group from recreate output
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#986 Refactor `GetPolicies` function
  cmd/create/accountroles/cmd.go
  cmd/create/ocmrole/cmd.go
  cmd/create/operatorroles/cmd.go
  cmd/create/userrole/cmd.go
  cmd/install/addon/cmd.go
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/operatorroles/cmd.go
  cmd/upgrade/roles/cmd.go
  pkg/aws/client.go
  pkg/aws/helpers.go
  pkg/aws/permissions.go
  pkg/helper/roles/helpers.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#989 [SDA-7657] Using tabwriters options instead of manually formatting `list users`
  cmd/list/user/cmd.go
Labels: approved, lgtm

#985 fix ux issues related to rosa describe
  cmd/describe/upgrade/cmd.go
Labels: approved, lgtm, ok-to-test

#990 Fix scaling bug and improve interactive mode
  cmd/edit/machinepool/machinepool.go
Labels: approved, lgtm

#988 Create account roles with existing policies
  cmd/create/accountroles/cmd.go
  cmd/create/ocmrole/cmd.go
  cmd/create/operatorroles/cmd.go
  cmd/create/userrole/cmd.go
  cmd/install/addon/cmd.go
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/operatorroles/cmd.go
  cmd/upgrade/roles/cmd.go
  pkg/aws/client.go
  pkg/aws/helpers.go
  pkg/aws/policies.go
  pkg/aws/tags/tags.go
  pkg/ocm/config.go
Labels: approved, lgtm
