Repository openshift/rosa, pull requests merged in 2022-03, with the labels that each got.

#617 Fix bug - `delete ocm-role` should be hidden in rosa cli
  cmd/dlt/ocmrole/cmd.go
Labels: approved, lgtm

#588 Refactor MachineTypes handling
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/cmd.go
  pkg/ocm/machines.go
Labels: approved, lgtm

#620 Improve `rosa unlink user role` error message
  cmd/unlink/userrole/cmd.go
Labels: approved, lgtm

#610 Add policies for 4.10
  assets/bindata.go
  cmd/create/cluster/cmd.go
  cmd/create/operatorroles/cmd.go
  pkg/aws/policies.go
  pkg/ocm/helpers.go
  templates/policies/openshift_cluster_storage_operator_csi_cloud_credentials_policy.json
  templates/policies/sts_installer_permission_policy.json
Labels: approved, lgtm

#619 Fix bug - validate role type before deletion
  cmd/dlt/ocmrole/cmd.go
  cmd/dlt/userrole/cmd.go
  pkg/aws/client.go
  pkg/aws/policies.go
Labels: approved, lgtm

#618 Fix upgrade issue
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/cluster/cmd.go
  pkg/aws/policies.go
Labels: approved, lgtm

#621 Add support for seamless upgrade from any rosa version
  cmd/upgrade/accountroles/cmd.go
  pkg/aws/client.go
  pkg/aws/policies.go
Labels: approved, lgtm

#616 HTPasswd bug fixes corresponding with some CS changes
  cmd/create/admin/cmd.go
  cmd/create/idp/htpasswd.go
  cmd/dlt/admin/cmd.go
  pkg/ocm/idps.go
Labels: approved, needs-ok-to-test, lgtm

#623 sda-5576-Fix upgrades to 4.9 or less with 4.10 operator roles
  cmd/upgrade/accountroles/cmd.go
  pkg/aws/policies.go
Labels: approved, lgtm

#624 add new support policy and policy for verifier
  assets/bindata.go
  templates/policies/sts_installer_permission_policy.json
  templates/policies/sts_support_permission_policy.json
Labels: approved, lgtm

#625 fix operator policies for 4.10
  assets/bindata.go
  pkg/aws/policies.go
  templates/policies/openshift_cloud_network_config_controller_cloud_credentials_policy.json
  templates/policies/openshift_cluster_storage_operator_csi_cloud_credentials_policy.json
Labels: approved, lgtm

#627 Revert "HTPasswd bug fixes corresponding with some CS changes"
  cmd/create/admin/cmd.go
  cmd/create/idp/htpasswd.go
  cmd/dlt/admin/cmd.go
  pkg/ocm/idps.go
Labels: approved, lgtm

#631 Revert "Introducing HTPasswd IDP"
  cmd/create/admin/cmd.go
  cmd/create/idp/cmd.go
  cmd/create/idp/htpasswd.go
  cmd/dlt/admin/cmd.go
  pkg/ocm/idps.go
Labels: approved, lgtm, ok-to-test

#632 Release v1.1.10
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm

#633 fix operator roles issue for old rosa versions
  cmd/create/cluster/cmd.go
  cmd/create/operatorroles/cmd.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#634 fix operator role issue
  cmd/create/operatorroles/cmd.go
Labels: approved, lgtm

#635 Release v1.1.11
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm

#622 Sort roles to display linked ones first
  cmd/list/ocmroles/cmd.go
  cmd/list/userroles/cmd.go
  pkg/aws/sts.go
Labels: approved, lgtm

#626 Refactor `list ocm-role` to use a map of linked roles
  cmd/list/ocmroles/cmd.go
Labels: approved, lgtm

#636 Add quota service permissions to the `installer policy`
  assets/bindata.go
  templates/policies/sts_installer_permission_policy.json
Labels: approved, lgtm

#640 Set minimum retry delay for AWS API calls
  pkg/aws/client.go
Labels: approved, lgtm

#641 Re-introducing HTPasswd IDP after revert
  cmd/create/admin/cmd.go
  cmd/create/idp/cmd.go
  cmd/create/idp/htpasswd.go
  cmd/dlt/admin/cmd.go
  pkg/ocm/idps.go
Labels: approved, lgtm, ok-to-test

#645 Add KMS permission to installer and more permissions for ocm role
  assets/bindata.go
  templates/policies/sts_installer_permission_policy.json
  templates/policies/sts_ocm_admin_permission_policy.json
Labels: approved, lgtm

#646 added link to help menu
  cmd/rosa/main.go
Labels: approved, lgtm, ok-to-test

#649 Permit overriding confirmation prompt for cluster upgrades
  cmd/upgrade/cluster/cmd.go
Labels: approved, needs-ok-to-test, lgtm

#653 Fix bug - create ocm-role - prompt the role ARN
  cmd/create/ocmrole/cmd.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#656 add more permissions to ocm admin role
  assets/bindata.go
  templates/policies/sts_ocm_admin_permission_policy.json
Labels: approved, lgtm
