Repository openshift/rosa, pull requests merged in 2022-01, with the labels that each got.

#554 Send rosa cli login event to pendo
  cmd/login/cmd.go
  pkg/ocm/helpers.go
Labels: approved, lgtm, ok-to-test

#556 Generate static assets for STS support permissions
  assets/bindata.go
Labels: approved, lgtm

#557 fix etcdEncryption
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#560 fixed issue with operator role upgrade
  pkg/aws/policies.go
Labels: approved, lgtm

#563 fixed upgade' to 'upgrade'
  cmd/upgrade/cluster/cmd.go
Labels: approved, lgtm

#559 OVN: Add network type selection
  cmd/create/cluster/cmd.go
  cmd/describe/cluster/cmd.go
  go.mod
  go.sum
  pkg/ocm/clusters.go
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/authentication/handler.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/add_on_parameter_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/add_on_parameter_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/add_on_parameter_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/key_rings_inquiry_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/key_rings_inquiry_server.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/network_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/network_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/network_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/vpcs_inquiry_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/vpcs_inquiry_server.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm

#565 fix issue with delete operatorrole/oidcprovider role
  cmd/dlt/oidcprovider/cmd.go
  cmd/dlt/operatorrole/cmd.go
  pkg/ocm/clusters.go
Labels: approved, lgtm

#564 clean up upgrade command
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/cluster/cmd.go
  cmd/upgrade/operatorroles/cmd.go
  pkg/aws/client.go
  pkg/aws/policies.go
Labels: approved, lgtm

#544 Adding password argument to create admin
  cmd/create/admin/cmd.go
Labels: approved, lgtm, ok-to-test

#552 idp: Enable interactive mode when missing required flags
  cmd/create/idp/cmd.go
  cmd/create/idp/github.go
  cmd/create/idp/gitlab.go
  cmd/create/idp/google.go
  cmd/create/idp/ldap.go
  cmd/create/idp/openid.go
Labels: approved, lgtm

#568 add rosa cli version to header
  pkg/ocm/client.go
Labels: approved, lgtm

#570 added Version gates acks
  cmd/create/accountroles/cmd.go
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/cluster/cmd.go
  pkg/aws/helpers.go
  pkg/ocm/upgrades.go
Labels: approved, lgtm

#571 Fix issue with Auto mode during upgrade cluster
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/cluster/cmd.go
Labels: approved, lgtm

#575 Fix missing vendored module
  go.mod
  vendor/modules.txt
Labels: approved, lgtm

#573 remove openshift version from operator role name
  cmd/create/operatorroles/cmd.go
Labels: approved, lgtm

#576 Add support for warning message version gates
  cmd/upgrade/cluster/cmd.go
  go.mod
  go.sum
  vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
  vendor/github.com/onsi/ginkgo/v2/internal/writer.go
  vendor/github.com/onsi/ginkgo/v2/table_dsl.go
  vendor/github.com/onsi/ginkgo/v2/types/errors.go
  vendor/github.com/onsi/ginkgo/v2/types/version.go
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/version_gate_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/version_gate_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/version_gate_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/go.mod
  vendor/github.com/openshift-online/ocm-sdk-go/go.sum
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm

#578 Verify chosen machine pool type is available
  pkg/ocm/machines.go
Labels: approved, lgtm, ok-to-test

#577 Avoid nil pointer dereference in cluster create
  cmd/create/cluster/cmd.go
Labels: approved, lgtm, ok-to-test

#582 Revert "Verify chosen machine pool type is available"
  pkg/ocm/machines.go
Labels: approved, needs-ok-to-test, lgtm

#561 ocp: Add list acknowledgement gate support
  cmd/list/cmd.go
  cmd/list/gates/cmd.go
  go.mod
  go.sum
  pkg/ocm/gates.go
  pkg/output/output.go
  vendor/github.com/nathan-fiscaletti/consolesize-go/LICENSE
  vendor/github.com/nathan-fiscaletti/consolesize-go/README.md
  vendor/github.com/nathan-fiscaletti/consolesize-go/consolesize_unix.go
  vendor/github.com/nathan-fiscaletti/consolesize-go/consolesize_windows.go
  vendor/modules.txt
Labels: approved, lgtm

#579 Update OWNERS file
  OWNERS
Labels: approved, lgtm

#584 Release v1.1.8
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm

#585 ROSA CLI Interactive install - make the choice default STS
  cmd/create/cluster/cmd.go
Labels: approved, lgtm, ok-to-test

#587 The attribute name in error message should be same with the correct proxy attribute in body
  pkg/ocm/helpers.go
Labels: approved, lgtm, ok-to-test

#586 Add IAM List and Get role permissions to support policy
  assets/bindata.go
  templates/policies/sts_support_permission_policy.json
Labels: approved, lgtm

#589 Fix bug - remove duplicated error message when deleting a cluster
  cmd/dlt/cluster/cmd.go
Labels: approved, lgtm, ok-to-test
