Repository openshift/rosa, pull requests merged in 2022-11, with the labels that each got.

#915 add `--yes` to create cluster cmd
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#916 fix hosted cluster parameter in create cluster
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#917 unhide tags during cluster create
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#919 fix: add tags check when b.tags nil
  pkg/aws/commandbuilder/commandbuilder.go
Labels: approved, lgtm

#918 Create/oidcprovider bug sets interactive.Enable
  cmd/create/oidcprovider/cmd.go
Labels: approved, lgtm

#920 Output current environment when it is not production
  cmd/dlt/operatorrole/cmd.go
Labels: approved, needs-ok-to-test, lgtm

#922 FIPS: Unhide flag
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#923 Revert "[SDA-6643] STS is now default mode for cluster creation, added flags for mint mode/non-sts mode"
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#924 [SDA-6443] Message deprecation non sts (legacy iam creds)
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#928 Bump OCM SDK GO version to v0.1.293
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cloud_provider_data_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cloud_provider_data_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cloud_provider_data_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm

#929 Create machinepool - filter supported instances by availability zones
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/cmd.go
  pkg/aws/client.go
  pkg/ocm/machines.go
Labels: approved, lgtm

#931 Add aws command builder unit tests
  pkg/aws/commandbuilder/commandbuilder.go
  pkg/aws/commandbuilder/commandbuilder_suite_test.go
  pkg/aws/commandbuilder/commandbuilder_test.go
Labels: approved, lgtm

#932 Create a machine pool - prevent choosing a spot instance for a local AZ
  cmd/create/machinepool/cmd.go
  pkg/aws/client.go
Labels: approved, lgtm

#897 [SDE-1816] new command upgrade roles from cluster
  cmd/create/accountroles/cmd.go
  cmd/create/cluster/cmd.go
  cmd/create/ocmrole/cmd.go
  cmd/create/operatorroles/cmd.go
  cmd/create/service/cmd.go
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/cluster/cmd.go
  cmd/upgrade/cmd.go
  cmd/upgrade/operatorroles/cmd.go
  cmd/upgrade/roles/cmd.go
  pkg/aws/client.go
  pkg/aws/commandbuilder/helper/roles/roles.go
  pkg/aws/helpers.go
  pkg/aws/policies.go
  pkg/aws/sts.go
  pkg/helper/helpers.go
  pkg/helper/roles/helpers.go
  pkg/ocm/flag.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#933 Create a machine pool with a different region configured in the AWS CLI
  cmd/create/machinepool/cmd.go
Labels: approved, lgtm

#934 Create machine pool - display spinner when fetching instance types
  cmd/create/machinepool/cmd.go
Labels: approved, lgtm

#936 Add channel group and option to choose version for policy tags in upgrade roles cmd
  cmd/create/accountroles/cmd.go
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/cluster/cmd.go
  cmd/upgrade/roles/cmd.go
  pkg/aws/commandbuilder/commandbuilder.go
  pkg/helper/helpers.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#938 [SDA-7342] Fixing wrongful behaviors on upgrade roles
  cmd/upgrade/roles/cmd.go
  pkg/helper/helpers.go
Labels: approved, lgtm

#940 [SDA-7207] Invert condition for no reason to update ingress
  cmd/edit/ingress/cmd.go
Labels: approved, lgtm

#939 [SDA-7345] Prompt mode for upgrade cluster when sts and mode is empty
  cmd/upgrade/cluster/cmd.go
  cmd/upgrade/roles/cmd.go
Labels: approved, lgtm

#941 [SDA-7201] Always show warning, don't go into interactive if non sts mode is enabled
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#942 [SDA-7382] Checking undefined aws region on init and create cluster
  cmd/create/cluster/cmd.go
  cmd/initialize/cmd.go
  pkg/aws/helpers.go
  pkg/aws/region/flag.go
  pkg/helper/helpers.go
  pkg/interactive/interactive.go
  pkg/ocm/regions.go
Labels: approved, lgtm

#944 [SDA-6826] Handle empty strings before validation
  cmd/create/cluster/cmd.go
  cmd/edit/cluster/cmd.go
  pkg/helper/helpers.go
Labels: approved, lgtm

#947 Adding check for Changes in `replicas` flag too
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#945 Move HostedCP region supports check to the backend side
  cmd/list/region/cmd.go
  go.mod
  go.sum
  pkg/ocm/regions.go
  pkg/ocm/regions_test.go
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cloud_region_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cloud_region_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cloud_region_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#948 SDA-7290 Remove redundant quotation
  cmd/describe/cluster/cmd.go
Labels: approved, needs-ok-to-test, lgtm

#951 Release v1.2.9
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm

#952 Check HostedCP version support also in interactive mode
  cmd/create/cluster/cmd.go
  cmd/create/cluster/cmd_test.go
  pkg/ocm/versions.go
  pkg/ocm/versions_test.go
Labels: approved, lgtm, ok-to-test

#953 [SDA-7429] Going through all policies to check upgrade
  cmd/upgrade/operatorroles/cmd.go
  pkg/aws/policies.go
Labels: approved, lgtm
