Repository openshift/rosa, pull requests merged in 2022-06, with the labels that each got.

#724 The wildcard domain is not allowed to set in no_proxy field
  pkg/aws/helpers.go
Labels: approved, needs-ok-to-test, lgtm

#728 Unhide ocm/user link/unlink role
  cmd/link/cmd.go
  cmd/unlink/cmd.go
Labels: approved, lgtm

#727 Fix order of instance types
  cmd/create/cluster/cmd.go
  pkg/ocm/helpers.go
  pkg/ocm/machines.go
Labels: approved, lgtm

#717 command to list parameters of add-on installation
  cmd/describe/cmd.go
  cmd/describe/installation/cmd.go
Labels: approved, lgtm

#732 token: Allow login with encrypted tokens
  cmd/login/cmd.go
  cmd/whoami/cmd.go
  go.sum
  pkg/ocm/client.go
  pkg/ocm/config.go
  pkg/ocm/token.go
Labels: approved, lgtm

#733 support creation of managed services with non-custom configurations
  pkg/ocm/managedservice.go
Labels: approved, lgtm

#737 support -c flag when using "rosa describe addon-installation"
  cmd/describe/installation/cmd.go
Labels: approved, lgtm

#736 support host-prefix during managed service creation
  cmd/create/service/cmd.go
  pkg/ocm/managedservice.go
Labels: approved, lgtm

#739 Add helpers for creating a policy document and allowing actions
  pkg/aws/policy_document.go
Labels: approved, lgtm

#722 STS for addons - helper methods
  cmd/create/cluster/cmd.go
  cmd/create/service/cmd.go
  pkg/aws/helpers.go
  pkg/ocm/addons.go
Labels: approved, lgtm

#730 creating htpassword idp still prompts for username even if provided
  cmd/create/idp/htpasswd.go
Labels: approved, lgtm, ok-to-test

#742 add more throttle metrics
  cmd/upgrade/accountroles/cmd.go
Labels: approved, lgtm

#743 Prompt the user to select multi or single AZ only in an interactive mood
  cmd/create/machinepool/cmd.go
Labels: approved, lgtm

#744 Fix bug - remove replicas constraint when editing single AZ machine pool
  cmd/edit/machinepool/cmd.go
Labels: approved, lgtm

#746 Create a single AZ machine pool - availability zone flag
  cmd/create/machinepool/cmd.go
Labels: approved, lgtm

#749 Release v1.2.3
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm

#740 Initial implementation of runtime
  cmd/create/accountroles/cmd.go
  cmd/create/admin/cmd.go
  cmd/create/cluster/cmd.go
  cmd/describe/addon/cmd.go
  cmd/describe/cluster/cmd.go
  pkg/rosa/runtime.go
Labels: approved, lgtm

#754 Migrate describe commands to use runtime
  cmd/describe/admin/cmd.go
  cmd/describe/installation/cmd.go
  cmd/describe/service/cmd.go
Labels: approved, lgtm

#756 Migrate delete commands to use runtime
  cmd/dlt/accountroles/cmd.go
  cmd/dlt/admin/cmd.go
  cmd/dlt/cluster/cmd.go
  cmd/dlt/idp/cmd.go
  cmd/dlt/ingress/cmd.go
  cmd/dlt/ocmrole/cmd.go
  cmd/dlt/oidcprovider/cmd.go
  cmd/dlt/operatorrole/cmd.go
  cmd/dlt/service/cmd.go
  cmd/dlt/upgrade/cmd.go
  cmd/dlt/userrole/cmd.go
Labels: approved, lgtm

#755 Migrate create commands to use runtime
  cmd/create/admin/cmd.go
  cmd/create/idp/cmd.go
  cmd/create/idp/htpasswd.go
  cmd/create/ingress/cmd.go
  cmd/create/machinepool/cmd.go
  cmd/create/ocmrole/cmd.go
  cmd/create/oidcprovider/cmd.go
  cmd/create/operatorroles/cmd.go
  cmd/create/service/cmd.go
  cmd/create/userrole/cmd.go
  cmd/describe/admin/cmd.go
  cmd/dlt/idp/cmd.go
Labels: approved, lgtm

#753 idp: Provide shell completion for IdP types
  cmd/create/idp/cmd.go
Labels: approved, lgtm

#757 Migrate edit commands to use runtime
  cmd/edit/addon/cmd.go
  cmd/edit/cluster/cmd.go
  cmd/edit/ingress/cmd.go
  cmd/edit/machinepool/cmd.go
  cmd/edit/service/cmd.go
Labels: approved, lgtm

#761 Migrate list commands to use runtime
  cmd/list/accountroles/cmd.go
  cmd/list/addon/cmd.go
  cmd/list/cluster/cmd.go
  cmd/list/gates/cmd.go
  cmd/list/idp/cmd.go
  cmd/list/ingress/cmd.go
  cmd/list/instancetypes/cmd.go
  cmd/list/machinepool/cmd.go
  cmd/list/ocmroles/cmd.go
  cmd/list/region/cmd.go
  cmd/list/service/cmd.go
  cmd/list/upgrade/cmd.go
  cmd/list/user/cmd.go
  cmd/list/userroles/cmd.go
  cmd/list/version/cmd.go
Labels: approved, lgtm

#762 Migrate remaining commands to use runtime
  cmd/dlt/machinepool/cmd.go
  cmd/install/addon/cmd.go
  cmd/upgrade/cluster/cmd.go
  cmd/upgrade/operatorroles/cmd.go
Labels: approved, lgtm

#751 Allow to select availability zones when creating a non-BYOVPC cluster
  cmd/create/cluster/cmd.go
  pkg/aws/client.go
Labels: approved, lgtm

#758 Drop unused CheckStackReadyForCreateCluster method
  pkg/aws/cloudformation.go
Labels: approved, lgtm

#764 Add cluster lookup methods to runtime
  cmd/create/admin/cmd.go
  cmd/create/idp/cmd.go
  cmd/create/ingress/cmd.go
  cmd/create/machinepool/cmd.go
  cmd/create/oidcprovider/cmd.go
  cmd/create/operatorroles/cmd.go
  cmd/describe/admin/cmd.go
  cmd/describe/cluster/cmd.go
  cmd/describe/installation/cmd.go
  cmd/dlt/admin/cmd.go
  cmd/dlt/cluster/cmd.go
  cmd/dlt/idp/cmd.go
  cmd/dlt/ingress/cmd.go
  cmd/dlt/machinepool/cmd.go
  cmd/dlt/oidcprovider/cmd.go
  cmd/dlt/upgrade/cmd.go
  cmd/edit/addon/cmd.go
  cmd/edit/cluster/cmd.go
  cmd/edit/ingress/cmd.go
  cmd/edit/machinepool/cmd.go
  cmd/grant/user/cmd.go
  cmd/hibernate/cluster/cmd.go
  cmd/install/addon/cmd.go
  cmd/list/addon/cmd.go
  cmd/list/gates/cmd.go
  cmd/list/idp/cmd.go
  cmd/list/ingress/cmd.go
  cmd/list/machinepool/cmd.go
  cmd/list/upgrade/cmd.go
  cmd/list/user/cmd.go
  cmd/logs/install/cmd.go
  cmd/logs/uninstall/cmd.go
  cmd/resume/cluster/cmd.go
  cmd/revoke/user/cmd.go
  cmd/uninstall/addon/cmd.go
  cmd/upgrade/cluster/cmd.go
  cmd/upgrade/operatorroles/cmd.go
  pkg/rosa/runtime.go
Labels: approved, lgtm

#766 Update ocm-sdk-go to v.0.1.275
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/reserved_resource_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/reserved_resource_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/reserved_resource_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/resource_review_request_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/resource_review_request_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/resource_review_request_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/subscription_status_list_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/subscription_status_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/machine_pool_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/machine_pool_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/machine_pool_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm

#767 Refactor function for more general use
  cmd/create/cluster/cmd.go
  pkg/aws/client.go
  pkg/aws/helpers.go
Labels: approved, lgtm

#765 Select a single subnet for a single AZ machine pool - BYOVPC clusters
  cmd/create/machinepool/cmd.go
  pkg/aws/client.go
Labels: approved, lgtm
