Repository openshift/rosa, pull requests merged in 2022-08, with the labels that each got.

#787 Refactored ROSA to create operator policies when running cluster creation
  cmd/create/accountroles/cmd.go
  cmd/create/operatorroles/cmd.go
Labels: approved, lgtm, ok-to-test

#805 Release v1.2.6
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm

#806 support for path in iam roles and policies
  cmd/create/accountroles/cmd.go
  cmd/create/cluster/cmd.go
  cmd/create/ocmrole/cmd.go
  cmd/create/operatorroles/cmd.go
  cmd/create/service/cmd.go
  cmd/create/userrole/cmd.go
  cmd/dlt/ocmrole/cmd.go
  cmd/dlt/userrole/cmd.go
  cmd/install/addon/cmd.go
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/operatorroles/cmd.go
  pkg/aws/client.go
  pkg/aws/helpers.go
  pkg/aws/policies.go
  pkg/aws/sts.go
  pkg/ocm/clusters.go
Labels: approved, lgtm

#802 fix - Google IDP doesn't work when created with ROSA CLI
  cmd/create/idp/google.go
  go.mod
  go.sum
  vendor/github.com/dchest/validator/.travis.yml
  vendor/github.com/dchest/validator/LICENSE
  vendor/github.com/dchest/validator/README.md
  vendor/github.com/dchest/validator/domain.go
  vendor/github.com/dchest/validator/email.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#807 Create cluster - use a GET request to describe cluster details
  cmd/create/cluster/cmd.go
  pkg/ocm/clusters.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#808 Refactor `GetCluster` function
  go.mod
  pkg/helper/helpers.go
  pkg/ocm/clusters.go
  vendor/modules.txt
Labels: approved, lgtm

#809 add arn path to ocm and user role
  cmd/create/accountroles/cmd.go
  cmd/create/ocmrole/cmd.go
  cmd/create/operatorroles/cmd.go
  cmd/create/service/cmd.go
  cmd/create/userrole/cmd.go
  cmd/install/addon/cmd.go
  cmd/upgrade/operatorroles/cmd.go
  pkg/aws/helpers.go
  pkg/aws/policies.go
Labels: approved, lgtm

#810 [SDA-6439] Add red-hat-managed tag to roles and policies
  cmd/create/accountroles/cmd.go
  cmd/create/ocmrole/cmd.go
  cmd/create/operatorroles/cmd.go
  cmd/create/userrole/cmd.go
  cmd/upgrade/accountroles/cmd.go
  pkg/aws/sts.go
  pkg/aws/tags/tags.go
Labels: approved, lgtm

#812 Adding an info message after `rosa delete admin`
  cmd/dlt/admin/cmd.go
Labels: approved, lgtm, ok-to-test

#811 properly handle "" no_proxy option in interactive mode
  cmd/edit/cluster/cmd.go
Labels: approved, needs-ok-to-test, lgtm

#794 add samira to maintainers
  OWNERS
Labels: approved, lgtm

#819 missing '--operator-roles-path' in 'To create this cluster again...'
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#814 compare arn path for existing policy/role
  pkg/aws/policies.go
Labels: approved, lgtm

#701 cluster: Allow using local AWS credentials
  cmd/create/cluster/cmd.go
  pkg/aws/client.go
  pkg/ocm/clusters.go
  pkg/properties/properties.go
Labels: approved, lgtm

#818 Only display supported machine types by region
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/cmd.go
  pkg/ocm/machines.go
Labels: approved, lgtm

#821 policies: Ensure policy version succeeds
  pkg/aws/policies.go
Labels: approved, lgtm

#820 [SDA-6610] account-role and operator-role policies are now deleted when roles are
  cmd/dlt/accountroles/cmd.go
  cmd/dlt/operatorrole/cmd.go
  pkg/aws/policies.go
Labels: approved, lgtm

#822 ocm: Add aliases for local development
  pkg/aws/helpers.go
  pkg/ocm/config.go
Labels: approved, lgtm
