Repository openshift/rosa, pull requests merged in 2022-07, with the labels that each got.

#771 Create cluster - detect multi-AZ cluster
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#770 Fix error message - create non-BYOVPC - select availability zone
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#772 Fix bug - create a cluster with an invalid number of subnets
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#774 Fix bug - fetch the subnets from the cluster region
  cmd/create/machinepool/cmd.go
Labels: approved, lgtm

#773 Create a single AZ machine pool implicitly by providing a subnet
  cmd/create/machinepool/cmd.go
Labels: approved, lgtm

#775 List machine pools - add a subnets column
  cmd/list/machinepool/cmd.go
Labels: approved, lgtm

#777 Fix bug - create cluster - validate subnets number for private link
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#780 Set `clusterKey` properly to support `r.FetchCluster`
  cmd/list/addon/cmd.go
Labels: approved, lgtm

#781 setting useVPCExist to true when subnet ids are provided
  cmd/create/cluster/cmd.go
Labels: approved, lgtm, ok-to-test

#769 Having the option to remove or add a new cluster-admin in rosa cli
  cmd/create/admin/cmd.go
  cmd/create/idp/cmd.go
  cmd/dlt/admin/cmd.go
Labels: approved, lgtm, ok-to-test

#776 Create cluster - validate subnets count interactively
  cmd/create/cluster/cmd.go
  pkg/aws/helpers.go
  pkg/interactive/validation.go
Labels: approved, lgtm

#745 accept major minor version for cluster upgrade
  cmd/upgrade/cluster/cmd.go
  pkg/ocm/versions.go
Labels: approved, lgtm

#783 removing htpasswd idp even if there are no users in this idp
  pkg/ocm/idps.go
Labels: approved, needs-ok-to-test, lgtm

#784 ROSA release 1.2.4
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm

#785 Add oriAdler to OWNERS in order to tag a ROSA release
  OWNERS
Labels: approved, lgtm

#786 Fix typo in error message when looking up account role prefix
  pkg/aws/policies.go
Labels: approved, lgtm

#790 fix for - Not able to remove or add a new cluster-admin in rosa cli
  cmd/create/idp/htpasswd.go
  cmd/dlt/admin/cmd.go
  cmd/grant/user/cmd.go
  cmd/list/user/cmd.go
  cmd/revoke/user/cmd.go
  pkg/ocm/idps.go
Labels: approved, lgtm, ok-to-test

#789 Create cluster - validate availability zones count interactively
  cmd/create/cluster/cmd.go
  pkg/aws/helpers.go
  pkg/interactive/validation.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#793 Release v1.2.5
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm

#792 add fake cluster parameter to create services
  cmd/create/service/cmd.go
  pkg/ocm/managedservice.go
Labels: approved, lgtm

#795 fedramp: Update rosa-authenticator configuration
  pkg/fedramp/config.go
Labels: approved, lgtm

#778 Redact token output
  cmd/login/cmd.go
  pkg/ocm/clusters.go
Labels: approved, lgtm

#797 SDA-5813 Remove DisplayName from cluster
  cmd/describe/cluster/cmd.go
  pkg/ocm/clusters.go
Labels: approved, lgtm

#800 Create cluster - for single AZ, only allow to select one AZ
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#798 Switch from `github.com/pkg/errors` to stdlib
  cmd/upgrade/cluster/cmd.go
  go.mod
  pkg/aws/sts.go
  pkg/ocm/managedservice.go
  vendor/modules.txt
Labels: approved, lgtm

#801 SDA-5813: Updated SDK version and ran go mod vendor
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/account_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/account_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/account_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/registry_credential_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/registry_credential_resource_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/add_on_parameter_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/add_on_parameter_option_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/add_on_parameter_option_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/add_on_parameter_option_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/add_on_parameter_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/add_on_parameter_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/limited_support_reason_template_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/provision_shard_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/provision_shard_resource_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/provision_shard_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/provision_shards_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/provision_shards_resource_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm
