Repository openshift/rosa, pull requests merged in 2023-05, with the labels that each got.

#1214 Release v1.2.18
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm

#1198 SDA-8914 | fix: rosa upgrade hcp account roles - handle edge cases
  cmd/create/accountroles/cmd.go
  cmd/upgrade/accountroles/cmd.go
Labels: approved, lgtm

#1215 SDA-8636 | fix: OIDC provider behavior when calling internally from oidc config flow
  cmd/create/oidcprovider/cmd.go
Labels: approved, lgtm

#1206 SDA-8382| Fix: skip replicas when passing tuning configs to edit
  cmd/edit/machinepool/nodepool.go
Labels: approved, lgtm

#1204 SDA-8716 | Fix: provide warning message when no OIDC config is found
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1218 SDA-9046 | feat: adding billing account attribute to describe cluster command
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm

#1176 SDA-8770 | fix: accept only official default prefix when selecting default prefix
  cmd/create/cluster/cmd.go
  pkg/interactive/helper.go
Labels: approved, lgtm

#1213 SDA-8600 | feat: add interactive option for delete account roles
  cmd/dlt/accountroles/accountroles_suite_test.go
  cmd/dlt/accountroles/cmd.go
  cmd/dlt/accountroles/cmd_test.go
Labels: approved, lgtm

#1216 SDA-9041 | feat: defaults to managed oidc configs
  cmd/create/oidcconfig/cmd.go
Labels: approved, lgtm

#1220 SDA-9051 | fix: Upgrade account roles - fix error message
  cmd/upgrade/accountroles/cmd.go
Labels: approved, lgtm

#1209 SDA-8689 Adjust default replicas on hosted clusters
  cmd/create/cluster/cmd.go
  cmd/edit/machinepool/nodepool.go
Labels: approved, lgtm

#1219 SDA-9048 | feat: add messages and checks to ensure a better flow UX wise
  cmd/create/accountroles/cmd.go
  cmd/create/cluster/cmd.go
  cmd/create/oidcconfig/cmd.go
  cmd/create/oidcprovider/cmd.go
  cmd/create/operatorroles/by_clusterkey.go
  cmd/create/operatorroles/by_prefix.go
  cmd/verify/rosa/cmd.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#1221 Release v1.2.19
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm

#1222 fix: aws path differs from ocm expected path
  pkg/ocm/helpers.go
Labels: approved

#1223 Release v1.2.20
  CHANGES.adoc
  pkg/info/info.go
Labels: approved

#1226 Allow editing ingress privacy for private hypershift cluster
  cmd/edit/ingress/cmd.go
Labels: approved, lgtm

#1229 SDA-8718 Update rosa create message for hosted cluster
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1230 fix : update action to run on each commit in a pull request
  .github/workflows/check-commit-format.yml
Labels: approved, lgtm

#1233 OCM-186 | fix: only print success message if no errors occur
  cmd/dlt/operatorrole/cmd.go
Labels: approved, lgtm

#1234 [SDA-9078] fix: only ask mode if flag is not changed
  cmd/create/oidcprovider/cmd.go
  cmd/dlt/oidcprovider/cmd.go
Labels: approved, lgtm

#1231 SDA-8963 Improve machine type not found message
  cmd/create/machinepool/machinepool.go
  cmd/create/machinepool/nodepool.go
  cmd/list/instancetypes/cmd.go
  pkg/ocm/machines.go
Labels: approved, lgtm

#1235 Release v1.2.21
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm

#1237 SDA-9086 | fix: check error when retrieving operator-roles
  cmd/dlt/operatorrole/cmd.go
Labels: approved, lgtm

#1225 SDA-8538 | fix: create hcp account roles in interactive mode
  cmd/create/accountroles/cmd.go
Labels: approved, lgtm

#1239 remove os.Exit in cluster creation cmd
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1242 SDA-9105 | feat: asks for OIDC Configuration kind in interactive
  cmd/create/oidcconfig/cmd.go
Labels: approved, lgtm

#1241 OCM-263 | fix: behavior when creating operator-roles
  cmd/create/operatorroles/by_clusterkey.go
  cmd/create/operatorroles/by_prefix.go
  pkg/helper/helpers.go
Labels: approved, lgtm

#1240 SDA-9087 | fix: validate installer role arn after selection
  cmd/create/oidcconfig/cmd.go
  pkg/aws/client.go
  pkg/aws/policies.go
Labels: approved, lgtm

#1251 SDA-9122 | fix: only validate installer arn if role name is not empty
  cmd/create/oidcconfig/cmd.go
Labels: approved, lgtm

#1245 OCM-264 | fix: Properly checks the path when validating trusted relationship
  cmd/create/operatorroles/by_clusterkey.go
  cmd/create/operatorroles/by_prefix.go
  cmd/create/operatorroles/cmd.go
  pkg/ocm/clusters.go
  pkg/ocm/clusters_test.go
  pkg/ocm/helpers.go
  pkg/ocm/helpers_test.go
Labels: approved, lgtm

#1247 fix: remidiating gramatical typo in hibernation help messages
  cmd/hibernate/cmd.go
  cmd/resume/cmd.go
Labels: approved, lgtm

#1252 OCM-302 | fix: if no such entity move operator roles creation forward
  cmd/create/operatorroles/by_prefix.go
Labels: approved, lgtm

#1253 OCM-301 | fix: goes through both operator roles type when deleting by prefix
  cmd/dlt/operatorrole/cmd.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#1246 SDA-9126 | feat: remove hypershift capability check in list regions
  cmd/list/region/cmd.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#1256 OCM-285 | feat: unhide hcp params
  cmd/create/accountroles/cmd.go
  cmd/create/cluster/cmd.go
  cmd/dlt/accountroles/cmd.go
  cmd/list/region/cmd.go
  cmd/upgrade/accountroles/cmd.go
Labels: approved, lgtm

#1258 OCM-756 | feat: removed prompt for subscription billing account
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1264 Release v1.2.22
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm

#1266 Create cluster - fix error messages
  cmd/create/cluster/cmd.go
  cmd/upgrade/accountroles/cmd.go
Labels: approved, lgtm

#1267 OCM-785 | docs: Add instructions to get rosa binary from latest
  README.md
Labels: approved, lgtm

#1269 Revert "OCM-140 | chore : reverting IMDSv2"
  cmd/create/cluster/cmd.go
  pkg/ocm/clusters.go
  pkg/ocm/helpers.go
  pkg/ocm/helpers_test.go
  pkg/ocm/versions.go
  pkg/ocm/versions_test.go
Labels: approved, lgtm

#1268 add Technology Preview to --help output for hosted-cp
  cmd/create/accountroles/cmd.go
  cmd/create/cluster/cmd.go
  cmd/upgrade/accountroles/cmd.go
Labels: approved, lgtm

#1244 sda-6257: handle errors when retrieve versiongates
  pkg/ocm/upgrades.go
Labels: approved, lgtm, jira/valid-reference

#1271 OCM-785 | Add specific commit binary image to README.md
  README.md
Labels: approved, lgtm

#1275 SDA-4652 | feat: add list oidc providers command
  cmd/list/cmd.go
  cmd/list/oidcprovider/cmd.go
  pkg/aws/client.go
  pkg/aws/sts.go
  pkg/output/output.go
Labels: approved, lgtm

#1276 OCM-1013 | fix: remove dial issuer url when creating operator roles by prefix
  cmd/create/operatorroles/by_prefix.go
  pkg/helper/helpers.go
Labels: approved, lgtm

#1277 SDA-8838 | fix: STS default warning does not show for hcp
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1282 OCM-1361 | fix: Add flag to bypass confirmation on edit cluster
  cmd/edit/cluster/cmd.go
Labels: approved, lgtm

#1284 OCM-1410 | fix: correct error message when 'rosa link user-role' with account-id under diff org
  cmd/link/userrole/cmd.go
  cmd/unlink/userrole/cmd.go
Labels: approved, lgtm
