Repository openshift/rosa, pull requests merged in 2023-10, with the labels that each got.

#1523 OCM-3522 | fix: improve create operator roles error message
  cmd/create/operatorroles/common_utils.go
Labels: approved, lgtm

#1524 OCM-3833 | fix: only show interactive SGs if there are any
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/machinepool.go
  cmd/create/oidcconfig/cmd.go
  cmd/create/oidcprovider/cmd.go
  cmd/create/operatorroles/by_prefix.go
  cmd/dlt/oidcconfig/cmd.go
  cmd/dlt/oidcprovider/cmd.go
  cmd/register/oidcconfig/cmd.go
  pkg/interactive/oidc/oidc.go
  pkg/interactive/roles/roles.go
  pkg/interactive/securitygroups/security_groups.go
Labels: approved, lgtm

#1526 OCM-4026 | chore: bump version for release 1.2.28
  pkg/info/info.go
Labels: approved, lgtm

#1525 OCM-3873 | fix: change references to default machine pool to worker machine pool
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1528 OCM-4024 | fix: fedramp admin stage urls
  pkg/fedramp/config.go
Labels: approved, lgtm

#1527 OCM-3833 | fix: only go interactive on non hcp
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/machinepool.go
Labels: approved, lgtm

#1529 OCM-1448 | fix: improve subnet not found error message
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1505 OCM-3366 | fix: CLI options dependency
  cmd/create/autoscaler/cmd.go
  cmd/create/cluster/cmd.go
  cmd/edit/autoscaler/cmd.go
  go.mod
  go.sum
  pkg/clusterautoscaler/flags.go
  vendor/github.com/cpuguy83/go-md2man/v2/md2man/roff.go
  vendor/github.com/inconshreveable/mousetrap/LICENSE
  vendor/github.com/inconshreveable/mousetrap/trap_others.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows_1.4.go
  vendor/github.com/russross/blackfriday/v2/README.md
  vendor/github.com/russross/blackfriday/v2/block.go
  vendor/github.com/russross/blackfriday/v2/doc.go
  vendor/github.com/russross/blackfriday/v2/entities.go
  vendor/github.com/russross/blackfriday/v2/esc.go
  vendor/github.com/russross/blackfriday/v2/html.go
  vendor/github.com/russross/blackfriday/v2/inline.go
  vendor/github.com/russross/blackfriday/v2/node.go
  vendor/github.com/shurcooL/sanitized_anchor_name/.travis.yml
  vendor/github.com/shurcooL/sanitized_anchor_name/LICENSE
  vendor/github.com/shurcooL/sanitized_anchor_name/README.md
  vendor/github.com/shurcooL/sanitized_anchor_name/main.go
  vendor/github.com/spf13/cobra/.golangci.yml
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/CHANGELOG.md
  vendor/github.com/spf13/cobra/MAINTAINERS
  vendor/github.com/spf13/cobra/Makefile
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/active_help.go
  vendor/github.com/spf13/cobra/active_help.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/bash_completionsV2.go
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_notwin.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/completions.go
  vendor/github.com/spf13/cobra/doc/README.md
  vendor/github.com/spf13/cobra/doc/man_docs.go
  vendor/github.com/spf13/cobra/doc/md_docs.go
  vendor/github.com/spf13/cobra/doc/md_docs.md
  vendor/github.com/spf13/cobra/doc/rest_docs.go
  vendor/github.com/spf13/cobra/doc/rest_docs.md
  vendor/github.com/spf13/cobra/doc/util.go
  vendor/github.com/spf13/cobra/doc/yaml_docs.go
  vendor/github.com/spf13/cobra/doc/yaml_docs.md
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/flag_groups.go
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.go
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/user_guide.md
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/modules.txt
Labels: approved, lgtm

#1534 OCM-4140 | fix: use output print slice instead of helper
  cmd/describe/machinepool/machinepool.go
  cmd/list/machinepool/machinepool.go
Labels: approved, lgtm

#1532 OCM-4128 | fix: validate sgs flag out of byo vpc
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/machinepool.go
Labels: approved, lgtm

#1531 OCM-3526 | feat: create operator roles for shared VPC with cluster key
  cmd/create/operatorroles/by_clusterkey.go
  cmd/create/operatorroles/cmd.go
Labels: approved, lgtm

#1522 OCM-3831 | fix: 'rosa describe admin' cannot find 'cluster-admin' htpasswd idp and user (updated)
  cmd/create/admin/cmd.go
  cmd/create/cluster/cmd.go
  cmd/create/idp/htpasswd.go
Labels: approved, lgtm

#1537 OCM-3366 | fix: force --enable-autoscaling flag when autoscaling flags are used
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1536 OCM-4123 | fix: Remove unnecessary warning messages about Red Hat owned subnets when user explicitly specifies subnets to use
  cmd/create/cluster/cmd.go
  cmd/create/service/cmd.go
  pkg/aws/client.go
  pkg/aws/client_test.go
Labels: approved, lgtm

#1538 OCM-4134 | fix: better help message
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/cmd.go
Labels: approved, lgtm

#1535 OCM-3884 | fix: validate version and HCP default ingress attributes
  cmd/create/cluster/cmd.go
  pkg/ingress/flags.go
Labels: approved, lgtm

#1543 OCM-4257 | fix: doesn't check /labels for HCP
  cmd/edit/ingress/cmd.go
Labels: approved, lgtm

#1521 OCM-2864 | feat: Added default push request template
  .github/merge_request_template/Default.md
Labels: approved, needs-ok-to-test, lgtm

#1540 OCM-3663 | feat: AWS billing support
  cmd/create/cluster/cmd.go
  cmd/create/cluster/cmd_test.go
  pkg/helper/helpers.go
  pkg/ocm/billing.go
  pkg/ocm/billing_test.go
Labels: approved, lgtm

#1542 OCM-3911 | feat: use HCP specific endpoints for versions and upgrades
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/nodepool.go
  cmd/describe/machinepool/cmd_test.go
  cmd/describe/upgrade/cmd_test.go
  cmd/list/upgrade/cmd.go
  cmd/list/upgrade/cmd_test.go
  cmd/list/version/cmd.go
  cmd/upgrade/cluster/cmd.go
  cmd/upgrade/cluster/cmd_test.go
  cmd/upgrade/machinepool/cmd.go
  cmd/upgrade/machinepool/cmd_test.go
  pkg/helper/versions/helpers.go
  pkg/helper/versions/helpers_test.go
  pkg/ocm/helpers.go
  pkg/ocm/versions.go
  pkg/test/helpers.go
Labels: approved, lgtm

#1550 OCM-4336 | feat: disable edit machinepool --version command
  cmd/edit/machinepool/cmd.go
  cmd/edit/machinepool/nodepool.go
Labels: approved, lgtm

#1547 OCM-2373 | feat: Moved associated to GetRole functions to common folder
  cmd/create/accountroles/creators.go
  cmd/create/machinepool/machinepool.go
  cmd/create/ocmrole/cmd.go
  cmd/create/operatorroles/by_clusterkey.go
  cmd/create/operatorroles/by_prefix.go
  cmd/create/operatorroles/common_utils.go
  cmd/edit/autoscaler/cmd.go
  cmd/install/addon/cmd.go
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/cluster/cmd.go
  cmd/upgrade/roles/cmd.go
  pkg/aws/client.go
  pkg/aws/client_test.go
  pkg/aws/commandbuilder/helper/roles/roles.go
  pkg/aws/helpers.go
  pkg/aws/policies.go
  pkg/aws/sts.go
  pkg/aws/tags/tags.go
  pkg/aws/tags/utils.go
  pkg/helper/roles/helpers.go
  pkg/interactive/interactive.go
  pkg/ocm/helpers.go
  pkg/ocm/helpers_test.go
  pkg/ocm/validators.go
  vendor/github.com/openshift-online/ocm-common/pkg/aws/validations/iam_helpers.go
  vendor/github.com/openshift-online/ocm-common/pkg/aws/validations/tags.go
  vendor/github.com/openshift-online/ocm-common/pkg/consts.go
  vendor/github.com/openshift-online/ocm-common/pkg/ocm/validations/helpers.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#1548 OCM-4302 | fix: hide billingaccount for classic
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1549 OCM-3604 | feat: support best-effort mode in cluster deletion
  cmd/dlt/cluster/cmd.go
  go.mod
  go.sum
  pkg/ocm/clusters.go
  vendor/github.com/openshift-online/ocm-sdk-go/.gitignore
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/feature_review_request_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/feature_review_request_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/feature_review_request_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/authorizations/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/environment_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/environment_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/environment_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/version_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/version_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/version_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/servicelogs/v1/log_entry_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/servicelogs/v1/log_entry_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/servicelogs/v1/log_entry_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/servicelogs/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm

#1552 OCM-3492 | Fix: log should be aligned to left
  cmd/describe/upgrade/cmd.go
  cmd/describe/upgrade/cmd_test.go
Labels: approved, lgtm

#1555 OCM-4433| feat: Fixing cluster creation bug
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-common/pkg/resource/validations/kms_arn_regex_validation.go
  vendor/modules.txt
Labels: approved, needs-ok-to-test, lgtm

#1558 OCM-3492 | fix: Classic upgrade should align left
  cmd/describe/upgrade/cmd.go
  cmd/describe/upgrade/cmd_test.go
Labels: approved, lgtm

#1563 OCM-4571 | fix: Validate upgrade versions from prerelease scenarios
  pkg/ocm/versions.go
  pkg/ocm/versions_test.go
Labels: approved, lgtm

#1566 OCM-4506 | fix: adjust min format so it allows nightlies
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/machinepool.go
  pkg/helper/versions/helpers.go
  pkg/helper/versions/helpers_test.go
  pkg/ocm/versions.go
Labels: approved, lgtm

#1567 OCM-4571 | fix: Fix CheckAndParseVersion when coming from preRelease
  cmd/upgrade/cluster/cmd.go
  pkg/ocm/versions.go
  pkg/ocm/versions_test.go
Labels: approved, lgtm

#1562 OCM-4513 | fix: updating vendor
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-common/pkg/resource/validations/kms_arn_regex_validation.go
  vendor/modules.txt
Labels: approved, needs-ok-to-test, lgtm
