Repository openshift/rosa, pull requests merged in 2023-01, with the labels that each got.

#991 Fix bug create account roles with existing policies
  cmd/create/accountroles/cmd.go
  cmd/create/ocmrole/cmd.go
  cmd/create/operatorroles/cmd.go
  cmd/create/userrole/cmd.go
  cmd/install/addon/cmd.go
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/operatorroles/cmd.go
  cmd/upgrade/roles/cmd.go
  pkg/aws/helpers.go
  pkg/aws/permissions.go
  pkg/helper/roles/helpers.go
Labels: approved, lgtm

#853 [SDA-4764] Hide region arg in account roles commands
  cmd/create/cmd.go
  cmd/dlt/cmd.go
  cmd/list/cmd.go
  cmd/upgrade/cmd.go
  pkg/arguments/arguments.go
Labels: approved, lgtm

#994 Refactor sort strings helper
  cmd/initialize/cmd.go
  pkg/aws/helpers.go
  pkg/helper/helpers.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#993 Create operator role with existing policies
  cmd/create/operatorroles/cmd.go
  pkg/aws/client.go
  pkg/aws/policies.go
  pkg/helper/helpers.go
Labels: approved, lgtm

#995 [SDA-4764] Hide region from other globally available commands
  cmd/create/cmd.go
  cmd/dlt/cmd.go
  cmd/list/cmd.go
  cmd/upgrade/cmd.go
  pkg/arguments/arguments.go
Labels: approved, lgtm

#996 SDA-7521 Support instanceType selection on NodePools
  cmd/create/machinepool/nodepool.go
Labels: approved, lgtm

#999 [SDA-7662] Display Tags question in interactive mode
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1000 Revert "[SDA-7662] Display Tags question in interactive mode"
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1002 [SDA-7662] Made it so the Tags question appears always in interactive mode
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1001 Upgrade account roles with managed policies
  cmd/create/operatorroles/cmd.go
  cmd/upgrade/accountroles/cmd.go
  pkg/aws/client.go
  pkg/aws/policies.go
Labels: approved, lgtm

#1003 Add the default-mp-labels flag to cluster create command on interactive
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1005 Fix OAuth callback URL logic for HyperShift clusters
  cmd/create/cluster/cmd_test.go
  cmd/create/idp/github.go
  cmd/create/idp/gitlab.go
  cmd/create/idp/google.go
  cmd/create/idp/openid.go
  cmd/list/idp/cmd.go
  pkg/ocm/idps.go
  pkg/ocm/idps_test.go
Labels: approved, lgtm, ok-to-test

#998 [SDA-7663] Check current ingress values to see if there are no changes
  cmd/edit/ingress/cmd.go
Labels: approved, lgtm

#1008 Upgrade operator roles with managed policies
  cmd/create/operatorroles/cmd.go
  cmd/upgrade/operatorroles/cmd.go
  cmd/upgrade/roles/cmd.go
  pkg/aws/client.go
  pkg/aws/commandbuilder/helper/roles/roles.go
  pkg/aws/helpers.go
  pkg/aws/policies.go
  pkg/helper/roles/helpers.go
Labels: approved, lgtm

#1006 [SDA-6753] Now updating stsBuilder.AutoMode properly
  pkg/ocm/clusters.go
Labels: approved, lgtm

#1011 Fix tags passing in cluster creation interactive mode
  cmd/create/cluster/cmd.go
Labels: approved, lgtm, ok-to-test

#1012 Upgrade roles command - handle managed policies
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/operatorroles/cmd.go
  cmd/upgrade/roles/cmd.go
  pkg/helper/roles/helpers.go
Labels: approved, lgtm

#1013 [SDA-7741] Machine pool label validation
  cmd/create/machinepool/machinepool.go
Labels: approved, lgtm

#976 fix: Incorrect OIDC Provider Sometimes Targeted for Deletion
  cmd/dlt/oidcprovider/cmd.go
Labels: approved, lgtm, ok-to-test

#1016 Delete correct operator roles and support hypershift
  cmd/dlt/operatorrole/cmd.go
Labels: approved, lgtm

#1017 [SDA-7758] Accept pre release version during upgrade
  pkg/ocm/versions.go
Labels: approved, lgtm

#1021 Ensure console URL is available before offering it to the user
  cmd/create/idp/cmd.go
Labels: approved, lgtm, ok-to-test

#1014 SDCICD-893: cmd/create/machinepool: support output flag
  cmd/create/machinepool/cmd.go
  cmd/create/machinepool/machinepool.go
  cmd/create/machinepool/nodepool.go
  pkg/output/output.go
Labels: approved, lgtm, tide/merge-method-squash

#1023 [SDA-7784] Tagged current version on policy is not necessarily compatible
  pkg/aws/policies.go
Labels: approved, lgtm

#1027 Release v1.2.12
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm

#1025 Skip missing acc roles during upgrade
  cmd/upgrade/roles/cmd.go
  pkg/aws/client.go
  pkg/aws/policies.go
Labels: approved, lgtm

#1019 SDA-7767 Let user define machinepool name on hosted cluster
  cmd/create/machinepool/nodepool.go
  cmd/list/machinepool/nodepool.go
Labels: approved, lgtm

#1020 NodePools status in ROSA
  cmd/describe/cluster/cmd.go
  cmd/list/machinepool/nodepool.go
Labels: approved, lgtm

#1026 Skip region check if we use shard pinning
  cmd/create/cluster/cmd.go
  pkg/ocm/regions.go
  pkg/properties/properties.go
Labels: approved, needs-ok-to-test, lgtm

#1032 Fix managed policies cluster upgrade path
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/operatorroles/cmd.go
  cmd/upgrade/roles/cmd.go
Labels: approved, lgtm

#1015 [SDA-7756] create config with secrets manager
  Makefile
  cmd/create/oidcconfig/cmd.go
  pkg/aws/client.go
  pkg/aws/client_test.go
  pkg/aws/commandbuilder/commandbuilder.go
  pkg/aws/mocks/secretsmanagerapi.go
  vendor/github.com/aws/aws-sdk-go/service/secretsmanager/api.go
  vendor/github.com/aws/aws-sdk-go/service/secretsmanager/doc.go
  vendor/github.com/aws/aws-sdk-go/service/secretsmanager/errors.go
  vendor/github.com/aws/aws-sdk-go/service/secretsmanager/secretsmanageriface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/secretsmanager/service.go
  vendor/modules.txt
Labels: approved, lgtm

#1018 [SDA-7757] byo OIDC secret arn support
  cmd/create/cluster/cmd.go
  cmd/create/oidcprovider/cmd.go
  go.mod
  go.sum
  pkg/aws/idps.go
  pkg/helper/helpers.go
  pkg/ocm/clusters.go
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/sts_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/sts_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/sts_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm, tide/merge-method-squash

#1033 Delete roles with managed policies
  cmd/dlt/accountroles/cmd.go
  cmd/dlt/operatorrole/cmd.go
  pkg/aws/client.go
  pkg/aws/policies.go
Labels: approved, lgtm

#1034 Create OCM role with managed policies
  cmd/create/ocmrole/cmd.go
  pkg/aws/tags/tags.go
Labels: approved, lgtm

#1035 Delete OCM role with managed policies
  cmd/dlt/ocmrole/cmd.go
  pkg/aws/client.go
  pkg/aws/sts.go
Labels: approved, lgtm

#1036 Upgrade to Go 1.19
  .golangci.yml
  go.mod
Labels: approved, needs-ok-to-test, lgtm, do-not-merge/hold

#1037 Release v1.2.13
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm

#1029 [SDA-7898] Add force param to forcefully create policies
  cmd/create/accountroles/cmd.go
  cmd/create/operatorroles/cmd.go
  pkg/aws/client.go
  pkg/aws/policies.go
Labels: approved, lgtm

#1028 Permissions boundary shouldn't be asked if supposed to skip interactive
  cmd/create/operatorroles/cmd.go
Labels: approved, lgtm

#1041 [SDA-7879] Incorrect flags in message and hidden for upgrade roles
  cmd/upgrade/cluster/cmd.go
  cmd/upgrade/roles/cmd.go
Labels: approved, lgtm

#1040 Edit machinepool min replicas
  cmd/edit/machinepool/machinepool.go
Labels: approved, lgtm

#1043 IDP related minor cleanup
  cmd/create/admin/cmd.go
  cmd/create/idp/cmd.go
  cmd/create/idp/github.go
  cmd/create/idp/gitlab.go
  cmd/create/idp/google.go
  cmd/create/idp/htpasswd.go
  cmd/create/idp/ldap.go
  cmd/create/idp/openid.go
  pkg/ocm/idps.go
Labels: approved, lgtm

#1042 Add port for OAuth Callback URI in OpenID
  cmd/create/idp/cmd.go
  cmd/create/idp/github.go
  cmd/create/idp/gitlab.go
  cmd/create/idp/google.go
  cmd/create/idp/openid.go
  pkg/ocm/idps.go
  pkg/ocm/idps_test.go
Labels: approved, lgtm

#1045 Create cluster - validate account roles have managed policies attached
  cmd/create/cluster/cmd.go
  pkg/helper/roles/helpers.go
Labels: approved, lgtm
