Repository openshift/rosa, pull requests merged in 2023-06, with the labels that each got.

#1286 exit link userrole cmd when errors
  cmd/link/userrole/cmd.go
Labels: approved, lgtm

#1274 Add the ability to list all clusters
  cmd/list/cluster/cmd.go
  pkg/ocm/clusters.go
Labels: approved, needs-ok-to-test, lgtm

#1278 OCM-1179 | fix: act on output flag for list service command
  cmd/list/service/cmd.go
  pkg/output/output.go
Labels: approved, lgtm

#1280 OCM-2103 | feat: add 'in use' column list oidc providers
  cmd/list/oidcprovider/cmd.go
  pkg/aws/helpers.go
  pkg/aws/policies.go
Labels: approved, lgtm

#1289 OCM-953 | feat: add automatic upgrades for hypershift control plane
  cmd/upgrade/cluster/cmd.go
  cmd/upgrade/cluster/cmd_test.go
  cmd/upgrade/cluster/upgrade_suite_test.go
  go.mod
  go.sum
  pkg/ocm/client.go
  vendor/github.com/robfig/cron/v3/.gitignore
  vendor/github.com/robfig/cron/v3/.travis.yml
  vendor/github.com/robfig/cron/v3/LICENSE
  vendor/github.com/robfig/cron/v3/README.md
  vendor/github.com/robfig/cron/v3/chain.go
  vendor/github.com/robfig/cron/v3/constantdelay.go
  vendor/github.com/robfig/cron/v3/cron.go
  vendor/github.com/robfig/cron/v3/doc.go
  vendor/github.com/robfig/cron/v3/logger.go
  vendor/github.com/robfig/cron/v3/option.go
  vendor/github.com/robfig/cron/v3/parser.go
  vendor/github.com/robfig/cron/v3/spec.go
  vendor/modules.txt
Labels: approved, lgtm

#1294 OCM-2241| fix: Ensure all input users are added to the user list
  cmd/create/idp/htpasswd.go
Labels: approved, lgtm

#1291 OCM-2157 | fix: ensure policy when calling delete policy versions was not checking for errors
  pkg/aws/policies.go
Labels: approved, lgtm

#1298 OCM-2274 | Fix: skip version check for automated upgrade
  cmd/describe/upgrade/cmd.go
  cmd/upgrade/cluster/cmd.go
Labels: approved, lgtm

#1109 Create Hypershift dedicated account roles
  cmd/create/accountroles/cmd.go
  cmd/create/accountroles/creators.go
  cmd/dlt/accountroles/cmd.go
Labels: approved, lgtm

#1296 [OCM-942] ROSA CLI support for configurable ingress load balancer type
  cmd/create/ingress/cmd.go
  cmd/edit/ingress/cmd.go
  cmd/list/ingress/cmd.go
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_credentials_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_credentials_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_credentials_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/ingress_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/ingress_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/ingress_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/load_balancer_flavor_list_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/load_balancer_flavor_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/ssh_credentials_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/ssh_credentials_list_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/ssh_credentials_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/ssh_credentials_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm

#1299 OCM-2259 | feat: Expose `--hosted-cp` flag
  cmd/create/accountroles/cmd.go
  cmd/create/cluster/cmd.go
  cmd/dlt/accountroles/cmd.go
  cmd/upgrade/accountroles/cmd.go
Labels: approved, lgtm

#1250 OCM-300 | feat: remove environment check for managed policies
  cmd/create/accountroles/cmd.go
  cmd/create/cluster/cmd.go
  cmd/create/ocmrole/cmd.go
  cmd/create/operatorroles/by_clusterkey.go
  cmd/create/operatorroles/by_prefix.go
  cmd/dlt/accountroles/cmd.go
  cmd/dlt/operatorrole/cmd.go
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/operatorroles/cmd.go
  cmd/upgrade/roles/cmd.go
Labels: approved, lgtm

#1304 OCM-2181 | Fix: error message was misleading
  cmd/upgrade/cluster/cmd.go
Labels: approved, lgtm

#1287 fix/filter-subnets-by-cidr
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1305 OCM-955 | feat: register oidc config command
  cmd/create/oidcconfig/cmd.go
  cmd/register/cmd.go
  cmd/register/oidcconfig/cmd.go
  cmd/rosa/main.go
  pkg/constants/oidc_config.go
  pkg/helper/oidc_config/helper.go
Labels: approved, lgtm

#1309 OCM-2376 | ci : add script to run in prow job to validate commit msgs
  .github/workflows/check-commit-format.yml
  Makefile
  hack/commit-msg-verify.sh
Labels: approved, lgtm

#1308 OCM-2347: Accept path setting thru iam role check - regex
  pkg/aws/helpers.go
Labels: approved, needs-ok-to-test, lgtm, jira/valid-reference

#1312 [OCM-2347] fix: accept limited symbols in role name section of arn
  cmd/create/cluster/cmd.go
  cmd/edit/cluster/cmd.go
  pkg/aws/helpers.go
Labels: approved, needs-ok-to-test, lgtm

#1313 OCM-954 | Feat: small refactor to prepare for nodepool upgrades
  cmd/dlt/machinepool/nodepool.go
  cmd/edit/machinepool/nodepool.go
  cmd/upgrade/cluster/cmd.go
  cmd/upgrade/cluster/cmd_test.go
  pkg/interactive/upgrades.go
  pkg/ocm/controlplane_upgrades.go
  pkg/ocm/nodepools.go
  pkg/ocm/upgrades.go
Labels: approved, lgtm

#1318 OCM-2256| Fix : Remove debug msg that prints the user/password list
  cmd/create/idp/htpasswd.go
Labels: approved, lgtm

#1319 OCM-2257 | fix: Ensure only one of users or username flags is provided
  cmd/create/idp/cmd.go
  cmd/create/idp/htpasswd.go
Labels: approved, lgtm

#1321 OCM-1150 | fix: Validation for 'value' in tags when creating a non-sts cluster
  pkg/aws/helpers.go
Labels: approved, lgtm

#1325 OCM-1755 | fix: Removed unneeded log about creating cluster after creating accout-roles
  cmd/create/accountroles/cmd.go
Labels: approved, lgtm

#1326 OCM-2427 | fix: Added command in INFO message to register oidc config after creating
  cmd/create/oidcconfig/cmd.go
Labels: approved, lgtm

#1332 OCM-2440 | fix: reuse operator roles - validate compatible policies
  cmd/create/cluster/cmd.go
  cmd/create/operatorroles/by_clusterkey.go
  cmd/create/operatorroles/by_prefix.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#1335 OCM 844 | feat: Support loading users from htpasswd file
  cmd/create/idp/cmd.go
  cmd/create/idp/htpasswd.go
Labels: approved, lgtm

#1328 OCM-152 | feat: update the displayed output
  cmd/verify/network/cmd.go
Labels: approved, lgtm

#1320 OCM-2433 | feat: adds admin flag for fedramp
  cmd/login/cmd.go
  pkg/fedramp/config.go
  pkg/fedramp/flag.go
  pkg/ocm/config.go
Labels: approved, lgtm

#1336 OCM-158 | fix: enable clusteradmin if user set --cluster-admin-user arg
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1334 OCM-1295 | fix: add existence check for ocm-roles
  cmd/link/ocmrole/cmd.go
Labels: approved, lgtm

#1341 OCM-347 | fix: Align FedRAMP non-admin token url and client IDs for integration
  pkg/fedramp/config.go
Labels: approved, lgtm

#1330 OCM-2421 | fix: Made prompt for OIDC COnfig ID not happen when flag given
  cmd/dlt/oidcconfig/cmd.go
Labels: approved, lgtm

#1338 [OCM-2348] Add audit log details in rosa describe cluster
  cmd/describe/cluster/cmd.go
Labels: approved, needs-ok-to-test, lgtm
