Repository openshift/rosa, pull requests merged in 2023-09, with the labels that each got.

#1470 OCM-3313 | refactor: extract autoscaler code to new modules
  cmd/create/cluster/cmd.go
  pkg/clusterautoscaler/flags.go
  pkg/ocm/clusterautoscaler.go
  pkg/ocm/clusters.go
  pkg/ocm/validators.go
  pkg/ocm/validators_test.go
Labels: approved, lgtm

#1473 OCM-3334 | feat: allow setting GPU limitations
  cmd/create/cluster/cmd.go
  pkg/clusterautoscaler/flags.go
  pkg/ocm/clusterautoscaler.go
Labels: approved, lgtm

#1475 OCM-1294 | feat: Changed Password Validator function to use shared library
  cmd/create/cluster/cmd.go
  cmd/create/idp/htpasswd.go
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-common/pkg/idp/validations/passwordValidator.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#1472 OCM-3370 | fix: re-attach policies after detaching from operator roles
  cmd/upgrade/roles/cmd.go
Labels: approved, lgtm, ok-to-test

#1456 OCM-3381 | fix: adjust so that it doesn't show new ingress attributes when not supported
  cmd/create/cluster/cmd.go
  cmd/edit/ingress/cmd.go
  pkg/helper/versions/helpers.go
  pkg/ocm/clusters.go
  pkg/ocm/helpers.go
  pkg/ocm/versions.go
Labels: approved, lgtm

#1485 OCM-1370 | feat: Print acknowledgement in upgrade cluster when -y is passed
  cmd/upgrade/cluster/cmd.go
Labels: approved, lgtm

#1477 OCM-3535 | fix: set max-nodes-total default value to 180
  pkg/clusterautoscaler/flags.go
Labels: approved, lgtm

#1478 OCM-3574 | fix: cores range validation
  pkg/clusterautoscaler/flags.go
Labels: approved, lgtm

#1482 OCM-3313 | feat: add 'rosa edit autoscaler' command
  cmd/edit/autoscaler/cmd.go
  cmd/edit/cmd.go
  pkg/clusterautoscaler/flags.go
  pkg/interactive/interactive.go
  pkg/ocm/clusterautoscaler.go
Labels: approved, lgtm

#1468 OCM-3375 | feat: Add 'Workload Monitoring' to describe/cluster
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm

#1457 OCM-3397 Support machine pools with zero replicas on day two
  cmd/create/machinepool/nodepool.go
  cmd/edit/machinepool/nodepool.go
  pkg/helper/machinepools/helpers.go
  pkg/helper/machinepools/helpers_test.go
Labels: approved, lgtm

#1433 OCM-3280 | fix: Updated installation document
  README.md
Labels: approved, lgtm, ok-to-test

#1297 OCM-2418 | chore: build arm64 as part of release flow
  hack/build-release.sh
Labels: approved, lgtm

#1483 [OCM-2907] Add support for json/yaml output format on all "rosa list" commands
  cmd/list/accountroles/cmd.go
  cmd/list/addon/cmd.go
  cmd/list/instancetypes/cmd.go
  cmd/list/machinepool/nodepool.go
  cmd/list/ocmroles/cmd.go
  cmd/list/oidcprovider/cmd.go
  cmd/list/region/cmd.go
  cmd/list/upgrade/cmd.go
  cmd/list/user/cmd.go
  cmd/list/userroles/cmd.go
  cmd/list/version/cmd.go
  pkg/aws/helpers.go
  pkg/ocm/addons.go
  pkg/output/output.go
Labels: approved, lgtm

#1486 OCM-3609 | feat: Disable prompt & flag for HCP while using a govcloud account
  cmd/create/accountroles/cmd.go
  pkg/aws/client.go
Labels: approved, lgtm

#1459 OCM-2447 | feat: add automatic upgrades for node pools
  cmd/upgrade/cluster/cmd.go
  cmd/upgrade/machinepool/cmd.go
  cmd/upgrade/machinepool/cmd_test.go
  pkg/ocm/nodepools_upgrades.go
  pkg/test/helpers.go
Labels: approved, lgtm

#1489 OCM-3641 | fix: edit autoscaler examples
  cmd/edit/autoscaler/cmd.go
Labels: approved, lgtm

#1490 OCM-3650 | fix: negative durations are allowed
  pkg/clusterautoscaler/flags.go
  pkg/ocm/validators.go
  pkg/ocm/validators_test.go
Labels: approved, lgtm

#1491 OCM-3643 | fix: check if autoscaler already exists before creation
  cmd/create/autoscaler/cmd.go
Labels: approved, lgtm

#1488 OCM-3640 | fix: autoscaler created when not enabled
  cmd/create/autoscaler/cmd.go
  cmd/create/cluster/cmd.go
  cmd/edit/autoscaler/cmd.go
  pkg/clusterautoscaler/flags.go
Labels: approved, lgtm

#1492 OCM-3616 | fix: resource limits range defaults
  pkg/clusterautoscaler/flags.go
Labels: approved, lgtm

#1493 Remove tbrisker from owners
  OWNERS
Labels: approved, lgtm

#1496 OCM-3673 | chore: bump version for 1.2.27
  pkg/info/info.go
Labels: approved, lgtm

#1487 OCM-3366 | fix: CLI options not validated client-side
  pkg/clusterautoscaler/flags.go
Labels: approved, lgtm

#1498 OCM-3677 | fix: cluster-autoscaler enabled for HCP
  cmd/create/autoscaler/cmd.go
  cmd/create/cluster/cmd.go
  cmd/dlt/autoscaler/cmd.go
  cmd/edit/autoscaler/cmd.go
Labels: approved, lgtm

#1499 OCM-3614: fix machine type when using disk size
  pkg/ocm/clusters.go
Labels: approved, lgtm, jira/valid-reference

#1494 OCM-2446 | feat: add a rosa describe machinepool command
  cmd/describe/cmd.go
  cmd/describe/machinepool/cmd.go
  cmd/describe/machinepool/cmd_test.go
  cmd/describe/machinepool/machinepool.go
  cmd/describe/machinepool/main_test.go
  cmd/describe/machinepool/nodepool.go
  cmd/list/machinepool/helper.go
  cmd/list/machinepool/machinepool.go
  cmd/list/machinepool/nodepool.go
  pkg/ocm/machinepools.go
  pkg/ocm/output/machinepools.go
  pkg/ocm/output/nodepools.go
Labels: approved, lgtm

#1501 OCM-2385 | fix: Allow users to reset machinepool labels in interactive mode
  pkg/helper/machinepools/helpers.go
  pkg/helper/machinepools/helpers_test.go
Labels: approved, lgtm

#1506 OCM-3711 | feat: validate disk size during machinepool creation
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/machinepool.go
  pkg/interactive/validation.go
Labels: approved, lgtm

#1509 OCM-3739 | fix: no version change in edit machinepool if upgrade scheduled
  cmd/edit/machinepool/nodepool.go
Labels: approved, lgtm

#1510 OCM-3203 | fix: Update help message on rosa upgrade role command to be consistent
  cmd/upgrade/roles/cmd.go
Labels: approved, lgtm

#1504 OCM-3738 | fix: error message to alert customer of new ingress attributes
  cmd/edit/ingress/cmd.go
  cmd/edit/ingress/flags.go
Labels: approved, lgtm

#1508 OCM-3737 | fix: align version computation create machinepool for HCP
  cmd/create/machinepool/nodepool.go
Labels: approved, lgtm

#1452 OCM-3392 | fix: don't show RH managed VPC options when selecting subnets
  cmd/create/cluster/cmd.go
  pkg/aws/policies.go
  pkg/aws/tags/utils.go
Labels: approved, lgtm

#1502 OCM-3267 | feat: Add interactive mode for shared VPC
  cmd/create/cluster/cmd.go
  cmd/create/cluster/shared_vpc.go
  pkg/aws/helpers.go
Labels: approved, lgtm

#1507 OCM-3714 | fix: don't ask for disk size for hosted cp
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1515 OCM-2083 | fix: prompts with default value are not 'optional'
  cmd/create/cluster/cmd.go
  pkg/interactive/interactive.go
Labels: approved, lgtm

#1516 OCM-2418 | chore: add arm64 builds to gitignore
  .gitignore
Labels: approved, lgtm

#1517 OCM-3115 | fix: list resources when cluster in hibernating state
  cmd/list/addon/cmd.go
  cmd/list/idp/cmd.go
  cmd/list/ingress/cmd.go
  cmd/list/machinepool/cmd.go
  cmd/list/upgrade/cmd.go
  cmd/list/user/cmd.go
Labels: approved, lgtm

#1518 OCM-3840 | fix: improve create cluster in shared VPC info message
  cmd/create/cluster/shared_vpc.go
Labels: approved, lgtm

#1519 OCM-1625 | feat: Add the ability to list clusters using an Account Role
  cmd/list/cluster/cmd.go
  pkg/aws/client.go
  pkg/aws/client_test.go
  pkg/aws/policies.go
  pkg/ocm/clusters.go
  pkg/ocm/clusters_test.go
Labels: approved, lgtm

#1512 OCM-3724 | feat: day2 security groups
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/cmd.go
  cmd/create/machinepool/machinepool.go
  cmd/create/machinepool/nodepool.go
  pkg/ocm/clusters.go
  pkg/ocm/versions.go
Labels: approved
