Repository openshift/rosa, pull requests merged in 2023-04, with the labels that each got.

#1125 Improve taint validation
  cmd/create/machinepool/machinepool.go
  cmd/create/machinepool/machinepool_suite_test.go
  cmd/create/machinepool/machinepool_test.go
Labels: approved, lgtm

#1150 [SDA-8741] If -y is specified no need to go into interactive mode creating oidc-config
  cmd/create/oidcconfig/cmd.go
Labels: approved, lgtm

#1147 oc client version local check only
  cmd/verify/oc/cmd.go
Labels: approved, lgtm

#1153 [SDA-8752] Add type of cluster column in list clusters command
  cmd/list/cluster/cmd.go
Labels: approved, lgtm

#1155 [SDA-8752] Proper naming for topology description in list clusters
  cmd/list/cluster/cmd.go
Labels: approved, lgtm

#1152 fix: checking Account roles against proper Openshift version for the 'create service' command.
  cmd/create/service/cmd.go
  go.mod
  go.sum
  pkg/ocm/versions.go
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/quota_authorization_request_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/quota_authorization_request_list_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/quota_authorization_request_list_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/quota_authorization_request_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/quota_authorization_request_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/quota_authorization_response_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/quota_authorization_response_list_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/quota_authorization_response_list_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/quota_authorization_response_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/quota_authorization_response_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/quota_authorizations_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/quota_authorizations_resource_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/root_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/delete_protection_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/delete_protection_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/delete_protection_list_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/delete_protection_list_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/delete_protection_resource_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/delete_protection_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/delete_protection_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/metrics/path_tree_data.go
  vendor/github.com/openshift-online/ocm-sdk-go/servicemgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/servicemgmt/v1/services_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/servicemgmt/v1/version_inquiry_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/servicemgmt/v1/version_inquiry_request_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/servicemgmt/v1/version_inquiry_request_list_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/servicemgmt/v1/version_inquiry_request_list_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/servicemgmt/v1/version_inquiry_request_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/servicemgmt/v1/version_inquiry_request_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/servicemgmt/v1/version_inquiry_resource_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/servicemgmt/v1/version_inquiry_response_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/servicemgmt/v1/version_inquiry_response_list_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/servicemgmt/v1/version_inquiry_response_list_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/servicemgmt/v1/version_inquiry_response_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/servicemgmt/v1/version_inquiry_response_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm

#1156 [SDA-8753] Add list operator-roles command
  cmd/list/accountroles/cmd.go
  cmd/list/cmd.go
  cmd/list/operatorroles/cmd.go
  pkg/aws/client.go
  pkg/aws/policies.go
Labels: approved, lgtm

#1158 verify: Ensure stdout is only printed in terminal mode
  cmd/verify/rosa/cmd.go
Labels: approved, lgtm

#1160 Release v1.2.16
  CHANGES.adoc
  pkg/info/info.go
Labels: approved

#1162 chore: fix version tests
  cmd/create/cluster/cmd_test.go
  pkg/ocm/versions.go
Labels: approved, lgtm

#1164 SDA-8790 | fix: use parameter installer role arn when passed
  cmd/create/oidcconfig/cmd.go
  pkg/interactive/helper.go
Labels: approved, lgtm

#1167 Fix version validation error handling
  pkg/ocm/versions.go
Labels: approved, lgtm

#1168 SDA-8804,8805 | fix: better behavior for listing operator roles
  cmd/list/operatorroles/cmd.go
  pkg/output/output.go
Labels: approved

#1161 chore: remove deprecated lib `io/ioutil`
  cmd/create/idp/github.go
  cmd/create/idp/gitlab.go
  cmd/create/idp/ldap.go
  cmd/create/idp/openid.go
  cmd/edit/cluster/cmd.go
  pkg/config/config.go
  pkg/logging/round_tripper.go
  pkg/ocm/helpers.go
Labels: approved

#1170 SDA-8808 | feat: add aws account ID to filter unmanaged OIDC configs
  cmd/create/cluster/cmd.go
  cmd/list/oidcconfig/cmd.go
  pkg/interactive/helper.go
  pkg/ocm/oidc_config.go
Labels: approved

#1169 SDA-8775: Align label and taints validation between create and edit
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/helper.go
  cmd/create/machinepool/machinepool.go
  cmd/create/machinepool/nodepool.go
  cmd/edit/machinepool/helper.go
  cmd/edit/machinepool/machinepool.go
  cmd/edit/machinepool/nodepool.go
  pkg/helper/machinepools/helpers.go
  pkg/helper/machinepools/helpers_suite_test.go
  pkg/helper/machinepools/helpers_test.go
Labels: approved, lgtm, jira/valid-reference

#1172 SDA-8805 | fix: better messages when listing operator roles for specific version
  cmd/list/operatorroles/cmd.go
Labels: approved

#1173 fix: small issue when customer sets up oidc provider with issuer url '/' at the end
  cmd/dlt/oidcprovider/cmd.go
  pkg/aws/helpers.go
Labels: approved, lgtm

#1174 SDA-6239 | fix: Add message to helper --delete param on init cmd
  cmd/initialize/cmd.go
Labels: approved, lgtm

#1177 SDA-8836 | feat: add output json/yaml to create oidc config
  cmd/create/oidcconfig/cmd.go
  pkg/output/output.go
Labels: approved, lgtm

#1179 SDA-7708 | fix: remove --tags param from example for usage
  cmd/create/cluster/cmd.go
  pkg/aws/helpers.go
Labels: approved, lgtm

#1180 Warn about `version` flag in combination with HCP managed policies
  cmd/create/accountroles/cmd.go
Labels: approved, lgtm

#1178 chore: add initial github action to checking commit message format
  .github/workflows/check-commit-format.yml
  CONTRIBUTING.md
Labels: approved, lgtm

#1181 fix: trims trailing slash in ocm api when checking env
  pkg/ocm/config.go
Labels: approved, lgtm

#1183 SDA-8861 | feat: add --etcd-encryption-kms-arn to cluster build command when in use
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1185 fix: upgrade account roles - support hosted CP managed policies
  cmd/upgrade/accountroles/cmd.go
Labels: approved, lgtm

#1186 SDA-8897 | fix: shared operator roles with managed policies
  cmd/upgrade/roles/cmd.go
  pkg/aws/policies.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#1188 SDA-8900 | feat: only allow aws auto mode when choosing and output flag enabled
  cmd/create/oidcconfig/cmd.go
Labels: approved, lgtm

#1189 SDA-8892 | fix: Ask for drain period before scheduling the update
  cmd/upgrade/cluster/cmd.go
Labels: approved, lgtm

#1191 SDA-8880 | Fix: implement list upgrades for Hypershift
  cmd/describe/upgrade/cmd.go
  cmd/list/upgrade/cmd.go
  pkg/ocm/clusters.go
Labels: approved, lgtm

#1190 SDA-8905 | feat: Implement delete upgrade command for hypershift
  cmd/dlt/upgrade/cmd.go
  pkg/ocm/upgrades.go
Labels: approved, lgtm

#1192 SDA-8880 | Fix: correctly check if an upgrade is already scheduled
  cmd/upgrade/cluster/cmd.go
Labels: approved, lgtm

#1196 Release v1.2.17
  CHANGES.adoc
  pkg/info/info.go
Labels: approved, lgtm

#1197 SDA-8900 | fix: adjust behavior for creating with -o
  cmd/create/oidcconfig/cmd.go
Labels: approved, lgtm

#1195 SDA-8920 | fix: improve upgrade roles / operator-roles info messages
  cmd/upgrade/operatorroles/cmd.go
  cmd/upgrade/roles/cmd.go
Labels: approved, lgtm

#1194 fix: Add flag to bypass confirmation for hibernate/resume
  cmd/hibernate/cluster/cmd.go
  cmd/hibernate/cmd.go
  cmd/resume/cluster/cmd.go
  cmd/resume/cmd.go
  cmd/rosa/main.go
Labels: approved, lgtm

#1201 SDA-8690 Update replicas help message for hosted-cp cluster
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1202 SDA-8382| Fix: delete tuning config bad definition
  cmd/dlt/tuningconfigs/cmd.go
Labels: approved, lgtm

#1175 SDA-6562 | feat: skip subnet choice when AZ is supplied
  cmd/create/machinepool/helper.go
  cmd/create/machinepool/machinepool.go
Labels: approved, lgtm

#1199 Refactor oidcconfig and move a reuse-able code to a new helper package
  cmd/create/oidcconfig/cmd.go
  go.sum
  pkg/helper/oidc_config/helper.go
Labels: approved, lgtm

#1205 SDA-8245 | feat: ability to set billing account parameter for hypershift clusters
  cmd/create/cluster/cmd.go
  go.mod
  go.sum
  pkg/ocm/billing.go
  pkg/ocm/clusters.go
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/aws_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/aws_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/aws_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/metrics/path_tree_data.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm

#1208 SDA-8990 | chore: bump ocm-sdk v0.1.337
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/audit_log_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/audit_log_list_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/audit_log_list_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/audit_log_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/audit_log_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/aws_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/aws_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/aws_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/internal/system_cas_windows.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved

#1210 SDA-8990 | chore: bump ocm-sdk to v0.1.338
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/internal/system_cas_windows.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved

#1212 SDA-9008 | Fix node pool edit/create behaviour when no tuning config in a cluster
  cmd/create/machinepool/nodepool.go
  cmd/edit/machinepool/nodepool.go
Labels: approved, lgtm
