Repository openshift/rosa, pull requests merged in 2023-08, with the labels that each got.

#1398 OCM-2961 | feat: add fedramp staging01 aliases
  pkg/fedramp/config.go
Labels: approved, lgtm

#1393 OCM-3011 | fix: add --region to verify network message
  .golangciversion
  cmd/verify/network/cmd.go
  cmd/verify/network/cmd_test.go
Labels: approved, lgtm

#1399 OCM-2276 | fix: more clarity into why it might have not found the prefix
  pkg/aws/policies.go
Labels: approved

#1401 OCM-2961 | fix: Remove admin identifier for stage
  pkg/fedramp/config.go
Labels: approved, lgtm

#1390 OCM-2683 | feat: include policies,namespace,name,in-use when listing operator roles
  cmd/dlt/accountroles/cmd.go
  cmd/list/operatorroles/cmd.go
  cmd/upgrade/accountroles/cmd.go
  pkg/aws/client.go
  pkg/aws/helpers.go
  pkg/aws/policies.go
  pkg/aws/tags/tags.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#1402 OCM-2425 | fix: no need to choose installer arn when already specified in args
  cmd/register/oidcconfig/cmd.go
Labels: approved, lgtm

#1404 OCM-3088 | refactor: use SDK constants for upgrades instead of hardcodes
  cmd/list/gates/cmd.go
  cmd/upgrade/cluster/cmd.go
  go.mod
  go.sum
  pkg/ocm/controlplane_upgrades.go
  pkg/ocm/upgrades.go
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/upgrade_type_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm

#1397 OCM-3047 | fix: allow supplying empty values to reset component routes
  cmd/edit/ingress/cmd.go
Labels: approved, lgtm

#1411 OCM-2425 | fix: check args not changed instead of empty is more reliable
  cmd/register/oidcconfig/cmd.go
Labels: approved, lgtm

#1406 OCM-2107 | fix: add name to subnet details when selecting interactively
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/helper.go
  pkg/aws/helpers.go
Labels: approved, lgtm

#1410 OCM-3139 | feat: bump the OCM-SDK-GO version
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/aws_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/aws_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/aws_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm

#1408 Revert "OCM-2653 | fix: remove/hide HCP managed policies before release"
  cmd/create/accountroles/cmd.go
  cmd/create/accountroles/creators.go
  cmd/create/cluster/cmd.go
  cmd/dlt/accountroles/cmd.go
  cmd/upgrade/accountroles/cmd.go
Labels: approved, lgtm

#1409 Revert "OCM-2653 | fix: Create operator-roles - hide hosted cp managed policies
  cmd/create/operatorroles/by_prefix.go
  cmd/create/operatorroles/cmd.go
Labels: approved, lgtm

#1379 OCM-2118 | feat: Warns when choosing a close to eol version
  cmd/create/cluster/cmd.go
  pkg/ocm/versions.go
Labels: approved, lgtm

#1413 OCM-3049 | feat: upgrade operator roles for the shared VPC flow
  cmd/upgrade/operatorroles/cmd.go
  cmd/upgrade/roles/cmd.go
  pkg/aws/commandbuilder/helper/roles/roles.go
  pkg/aws/helpers.go
  pkg/aws/sts.go
Labels: approved, lgtm

#1416 OCM-3152 | fix: show roles with missing policies and order by prefix
  cmd/list/operatorroles/cmd.go
  pkg/aws/policies.go
Labels: approved, lgtm

#1417 OCM-3143 | Create operator-roles - ensure shared VPC policy
  cmd/create/operatorroles/by_prefix.go
  pkg/aws/helpers.go
  pkg/aws/policies.go
Labels: approved, lgtm

#1288 OCM-15 | feat: ability to set machine pool root disk size
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/cmd.go
  cmd/create/machinepool/machinepool.go
  cmd/list/machinepool/machinepool.go
  pkg/helper/helpers.go
  pkg/interactive/validation.go
Labels: approved, lgtm

#1415 OCM-3178 | fix: accept int64 max value for disk size
  pkg/ocm/helpers.go
  pkg/ocm/helpers_test.go
Labels: approved, lgtm

#1403 OCM-2423 | fix: interactively validate issuer url and secret arn
  cmd/register/oidcconfig/cmd.go
  pkg/aws/helpers.go
  pkg/constants/oidc_config.go
  pkg/interactive/validation.go
Labels: approved, lgtm

#1412 OCM-199 | feat: Add shared pvc fields to `cluster describe` cmd
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm

#1418 OCM-1081 | fix: checks hcp role tag in all flows
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1421 OCM-1338 | fix: use utility function to retrieve acc role suffix
  pkg/aws/policies.go
Labels: approved

#1420 OCM-1209 | feat: add warning and prompt to continue when subnets are not found
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1425 OCM-1209 | fix: take correct action based on vpc prompt
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1422 OCM-2865 | feat: support shared vpc in rosa
  cmd/create/cluster/cmd.go
  pkg/ocm/clusters.go
Labels: approved, lgtm

#1426 OCM-2892 | fix: Adding default value of http tokens metadata for describe command
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm

#1301 OCM-23 | feat: Removing default pool from rosa cli
  cmd/dlt/machinepool/machinepool.go
  cmd/edit/machinepool/machinepool.go
  cmd/list/machinepool/machinepool.go
Labels: approved, lgtm

#1432 OCM-2906 | fix: ROSA CLI for IMDSv2 - Help displays same prompt instead of anything helpful
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1431 OCM-3297 | feat: improve help message for the shared VPC flow
  cmd/create/cluster/cmd.go
  cmd/create/operatorroles/cmd.go
Labels: approved, lgtm

#1430 OCM-2134 | feat: warning and prompt for tech preview hibernation
  cmd/hibernate/cluster/cmd.go
  cmd/hibernate/cluster/messages.go
Labels: approved

#1371 updating create-cluster command with autoscaler configurations
  cmd/create/cluster/cmd.go
  pkg/ocm/clusters.go
  pkg/ocm/helpers.go
  pkg/ocm/helpers_test.go
Labels: approved, lgtm

#1435 OCM-3322 | fix: add empty default ingress attribute in config for rosa init
  cmd/create/cluster/cmd.go
  cmd/initialize/cmd.go
Labels: approved, lgtm

#1429 OCM-3284 | fix: allow to choose load balancer type for sts clusters
  cmd/edit/ingress/cmd.go
Labels: approved, lgtm

#1434 OCM-3318 | fix: use latest policies if user version is empty
  cmd/create/operatorroles/cmd.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#1427 OCM-3285 | ci: Clean up OWNERS file
  OWNERS
Labels: approved, lgtm

#1436 OCM-210 | Delete cluster autoscaler functionality
  cmd/dlt/autoscaler/cmd.go
  cmd/dlt/cmd.go
  pkg/ocm/clusterautoscaler.go
Labels: approved, lgtm

#1437 OCM-3278 | chore: bump version for release 1.2.26
  pkg/info/info.go
Labels: approved, lgtm

#1419 OCM-3249 | chore: update cluster pattern in test
  cmd/verify/network/cmd_test.go
  pkg/test/helpers.go
Labels: approved, lgtm

#1339 OCM-954 | Feat: Hypershift node pool upgrades
  cmd/create/machinepool/nodepool.go
  cmd/describe/upgrade/cmd.go
  cmd/describe/upgrade/cmd_test.go
  cmd/describe/upgrade/main_test.go
  cmd/dlt/upgrade/cmd.go
  cmd/dlt/upgrade/cmd_test.go
  cmd/dlt/upgrade/main_test.go
  cmd/edit/machinepool/cmd.go
  cmd/edit/machinepool/nodepool.go
  cmd/list/upgrade/cmd.go
  cmd/list/upgrade/cmd_test.go
  cmd/list/upgrade/main_test.go
  cmd/upgrade/cluster/cmd.go
  cmd/upgrade/cluster/cmd_test.go
  cmd/upgrade/cmd.go
  cmd/upgrade/machinepool/cmd.go
  cmd/upgrade/machinepool/cmd_test.go
  cmd/upgrade/machinepool/main_test.go
  pkg/helper/versions/helpers.go
  pkg/helper/versions/helpers_test.go
  pkg/ocm/hypershift_upgrades.go
  pkg/ocm/nodepools_upgrades.go
  pkg/test/helpers.go
Labels: approved, lgtm

#1428 OCM-2611 / fix: Added check for duplcate deletion of same cluster
  cmd/dlt/cluster/cmd.go
Labels: approved, lgtm, ok-to-test

#1440 OCM-3331 | fix: default values for boolean fields of autoscaler
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1442 OCM-3356 | fix: change the wording for autoscaler params
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1443 OCM-3353 | fix: utilization-threshold missing from interactive mode
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1446 OCM-3357 | fix: add a min/max validation
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1445 OCM-3361 | fix: in interactive mode, version is required for node pools
  cmd/create/machinepool/nodepool.go
  cmd/upgrade/machinepool/cmd.go
Labels: approved, lgtm

#1441 OCM-3336 | fix: Describe cluster compute node shows wrong value as we should not look on cluster.nodes.compute anymore
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm

#1447 OCM-3377 | fix: only show warning message about EOL if there is an EOL timestamp
  pkg/ocm/versions.go
Labels: approved, lgtm

#1450 OCM-3390 | fix: better warning message for RH managed vpc
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1451 OCM-1154 | feat: add warning message for public ingress when switching HCP cluster visibility
  cmd/edit/cluster/cmd.go
  cmd/edit/cluster/cmd_test.go
  cmd/edit/cluster/main_test.go
  pkg/test/helpers.go
Labels: approved, lgtm

#1455 OCM-3404 | fix: handle output for listing operator roles
  pkg/output/output.go
Labels: approved, lgtm

#1458 OCM-3418 | fix: handle verify network 'running' state
  cmd/verify/network/cmd.go
  cmd/verify/network/cmd_test.go
Labels: approved, lgtm

#1461 OCM-3439 | fix: add info message to create account roles
  cmd/create/accountroles/cmd.go
  cmd/create/accountroles/creators.go
Labels: approved, lgtm

#1462 OCM-3428 | fix: inform user about visibility change impact in interactive mode
  cmd/edit/cluster/cmd.go
Labels: approved, lgtm

#1463 OCM-3444 | fix: edit nodepool was broken if no upgrade available
  cmd/edit/machinepool/nodepool.go
Labels: approved, lgtm

#1464 OCM-1419 | fix: validate oic-provider exists in manual mode
  cmd/create/oidcprovider/cmd.go
Labels: approved, lgtm

#1469 OCM-1478 | fix: Moved getMode to top of cluster creation so it checks mode firstly
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1467 OCM-3473 | fix: create operator-roles for shared VPC
  cmd/create/operatorroles/by_prefix.go
  cmd/create/operatorroles/common_utils.go
  pkg/aws/client.go
  pkg/aws/policies.go
Labels: approved, lgtm

#1471 OCM-2898 | fix: more accuracy to --worker-disk-size
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1465 OCM-3478 | fix: automatic control plane upgrade when no update is available
  cmd/upgrade/cluster/cmd.go
  cmd/upgrade/cluster/cmd_test.go
Labels: approved, lgtm
