Repository openshift/rosa, pull requests merged in 2023-03, with the labels that each got.

#1092 Create cluster - roles with managed policies
  pkg/aws/policies.go
Labels: approved, lgtm

#1094 SDA-8040 Align machinepool condition for enter in interactive mode
  cmd/edit/machinepool/nodepool.go
Labels: approved, lgtm

#1091 SDA-8325 Add subnets field for Default Worker
  cmd/list/machinepool/machinepool.go
Labels: approved, lgtm

#1096 [SDA-7992] Add option to remove oidc provider from oidc endpoint url
  cmd/create/cluster/cmd.go
  cmd/create/oidcconfig/cmd.go
  cmd/dlt/cluster/cmd.go
  cmd/dlt/oidcconfig/cmd.go
  cmd/dlt/oidcprovider/cmd.go
  pkg/aws/client.go
  pkg/aws/helpers.go
  pkg/aws/policies.go
  pkg/ocm/clusters.go
Labels: approved, lgtm

#1100 Create OCM admin roles in manual mode - add all tags to policy
  cmd/create/ocmrole/cmd.go
Labels: approved, lgtm

#1097 [SDA-8387] Add possibility to delete operator roles from prefix
  cmd/dlt/cluster/cmd.go
  cmd/dlt/operatorrole/cmd.go
  pkg/aws/client.go
  pkg/aws/policies.go
  pkg/aws/sts.go
Labels: approved, lgtm

#1098 [SDA-8354] Allow creating operator roles prior to cluster spec
  cmd/create/cluster/cmd.go
  cmd/create/operatorroles/by_clusterkey.go
  cmd/create/operatorroles/by_prefix.go
  cmd/create/operatorroles/cmd.go
  cmd/create/operatorroles/common_utils.go
  cmd/create/service/cmd.go
  pkg/aws/helpers.go
  pkg/aws/policy_document.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#1088 SDA-8218 Support version parameter on hosted machine pools
  cmd/create/cluster/cmd.go
  cmd/create/cluster/cmd_test.go
  cmd/create/machinepool/cmd.go
  cmd/create/machinepool/machinepool.go
  cmd/create/machinepool/nodepool.go
  cmd/edit/machinepool/cmd.go
  cmd/edit/machinepool/machinepool.go
  cmd/edit/machinepool/nodepool.go
  cmd/list/machinepool/nodepool.go
  pkg/helper/versions/helpers.go
  pkg/helper/versions/helpers_test.go
  pkg/helper/versions/main_test.go
  pkg/ocm/versions.go
  pkg/ocm/versions_test.go
Labels: approved, lgtm

#1103 [SDA-8354] Check if cmd was progmatically called before erroring
  cmd/create/operatorroles/cmd.go
Labels: approved, lgtm

#1101 Fix inconsistencies across commands providing a watch flag
  cmd/create/cluster/cmd.go
  cmd/dlt/cluster/cmd.go
Labels: approved, lgtm

#1106 [SDA-8445] Add check for cluster version compatibility when reusing the operator roles
  cmd/create/cluster/cmd.go
  cmd/create/operatorroles/by_clusterkey.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#1108 [SDA-8450] Use role name instead of role arn for manual creation by prefix
  cmd/create/operatorroles/by_prefix.go
Labels: approved, lgtm

#1105 [SDA-8451] Delete oidc-provider cmd should not check flags when is progmatically called
  cmd/dlt/oidcprovider/cmd.go
Labels: approved, lgtm

#930 [SDA-7003] Block --watch when on manual mode for creating cluster
  cmd/create/cluster/cmd.go
Labels: approved, lgtm, lifecycle/stale

#1113 [SDA-8452] Check if bucket page returns 404
  cmd/create/cluster/cmd.go
  cmd/create/operatorroles/by_prefix.go
  pkg/helper/helpers.go
Labels: approved, lgtm

#1115 Create Hypershift account roles with managed policies
  cmd/create/accountroles/cmd.go
  cmd/create/accountroles/creators.go
  pkg/aws/policies.go
  pkg/aws/tags/tags.go
Labels: approved, lgtm

#1118 Create account roles - hide `hosted-cp` flag
  cmd/create/accountroles/cmd.go
Labels: approved, lgtm

#1119 Create account roles - prompt accurate message for cluster creation
  cmd/create/accountroles/cmd.go
Labels: approved, lgtm

#1114 Hypershift - create cluster
  cmd/create/cluster/cmd.go
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/roles/cmd.go
  pkg/aws/client.go
  pkg/aws/policies.go
  pkg/helper/roles/helpers.go
Labels: approved, lgtm

#1102 SDA-8224 Deprecate MultiAZ validations for hosted clusters
  cmd/create/cluster/cmd.go
  pkg/aws/client.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#1120 Create Hypershift operator roles
  cmd/create/operatorroles/by_clusterkey.go
  cmd/create/operatorroles/by_prefix.go
  pkg/aws/helpers.go
  pkg/aws/tags/tags.go
Labels: approved, lgtm

#1123 Fix hostedcp multiaz subnets validation on interactive mode
  cmd/create/cluster/cmd.go
  pkg/interactive/validation.go
Labels: approved, lgtm

#1121 Delete account-roles - handle Hypershift roles
  cmd/dlt/accountroles/cmd.go
  pkg/aws/client.go
  pkg/aws/policies.go
Labels: approved, lgtm

#1124 Upgrade cluster with hosted CP policies
  cmd/create/operatorroles/by_clusterkey.go
  cmd/upgrade/operatorroles/cmd.go
  cmd/upgrade/roles/cmd.go
  pkg/aws/client.go
  pkg/aws/helpers.go
  pkg/aws/policies.go
  pkg/helper/roles/helpers.go
Labels: approved, lgtm

#1112 [SDA-8369] Update versions to include hypershift_enabled and add validation
  cmd/create/cluster/cmd.go
  cmd/create/cluster/cmd_test.go
  cmd/create/machinepool/nodepool.go
  cmd/edit/machinepool/nodepool.go
  cmd/list/accountroles/cmd.go
  pkg/helper/versions/helpers.go
  pkg/ocm/versions.go
  pkg/ocm/versions_test.go
Labels: approved, lgtm

#1129 Revert "[SDA-8369] Update versions to include hypershift_enabled and …
  cmd/create/cluster/cmd.go
  cmd/create/cluster/cmd_test.go
  cmd/create/machinepool/nodepool.go
  cmd/edit/machinepool/nodepool.go
  cmd/list/accountroles/cmd.go
  pkg/helper/versions/helpers.go
  pkg/ocm/versions.go
  pkg/ocm/versions_test.go
Labels: approved, lgtm

#1132 [SDA-8621] Use oidcConfigIdFlag instead of var
  cmd/create/cluster/cmd.go
Labels: approved

#1133 [SDA-8587] Check specific prefix instead of all op roles that start with prefix
  pkg/aws/policies.go
Labels: approved

#1137 [SDA-8611] Cluster flow oidc provider flow should use issuer url instead
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1138 [SDA-8610] Interactive mode in unmanaged oidc config creation
  cmd/create/oidcconfig/cmd.go
Labels: approved

#1131 SDA-8220 Support autorepair parameter for hosted clusters
  cmd/create/machinepool/cmd.go
  cmd/create/machinepool/machinepool.go
  cmd/create/machinepool/nodepool.go
  cmd/edit/machinepool/cmd.go
  cmd/edit/machinepool/machinepool.go
  cmd/edit/machinepool/nodepool.go
  cmd/list/machinepool/helper.go
  cmd/list/machinepool/machinepool.go
  cmd/list/machinepool/nodepool.go
Labels: approved, lgtm

#1130 Delete account roles - classic ROSA
  cmd/dlt/accountroles/cmd.go
Labels: approved, lgtm

#1139 [SDA-8653] Extra message when operator roles prefix is already in use
  pkg/aws/policies.go
Labels: approved, lgtm

#1135 SDA-8551 Sync replicas validation for hosted clusters
  cmd/create/machinepool/nodepool.go
  cmd/edit/machinepool/nodepool.go
  pkg/helper/machinepools/helpers.go
Labels: approved, lgtm

#1140 [SDA-8657] Better UX when using oidc config id and related commands
  cmd/create/cluster/cmd.go
  cmd/create/oidcconfig/cmd.go
  cmd/create/oidcprovider/cmd.go
  cmd/create/operatorroles/by_prefix.go
  cmd/dlt/oidcconfig/cmd.go
  pkg/aws/policies.go
  pkg/interactive/helper.go
Labels: approved, lgtm

#1142 Delete account-roles - delete both types for the default flow
  cmd/dlt/accountroles/cmd.go
Labels: approved, lgtm

#1141 [SDA-8587] Favoring regex when deleting operator roles by prefix
  pkg/aws/policies.go
Labels: approved, lgtm

#1126 Add control plane upgrades for Hypershift cluster
  cmd/describe/cluster/cmd.go
  cmd/describe/upgrade/cmd.go
  cmd/list/gates/cmd.go
  cmd/upgrade/cluster/cmd.go
  pkg/ocm/upgrades.go
Labels: approved, lgtm

#1143 UX improvements for oidc-config cmds and cluster creation
  cmd/create/cluster/cmd.go
  cmd/create/oidcconfig/cmd.go
  cmd/dlt/oidcconfig/cmd.go
  pkg/aws/client.go
Labels: approved, lgtm

#1144 [SDA-8685] Added hosted-cp to rosa list versions
  cmd/list/version/cmd.go
Labels: approved, lgtm

#1145 Fixing some ui issues for oidc configs
  cmd/create/oidcconfig/cmd.go
  cmd/dlt/oidcconfig/cmd.go
  pkg/aws/client.go
Labels: approved

#1146 [SDA-8717] Interactive mode --classic-oidc-config param should not list oidc configs
  cmd/create/cluster/cmd.go
Labels: approved, lgtm
