Repository openshift/rosa, pull requests merged in 2024-07, with the labels that each got.

#2200 OCM-8925 | test: automate id:72166 set and get config via rosacli
  tests/ci/labels/features.go
  tests/e2e/test_rosacli_config.go
  tests/utils/exec/rosacli/ocm_resource_service.go
Labels: approved, lgtm

#2212 OCM-9225 | test: fixing id:36128,67348,72195 hcp ci fix
  tests/e2e/rosa_autoscaler_test.go
  tests/e2e/test_rosacli_idp_user.go
  tests/utils/exec/rosacli/machinepool_service.go
Labels: approved, lgtm

#2215 OCM-9225 | test: fixing id:67275 ci fix
  tests/e2e/rosa_autoscaler_test.go
  tests/utils/config/support.go
  tests/utils/exec/rosacli/autoscaler_service.go
Labels: approved, lgtm

#2217 OCM-9116 | chore: update next release to 1.2.43
  pkg/info/info.go
Labels: approved, lgtm

#2218 OCM-9273 | test: fix id:74225 and id:73731
  tests/e2e/test_rosacli_policy.go
  tests/e2e/test_rosacli_upgrade.go
Labels: approved, lgtm

#2122 OCM-7254 | feat: Move edit machinepool non-cmd funcs to pkg and test
  cmd/edit/machinepool/cmd.go
  cmd/edit/machinepool/cmd_test.go
  cmd/edit/machinepool/machinepool.go
  cmd/edit/machinepool/machinepool_test.go
  cmd/edit/machinepool/nodepool.go
  cmd/edit/machinepool/nodepool_test.go
  pkg/machinepool/machinepool.go
  pkg/machinepool/machinepool_test.go
  pkg/machinepool/output.go
  pkg/ocm/output/nodepools_test.go
Labels: approved, lgtm

#2216 OCM-8453 | fix: --multi-availability-zone flag must not be supported for HCP cluster while creating nodepool
  cmd/create/machinepool/nodepool.go
Labels: approved, lgtm

#2219 OCM-9301 | test: fixing id 52764
  tests/utils/exec/rosacli/machinepool_service.go
Labels: approved, lgtm, ok-to-test

#2220 OCM-9301 | test: updated case id:68173
  tests/e2e/test_rosacli_machine_pool.go
  tests/utils/exec/rosacli/machinepool_service.go
Labels: approved, lgtm, ok-to-test

#2225 OCM-9347 | ci: Fix sensitive problem when cases run
  tests/utils/exec/rosacli/cmd_runner.go
  tests/utils/log/constants.go
Labels: approved, lgtm

#2213 OCM-9240 | test: fixing id:49137,53031
  tests/e2e/test_rosacli_idp.go
Labels: approved, lgtm

#2223 OCM-9339 | test: fixing id:72195,70859 ci fix
  tests/e2e/hcp_machine_pool_test.go
  tests/e2e/test_rosacli_machine_pool.go
  tests/e2e/test_rosacli_operator_roles.go
Labels: approved, lgtm

#2227 OCM-9344 | ci: Fix latest version has no z-stream upgrade issue
  tests/utils/exec/rosacli/version_service.go
  tests/utils/profilehandler/data_preparation.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2230 OCM-9373 | ci: Add jerichokeyne,jfrazierRH,OAharoni-RedHat to reviewers of tests package
  tests/OWNERS
Labels: approved, lgtm

#2232 OCM-9406 | test: Automated id:55979,38194
  tests/e2e/test_rosacli_cluster_post.go
  tests/e2e/test_rosacli_machine_pool.go
  tests/utils/common/constants/general.go
Labels: approved, lgtm

#2231 OCM-9409 | test: automate id:52106,64620
  tests/e2e/test_rosacli_ocm_role.go
  tests/e2e/test_rosacli_oidc_config.go
  tests/utils/common/oidc.go
  tests/utils/exec/rosacli/ocm_resource_service.go
Labels: approved, lgtm

#2233 OCM-9377 | ci: Fix rosa-hcp-external-auth installation failure
  tests/e2e/e2e_setup_test.go
  tests/utils/config/support.go
Labels: approved, lgtm

#2235 OCM-9159 | feat: upgrade ocm-sdk-go to 0.1.428
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/aws_node_pool_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/aws_node_pool_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/aws_node_pool_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm

#2228 OCM-9364 | test: automate id:36293,57102,64078
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_machine_pool.go
Labels: approved, lgtm

#2238 OCM-9448 | ci: fix y and z stream upgrade failure for hcp cluster
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2240 OCM-5648 | feat: support both yaml and json format for tuningconfigs
  cmd/create/externalauthprovider/externalauthprovider_suite_test.go
  cmd/create/tuningconfigs/cmd_test.go
  cmd/create/tuningconfigs/spec.json
  cmd/create/tuningconfigs/spec.yaml
  cmd/create/tuningconfigs/tuningconfigs_suite_test.go
  pkg/input/helper.go
Labels: approved, lgtm

#2237 OCM-9466 | ci: Fix ids:59551,74661,64620 + HCP upgrade profiles/autos…
  tests/e2e/test_rosacli_oidc_config.go
  tests/e2e/test_rosacli_operator_roles.go
  tests/utils/exec/rosacli/version_service.go
  tests/utils/profilehandler/data_preparation.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2239 OCM-9340 | fix: Re-add max-surge/max-unavailable code
  pkg/machinepool/machinepool.go
Labels: approved, lgtm

#2242 OCM-9490 | ci: fix y-stream upgrade cannot be generated issue
  tests/utils/exec/rosacli/version_service.go
Labels: approved, lgtm

#2244 OCM-9535 | test: fix id:73731 fix to use an available upgrading versi…
  tests/e2e/test_rosacli_upgrade.go
Labels: approved, lgtm

#2246 OCM-9139 | fix: Enable maxSurge and maxUnavailable for interactive mode
  cmd/create/machinepool/nodepool.go
  pkg/machinepool/machinepool.go
Labels: approved, lgtm

#2248 OCM-9600 | ci: fix id:57102 and make error contains the error message when command run failed
  tests/e2e/test_rosacli_machine_pool.go
  tests/e2e/test_rosacli_oidc_config.go
  tests/utils/exec/rosacli/cmd_runner.go
Labels: approved, lgtm

#2249 OCM-9596 | test: fix ids:72162,64620 fix failures on PROW CI testing
  tests/e2e/test_rosacli_oidc_config.go
  tests/e2e/test_rosacli_token.go
  tests/utils/exec/rosacli/cmd_runner.go
Labels: approved, lgtm

#2250 OCM-9602 | test: fix id: 73731 for HCP cluster
  tests/e2e/test_rosacli_upgrade.go
Labels: approved, lgtm

#2252 OCM-9597 | ci: add more debug info for shared vpc preparetion
  tests/utils/profilehandler/data_preparation.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2236 OCM-7255 | feat: Edit machinepool refactored to use new runner
  cmd/edit/cmd.go
  cmd/edit/machinepool/cmd.go
  cmd/edit/machinepool/cmd_test.go
  cmd/edit/machinepool/options.go
  cmd/edit/machinepool/options_test.go
  pkg/machinepool/machinepool.go
  pkg/test/helpers.go
Labels: approved, lgtm

#2142 OCM-7184 | feat: Moving create machinepool and nodepool functions from cmd -> pkg
  cmd/create/machinepool/cmd.go
  cmd/create/machinepool/helper.go
  cmd/create/machinepool/helper_test.go
  cmd/create/machinepool/machinepool.go
  cmd/create/machinepool/machinepool_suite_test.go
  cmd/create/machinepool/nodepool.go
  pkg/machinepool/helper.go
  pkg/machinepool/helper_test.go
  pkg/machinepool/machine_pool_args.go
  pkg/machinepool/machinepool.go
  pkg/machinepool/machinepool_mock.go
  pkg/machinepool/machinepool_test.go
Labels: approved, lgtm

#2011 OSD-22376 | refactor: updates fedramp client id configuration
  cmd/login/cmd.go
  pkg/fedramp/config.go
Labels: approved, lgtm

#2202 OCM-9152 | test: automate id:74556,74408,74433 create/edit cluster with additional allowed principals
  go.mod
  go.sum
  tests/ci/data/profiles/rosa-hcp.yaml
  tests/e2e/hcp_cluster_test.go
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_cluster_post.go
  tests/utils/config/cluster.go
  tests/utils/exec/rosacli/cluster_service.go
  tests/utils/profilehandler/data_cleaner.go
  tests/utils/profilehandler/data_preparation.go
  tests/utils/profilehandler/interface.go
  tests/utils/profilehandler/profile_handler.go
  vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/role.go
  vendor/modules.txt
Labels: approved, lgtm

#2243 OCM-9293 | test: automate id:60956,57408,74761
  tests/e2e/test_rosacli_account_roles.go
  tests/e2e/test_rosacli_operator_roles.go
  tests/utils/common/role.go
Labels: approved, lgtm

#2253 OCM-9618 | test: fixing id:64917 hcp ci fix
  tests/e2e/test_rosacli_network_verifier.go
  tests/utils/config/support.go
Labels: approved, lgtm

#2257 OCM-9626 | fix: Fixed slow tests for break glass credential implementation
  cmd/create/breakglasscredential/cmd.go
  pkg/ocm/break_glass_credential.go
  pkg/ocm/break_glass_credential_test.go
Labels: approved, lgtm

#2259 OCM-9645 | fix: Add back maxSurge and maxUnavailabe for create HCP NPs
  cmd/create/machinepool/cmd.go
Labels: approved, lgtm

#2262 OCM-9653 | test: automate id:42832 hibernate and resume then delete cluster via rosacli
  tests/ci/labels/features.go
  tests/ci/labels/runtime.go
  tests/e2e/test_rosacli_hibernate.go
  tests/utils/exec/rosacli/cluster_service.go
  tests/utils/exec/rosacli/cmd_runner.go
Labels: approved, lgtm

#2261 OCM-9294 | test: automate id:53570 create cluster with IAM role path
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2247 OCM-5648 | ci: Update ids:63164,63178,63179
  go.mod
  tests/e2e/hcp_tuning_config_test.go
  tests/e2e/test_rosacli_node_pool.go
  tests/utils/exec/rosacli/tuning_config_service.go
Labels: approved, lgtm

#2269 OCM-7184 | fix: Fixing regression problems for OCM-9620,OCM-9655,OCM-9654,OCM-9625
  cmd/create/machinepool/cmd.go
Labels: approved, lgtm

#2260 OCM-8930 | feat: support IMDSv2 in HCP
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/cmd.go
  cmd/describe/machinepool/cmd_test.go
  pkg/machinepool/helper.go
  pkg/machinepool/helper_test.go
  pkg/machinepool/machine_pool_args.go
  pkg/machinepool/machinepool.go
  pkg/machinepool/output.go
  pkg/machinepool/output_test.go
  pkg/ocm/output/nodepools.go
Labels: approved, lgtm

#2267 OCM-8988 | test:Automated id:57105,59430,67412
  tests/e2e/test_rosacli_machine_pool.go
  tests/e2e/test_rosacli_node_pool.go
  tests/utils/exec/rosacli/machinepool_upgrade_service.go
Labels: approved, lgtm

#2270 OCM-9767 | test: fix id:55979 for private-link and shared-vpc profile
  tests/e2e/test_rosacli_machine_pool.go
Labels: approved, lgtm

#2266 OCM-9724 | fix: Elevate QE approvers to main ROSA approvers to reduce TOIL and enable QE team
  OWNERS
Labels: approved, lgtm

#2268 OCM-9705 | ci: Setup COMPUTE_MACHINE_TYPE global env
  tests/ci/config/config.go
  tests/e2e/test_rosacli_cluster_post.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2264 OCM-9690 | test: update id:74387,64078
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_node_pool.go
Labels: approved, lgtm

#2241 OCM-9282 | test: automate case id:54869
  tests/e2e/hcp_cluster_test.go
Labels: approved, lgtm

#2271 OCM-9769 | test: fix Add timeout after creating account-roles
  tests/utils/exec/rosacli/ocm_resource_service.go
Labels: approved, lgtm

#2251 OCM-9304 | test: Automate OCP-37499 Users can upgrade NON-STS rosa cluster across Y stream
  tests/ci/data/profiles/rosa-classic.yaml
  tests/e2e/test_rosacli_upgrade.go
  tests/utils/common/constants/cluster.go
  tests/utils/exec/rosacli/cluster_service.go
Labels: approved, lgtm

#2276 OCM-9833 | fix: remove dot import from machine pools
  pkg/aws/client_mock.go
  pkg/machinepool/machinepool.go
  pkg/machinepool/machinepool_mock.go
Labels: approved, lgtm

#2275 OCM-9725 | test: Fix 45161 to make it skip shared vpc profile
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2277 OCM-7875 | fix: Do not allow creating operator roles with managed policies role arn but no --hosted-cp flag
  cmd/create/operatorroles/cmd.go
Labels: lgtm

#2280 OCM-9865 | test: fix id:75150
  tests/e2e/test_rosacli_cluster_post.go
  tests/utils/common/constants/cluster.go
Labels: approved, lgtm

#2272 OCM-9288 | test: automate id:60688 reuse operator-roles and oidc config
  tests/e2e/test_rosacli_cluster.go
  tests/utils/common/string.go
Labels: approved, lgtm

#2283 OCM-8932 | ci: add support for imdsv2 for hcp cluster
  tests/ci/data/profiles/rosa-hcp.yaml
Labels: approved, lgtm

#2274 OCM-9291 | test: automate id:59530 create byo oidc config cluster via rosacli
  tests/e2e/test_rosacli_cluster_post.go
Labels: approved, lgtm

#2285 OCM-9917 | fix: Bug related to editing min/max replicas (machinepools)
  cmd/edit/machinepool/cmd_test.go
  cmd/edit/machinepool/options.go
  cmd/edit/machinepool/options_test.go
  pkg/machinepool/machinepool.go
Labels: approved, lgtm

#2279 OCM-9817 | test: automate id:75210 delete byo oidc config cluster via rosacli
  tests/e2e/test_rosacli_cluster_post.go
  tests/utils/common/oidc.go
  tests/utils/profilehandler/interface.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2287 OCM-9935 | test: fix ids: 60688,73731 to use cluster service to confirm if the cluster is HCP
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_upgrade.go
Labels: approved, lgtm

#2284 OCM-8933 | test: automate id:75114,75227 hcp cluster/machinepool creation supports imdsv2
  tests/e2e/test_rosacli_cluster_post.go
  tests/e2e/test_rosacli_node_pool.go
  tests/utils/common/constants/general.go
  tests/utils/config/support.go
  tests/utils/exec/rosacli/machinepool_service.go
Labels: approved, lgtm

#2289 OCM-9917 | fix: Issue with interactive + replicas edit machinepool
  cmd/edit/machinepool/cmd_test.go
  cmd/edit/machinepool/options.go
  pkg/machinepool/machinepool.go
  pkg/machinepool/validation.go
  pkg/machinepool/validation_test.go
Labels: approved, lgtm

#2290 OCM-9945 | test: fix failure of 55979
  tests/e2e/test_rosacli_machine_pool.go
  tests/utils/exec/rosacli/ocm_resource_service.go
Labels: approved, lgtm

#2293 OCM-9958 | ci: make pr check enhancement to match kinds of commit messages
  tests/ci/config/config.go
  tests/e2e/e2e_pre_check.go
  tests/utils/exec/rosacli/pr_check.go
Labels: approved, lgtm

#2297 OCM-9958 | ci: fix the pr-check feature filter if condition
  tests/e2e/e2e_pre_check.go
Labels: approved, lgtm

#2296 OCM-9967 | ci: fix id:73731,75150,73492
  tests/ci/config/config.go
  tests/e2e/test_rosacli_cluster_post.go
  tests/e2e/test_rosacli_node_pool.go
  tests/e2e/test_rosacli_upgrade.go
Labels: approved, lgtm

#2299 OCM-9973 | ci: Fix the commit-focus cannot find issue
  tests/utils/exec/rosacli/pr_check.go
Labels: approved, lgtm

#2295 OCM-9971 | ci: fix rosa-advanced profile creation failure due to autoscaler validation
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2302 OCM-9984 | fix: Change replica (min, max, and normal) minimum to 0
  pkg/machinepool/validation.go
  pkg/machinepool/validation_test.go
Labels: approved, lgtm

#2303 OCM-9967 | ci: fix id:59530,73492
  tests/e2e/test_rosacli_cluster_post.go
  tests/e2e/test_rosacli_node_pool.go
Labels: approved, lgtm

#2286 OCM-9786 | test: automated cases id:73161,74656
  tests/e2e/test_rosacli_cluster.go
  tests/utils/common/constants/cluster.go
  tests/utils/exec/rosacli/cluster_service.go
Labels: approved, lgtm

#2294 OCM-9296 | test: automate ids:41822,75256 Create/Delete STS cluster successfully via rosacli
  tests/e2e/test_rosacli_cluster_post.go
  tests/utils/profilehandler/interface.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2309 OCM-10024 | ci: fix id:67275
  tests/e2e/rosa_autoscaler_test.go
Labels: approved, lgtm

#2312 OCM-10009 | feat: Adding taints effect validation
  pkg/helper/machinepools/helpers.go
  pkg/helper/machinepools/helpers_suite_test.go
  pkg/helper/machinepools/helpers_test.go
Labels: approved, lgtm
