Repository openshift/rosa, pull requests merged in 2024-08, with the labels that each got.

#2306 OCM-10011 | test: automated cases id:73538
  tests/e2e/test_rosacli_ingress.go
Labels: approved, lgtm

#2282 OCM-9904 | test: automated cases id:72174
  tests/e2e/test_rosacli_machine_pool.go
Labels: approved, lgtm

#2298 OCM-3704 | fix: Update error message for create/describe/list/delete machine pool upgrade policy
  cmd/describe/upgrade/cmd.go
  cmd/dlt/upgrade/cmd.go
  cmd/list/upgrade/cmd.go
  cmd/upgrade/machinepool/cmd.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
Labels: approved, lgtm

#1918 OCM-7571 | chore: switch from ghodss/yaml to sigs.k8s.io/yaml
  go.mod
  go.sum
  pkg/input/helper.go
  pkg/output/output.go
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/modules.txt
  vendor/sigs.k8s.io/yaml/.gitignore
  vendor/sigs.k8s.io/yaml/.travis.yml
  vendor/sigs.k8s.io/yaml/CONTRIBUTING.md
  vendor/sigs.k8s.io/yaml/LICENSE
  vendor/sigs.k8s.io/yaml/OWNERS
  vendor/sigs.k8s.io/yaml/README.md
  vendor/sigs.k8s.io/yaml/RELEASE.md
  vendor/sigs.k8s.io/yaml/SECURITY_CONTACTS
  vendor/sigs.k8s.io/yaml/code-of-conduct.md
  vendor/sigs.k8s.io/yaml/fields.go
  vendor/sigs.k8s.io/yaml/yaml.go
  vendor/sigs.k8s.io/yaml/yaml_go110.go
Labels: approved, lgtm, ok-to-test

#2313 OCM-10034 | chore: update module gitlab.com/c0b/go-ordered-json to in…
  go.mod
  go.sum
  vendor/gitlab.com/c0b/go-ordered-json/LICENSE
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#2310 OCM-10021 | test: fix ids:57408,43053,74761,60956,60971
  tests/e2e/test_rosacli_account_roles.go
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_oidc_config.go
  tests/e2e/test_rosacli_operator_roles.go
  tests/utils/common/role.go
  tests/utils/exec/rosacli/cmd_runner.go
Labels: approved, lgtm

#2315 OCM-9954 | test: update id:57102 to also check replicas number when edit label/taint
  tests/e2e/test_rosacli_machine_pool.go
Labels: approved, lgtm

#2281 OCM-9778 | test: Automate OCP-57094 Describe/List rosa upgrade via rosacli
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_upgrade.go
  tests/utils/common/constants/general.go
  tests/utils/exec/rosacli/cluster_service.go
  tests/utils/exec/rosacli/cmd_client.go
  tests/utils/exec/rosacli/upgrade_service.go
Labels: approved, lgtm

#2308 OCM-10020 | test: fix id:49137,53031
  tests/e2e/test_rosacli_idp.go
Labels: approved, lgtm

#2319 OCM-10143 | test: fix ids:60688,59530,74761
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_cluster_post.go
  tests/e2e/test_rosacli_operator_roles.go
Labels: approved, lgtm

#2320 OCM-10024 | ci: fix id:75150,73731,73492
  tests/ci/config/config.go
  tests/e2e/test_rosacli_cluster_post.go
  tests/e2e/test_rosacli_node_pool.go
  tests/e2e/test_rosacli_upgrade.go
  tests/utils/config/cluster.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2318 OCM-10085 | ci: fix external-auth profile failure and introduce more logs
  tests/utils/config/support.go
  tests/utils/exec/occli/cmd_client.go
Labels: approved, lgtm

#2323 OCM-10024 | ci: fix hcp profile fail
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2322 OCM-10144 | fix: List upgrade for cluster asking machinepool identifier producing error
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
Labels: approved, lgtm

#2292 OCM-9775 | test: Automate OCP-54469 OCP-75246
  tests/e2e/test_rosacli_account_roles.go
Labels: approved, lgtm

#2327 OCM-9974 | fix: Change options validations to allow 0 min replicas as well
  cmd/edit/machinepool/options.go
  cmd/edit/machinepool/options_test.go
Labels: approved, lgtm

#2329 OCM-3303 | fix: a regression caused the external ID not to be forwarded
  cmd/create/cluster/cmd.go
  cmd/list/instancetypes/cmd.go
  pkg/machinepool/machinepool.go
  pkg/ocm/machines.go
Labels: approved, lgtm

#2324 OCM-10175 | test: fix id:67057
  tests/e2e/test_rosacli_machine_pool.go
Labels: approved, lgtm

#2326 OCM-10195 | fix: cmd/version arguments not being passed
  cmd/version/cmd.go
  cmd/version/cmd_test.go
  cmd/version/options.go
  cmd/version/options_test.go
Labels: approved, lgtm

#2305 OCM-2394 | fix: Delete classic and hosted-cp account roles automatically if -y flag is set
  cmd/dlt/accountroles/cmd.go
Labels: approved, lgtm

#2333 OCM-10263 | ci: fix id:57094
  tests/e2e/test_rosacli_upgrade.go
Labels: approved, lgtm

#2321 OSDOCS-11559 | docs: Add example for enabling UWM day-2
  cmd/edit/cluster/cmd.go
Labels: approved, lgtm

#2336 OCM-10266 | test: automate ids:75504,57410 Create/Delete cluster and…
  tests/e2e/test_rosacli_cluster_post.go
  tests/e2e/test_rosacli_operator_roles.go
  tests/utils/common/constants/general.go
  tests/utils/common/role.go
Labels: approved, lgtm

#2335 OCM-9776 | test: Automate OCP-55883 Upgrade STS rosa cluster across Y stream via ROSA cli
  tests/e2e/test_rosacli_upgrade.go
Labels: approved, lgtm

#2338 OCM-10298 | ci: fix id:73391,65160
  tests/e2e/test_rosacli_idp.go
  tests/e2e/test_rosacli_node_pool.go
Labels: approved, lgtm

#2332 OCM-10248 | test: automated cases id:75052
  tests/e2e/test_rosacli_ingress.go
Labels: approved, lgtm

#2177 OCM-8641 | automated case id :68971
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2337 OCM-10274 | ci: Automate ids:75525,75535,75527,75526
  tests/ci/data/profiles/rosa-hcp.yaml
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_cluster_post.go
  tests/utils/common/slice.go
  tests/utils/exec/rosacli/cluster_service.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2343 OCM-10331 | ci: fix id:72174,75527
  tests/e2e/test_rosacli_cluster_post.go
  tests/e2e/test_rosacli_machine_pool.go
  tests/e2e/test_rosacli_region.go
Labels: approved, lgtm

#2341 OCM-10303 | feat: unhide no-cni flag at cluster creation
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#2340 OCM-9704 | feat: persist refreshed tokens
  cmd/logs/install/cmd.go
  cmd/logs/uninstall/cmd.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/ocm/client.go
  pkg/ocm/client_test.go
Labels: approved, lgtm

#2348 OCM-9503 | chore: increment master version to 1.2.45 (1 above 1.2.44-rc1)
  pkg/info/info.go
Labels: approved

#2331 OCM-7552 | feat: output IAM policies that are being attached to IAM roles
  cmd/attach/policy/cmd.go
  cmd/attach/policy/cmd_test.go
  cmd/create/accountroles/creators.go
  cmd/create/ocmrole/cmd.go
  cmd/create/operatorroles/by_clusterkey.go
  cmd/create/operatorroles/by_prefix.go
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/roles/cmd.go
  pkg/aws/client.go
  pkg/aws/client_mock.go
  pkg/aws/policies.go
  pkg/aws/policies_test.go
  pkg/helper/roles/helpers.go
  pkg/policy/policy_service.go
  pkg/policy/policy_service_test.go
Labels: approved, lgtm

#2342 OCM-6419 | feat: Move fetching thumbprint from ROSA to backend
  cmd/create/oidcprovider/cmd.go
  pkg/ocm/oidc_config.go
Labels: approved, lgtm

#2344 OCM-10333 | ci: fix ids:57094,55883,37499
  tests/e2e/test_rosacli_upgrade.go
Labels: approved, lgtm

#2354 OCM-10412 | test: automate ids:41824,74620,38851
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_verify.go
  tests/utils/exec/rosacli/cmd_client.go
  tests/utils/exec/rosacli/verify_service.go
Labels: approved, lgtm

#2345 OCM-10341 | ci: fix z-stream upgrade cluster creation failed
  tests/utils/exec/rosacli/version_service.go
Labels: approved, lgtm

#2349 OCM-9284 | test: Automate id:64187
  tests/e2e/test_rosacli_upgrade.go
  tests/utils/exec/rosacli/upgrade_service.go
Labels: approved, lgtm

#2359 OCM-10459 | fix: trim double quotes of component route parameter
  cmd/edit/ingress/cmd_test.go
  cmd/edit/ingress/flags.go
Labels: approved

#2358 OCM-10299 | ci: fix rosa-hcp-external-auth deploy failure
  tests/e2e/e2e_setup_test.go
Labels: approved, lgtm

#2352 OCM-7551 | feat: output content of trust policy attached to a role
  cmd/create/accountroles/creators.go
  cmd/create/ocmrole/cmd.go
  cmd/create/operatorroles/by_clusterkey.go
  cmd/create/operatorroles/by_prefix.go
  cmd/create/userrole/cmd.go
  cmd/install/addon/cmd.go
  cmd/upgrade/roles/cmd.go
  pkg/aws/client.go
  pkg/aws/client_mock.go
  pkg/aws/policies.go
  pkg/helper/roles/helpers.go
Labels: approved, lgtm

#2364 OCM-10506 | test: automated cases id:73638
  tests/e2e/hcp_machine_pool_test.go
Labels: approved, lgtm

#2357 OCM-10438 | ci: Enhance account-roles list due to a known issue
  tests/utils/profilehandler/data_preparation.go
Labels: approved, lgtm

#2365 OCM-10299 | ci: fix rosa-hcp-external-auth deploy failure
  tests/e2e/e2e_setup_test.go
Labels: approved, lgtm

#2368 OCM-10511 | fix: missing operator roles when filtering due to extended naming cutting the postfix
  pkg/aws/policies.go
  pkg/aws/policies_test.go
Labels: approved, lgtm

#2370 OCM-7551 | feat: add role console url in the output for policy attach
  pkg/aws/policies.go
Labels: approved, lgtm

#2367 OCM-10479 | ci: fix id:64187,67348
  tests/e2e/rosa_autoscaler_test.go
  tests/e2e/test_rosacli_upgrade.go
Labels: approved, lgtm

#2356 OCM-10455 | feat: Add a configuration for a custom user agent
  cmd/create/service/cmd.go
  cmd/rosa/main.go
  cmd/verify/rosa/cmd.go
  cmd/version/cmd_test.go
  cmd/version/options.go
  pkg/aws/client.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/info/info.go
  pkg/ocm/client.go
  pkg/ocm/clusters.go
  tests/e2e/test_rosacli_version.go
Labels: approved, lgtm

#2346 OCM-10375 | fix: update edit machinepool error message for missing identifier
  cmd/describe/upgrade/cmd.go
  cmd/dlt/upgrade/cmd.go
  cmd/edit/machinepool/cmd.go
  cmd/list/upgrade/cmd.go
  cmd/upgrade/machinepool/cmd.go
  pkg/machinepool/args.go
  pkg/machinepool/args_test.go
Labels: approved, lgtm

#2377 OCM-10450 | fix: Pass in OIDC Config ID when creating oidcprovider from create/oidcconfig
  cmd/create/oidcconfig/cmd.go
  cmd/create/oidcprovider/cmd.go
Labels: approved, lgtm

#2375 OCM-5445 | fix: Interactive installer inconsistency with choosing wrong subnets
  cmd/create/cluster/cmd.go
  pkg/interactive/validation.go
  pkg/interactive/validation_test.go
Labels: approved, lgtm

#2376 OCM-10460 | fix: don't overwrite existing autoscaler value in edit flow
  cmd/edit/autoscaler/autoscaler_suite_test.go
  cmd/edit/autoscaler/cmd.go
  cmd/edit/autoscaler/cmd_test.go
  cmd/edit/cmd.go
  pkg/clusterautoscaler/flags.go
  pkg/clusterautoscaler/flags_test.go
Labels: approved, lgtm

#2381 OCM-10452 | fix: Fix cluster creation with oidc provider
  cmd/create/cluster/cmd.go
  cmd/create/oidcconfig/cmd.go
Labels: approved, lgtm

#2369 OCM-10511 | fix: missing operator roles when filtering due to extended naming cutting the postfix
  pkg/aws/policies.go
  pkg/aws/policies_test.go
Labels: approved

#2383 OCM-10616 | feat: refactoring on autoscaler commands to use new runner
  cmd/create/autoscaler/autoscaler_suite_test.go
  cmd/create/autoscaler/cmd.go
  cmd/create/autoscaler/cmd_test.go
  cmd/create/cmd.go
  cmd/dlt/autoscaler/autoscaler_suite_test.go
  cmd/dlt/autoscaler/cmd.go
  cmd/dlt/autoscaler/cmd_test.go
  cmd/dlt/cmd.go
  cmd/edit/cmd.go
Labels: approved, lgtm

#2325 OCM-9805 | test: Automate id:60278 [Scaling up/down node pool on rosa hcp cluster]
  tests/e2e/hcp_machine_pool_test.go
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/utils.go
  tests/utils/common/constants/cluster.go
  tests/utils/config/cluster.go
  tests/utils/exec/rosacli/cluster_service.go
  tests/utils/exec/rosacli/machinepool_service.go
Labels: approved, lgtm

#2360 OCM-10477 | test: fix id:75210
  tests/e2e/test_rosacli_cluster_post.go
Labels: approved, lgtm

#2371 OCM-10532: Update staging qaprodauth console url for details page
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm, jira/valid-reference

#2382 OCM-9804 | fix: describe etcd KMS key when configure
  cmd/describe/cluster/cmd.go
  cmd/describe/cluster/cmd_test.go
Labels: approved, lgtm

#2385 OCM-10633 | test: fix id:73731
  tests/e2e/test_rosacli_upgrade.go
Labels: approved, lgtm

#2387 OCM-10452 | fix: Add cluster key back to oidcprovider create/cluster call
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#2366 OCM-10507 | ci: fix id:71050
  tests/e2e/hcp_cluster_test.go
Labels: approved, lgtm

#2374 OCM-10545 | test: fix id: 72162
  tests/e2e/test_rosacli_token.go
Labels: approved, lgtm

#2379 OCM-10606 | test: fix id:74402
  tests/e2e/test_rosacli_policy.go
Labels: approved, lgtm

#2373 OCM-10543 | test: fix ids: 75210,73731,57408,38770,74661,60688 some failures
  tests/e2e/test_rosacli_account_roles.go
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_operator_roles.go
  tests/e2e/test_rosacli_upgrade.go
  tests/utils/common/oidc.go
Labels: approved, lgtm

#2388 OCM-10467 | fix: don't allow cluster name longer than 15 characters when installed into shared vpc
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#2224 OCM 7186 - Adding Unit test coverage to Create Machinepool and Nodepool functions
  cmd/create/cmd.go
  cmd/create/idp/mocks/identityprovider.go
  cmd/create/machinepool/cmd.go
  cmd/create/machinepool/cmd_test.go
  cmd/create/machinepool/options.go
  cmd/create/machinepool/options_test.go
  cmd/create/machinepool/suite_test.go
  cmd/verify/rosa/cmd_mock.go
  pkg/cache/cache_mock.go
  pkg/cache/service_mock.go
  pkg/clients/http_mock.go
  pkg/kubeletconfig/capability_checker_mock.go
  pkg/machinepool/helper.go
  pkg/machinepool/helper_test.go
  pkg/machinepool/machine_pool_args.go
  pkg/machinepool/machinepool.go
  pkg/machinepool/machinepool_mock.go
  pkg/machinepool/machinepool_test.go
  pkg/options/machinepool/create.go
  pkg/options/machinepool/create_test.go
  pkg/options/machinepool/suit_test.go
  pkg/test/helpers.go
  pkg/version/retriever_mock.go
  pkg/version/version_mock.go
Labels: approved, lgtm

#2392 OCM-10676 | fix: Remove manual cluster ID flag update for create/oidcprovider
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#2394 OCM-10711 | test: fix ids:73449, 74403
  tests/e2e/test_rosacli_policy.go
Labels: approved, lgtm

#2397 OCM-10756 | fix: add missing aliases for describe/delete autoscaler commands
  cmd/describe/autoscaler/cmd.go
  cmd/dlt/autoscaler/cmd.go
Labels: approved, lgtm

#2398 OCM-10754 | fix: validate int32 for user input in autoscaler attributes
  pkg/clusterautoscaler/flags.go
  pkg/ocm/validators.go
  pkg/ocm/validators_test.go
Labels: approved, lgtm

#2399 OCM-10530 | test: automated cases id:75916
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2378 OCM-9784 | test: automate case id:72538
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2403 OCM-10779 | fix: Error when setting multi-az true for HCP
  pkg/machinepool/machinepool.go
Labels: approved, lgtm

#2400 OCM-10712 | tests: fix id:75210
  tests/e2e/test_rosacli_cluster_post.go
Labels: approved, lgtm
