Repository openshift/rosa, pull requests merged in 2024-10, with the labels that each got.

#2520 OCM-11556 | fix: remove multiple ca tests from getClusterRegistryConfig
  cmd/describe/cluster/cmd_test.go
Labels: lgtm

#2258 OCM-9613 | feat: Allow billing account update via the cluster edit command
  cmd/create/cluster/cmd.go
  cmd/create/cluster/cmd_test.go
  cmd/edit/cluster/cmd.go
  cmd/rosa/structure_test/command_args/rosa/edit/cluster/command_args.yml
  pkg/interactive/interactive.go
  pkg/ocm/billing.go
  pkg/ocm/clusters.go
Labels: approved, lgtm

#2521 OCM-11564 | feat: Add hunterkepley to approvers section
  OWNERS
Labels: approved, lgtm

#2478 OCM-6053 | feat: Day1 SG support for HCP
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#2508 OCM-11446 | feat: Add "rosa cli" to !latest error main.go
  cmd/rosa/main.go
Labels: approved, lgtm

#2522 OCM-11484 | fix: registry config allowed for import flag should not enable interactive mode
  cmd/edit/cluster/cmd.go
Labels: approved, lgtm

#2525 OCM-67348 | test: fix id:67348
  tests/e2e/rosa_autoscaler_test.go
Labels: approved, lgtm

#2519 OCM-11553 | ci: fix id:73754,63179,74430,72538,37177,62161,73018
  tests/e2e/hcp_external_auth_test.go
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_kubelet_config.go
  tests/e2e/test_rosacli_node_pool.go
  tests/e2e/test_rosacli_upgrade.go
Labels: approved, lgtm

#2526 OCM-11589 | ci: Revert 4.17 policy workaround
  tests/utils/profilehandler/data_preparation.go
  tests/utils/profilehandler/interface.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2517 OCM-7783 | feat: add rosa describe accessrequest command
  cmd/create/decision/cmd.go
  cmd/describe/accessrequest/accessrequest_suite_test.go
  cmd/describe/accessrequest/cmd.go
  cmd/describe/accessrequest/cmd_test.go
  cmd/describe/cmd.go
  cmd/rosa/structure_test/command_args/rosa/describe/accessrequest/command_args.yml
  cmd/rosa/structure_test/command_structure.yml
  pkg/ocm/accessrequests.go
  pkg/output/output.go
  pkg/test/helpers.go
Labels: approved, lgtm

#2518 OCM-11538 | feat: Adding rosa create network command
  cmd/create/cmd.go
  cmd/create/network/cmd.go
  cmd/create/network/cmd_test.go
  cmd/create/network/options.go
  cmd/create/network/options_test.go
  cmd/create/network/suite_test.go
  cmd/create/network/templates/rosa-quickstart-default-vpc/cloudformation.yaml
  cmd/rosa/structure_test/command_args/rosa/create/network/command_args.yml
  cmd/rosa/structure_test/command_structure.yml
  pkg/network/helper.go
  pkg/network/helper_test.go
  pkg/network/network.go
  pkg/network/network_mock.go
  pkg/network/network_test.go
  pkg/network/suite_test.go
  pkg/options/machinepool/suite_test.go
  pkg/options/network/create.go
  pkg/options/network/create_test.go
  pkg/options/network/suite_test.go
Labels: approved, lgtm

#2528 OCM-11611 | ci: Fix id:75525
  tests/e2e/test_rosacli_cluster_post.go
Labels: approved, lgtm

#2507 OCM-10279 | test: automate id:75534
  tests/e2e/hcp_cluster_test.go
Labels: approved, lgtm

#2529 OCM-11614 | ci: bump ocm-common to fix the image cannot find issue fr…
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/ram.go
  vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/role.go
  vendor/github.com/openshift-online/ocm-common/pkg/aws/consts/consts.go
  vendor/modules.txt
Labels: approved, lgtm

#2533 OCM-8739 | test: fix for cluster configure file error
  tests/e2e/hcp_cluster_test.go
  tests/e2e/hcp_machine_pool_test.go
  tests/e2e/rosa_autoscaler_test.go
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_cluster_post.go
  tests/e2e/test_rosacli_operator_roles.go
  tests/e2e/test_rosacli_upgrade.go
  tests/e2e/test_rosacli_version.go
Labels: approved, lgtm

#2534 OCM-11609 | test: updated id:68971,68172
  tests/ci/data/profiles/rosa-hcp.yaml
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_cluster_post.go
  tests/utils/exec/rosacli/cluster_service.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2514 OCM-9940 | test: automated id:34950 check available regions
  tests/e2e/test_rosacli_region.go
Labels: approved, lgtm

#2531 OCM-11560 | fix: allow trailing comma for taints/labels
  pkg/helper/machinepools/helpers.go
  pkg/helper/machinepools/helpers_test.go
Labels: approved

#2536 OCM-11707 | fix: Fixing typo
  pkg/options/network/create.go
Labels: approved, lgtm

#2537 OCM-11710 | ci: fix id:38770
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2524 OCM-11565 | fix: include zero egress status in cluster describe command
  cmd/describe/cluster/cmd.go
  cmd/describe/cluster/cmd_test.go
Labels: approved, lgtm

#2538 OCM-11045 | fix: etcd encryption describe should be shared between hcp and classic
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm

#2532 OCM-11496 | fix: Change language when updating cluster reg config
  pkg/clusterregistryconfig/flags.go
  pkg/clusterregistryconfig/flags_test.go
Labels: approved, lgtm

#2539 OCM-11711 | fix: Adding a default template if no template is specified
  cmd/create/network/cmd.go
  pkg/options/network/create.go
Labels: approved, lgtm

#2535 OCM-11559 | fix: first check if pool exists
  cmd/upgrade/machinepool/cmd.go
  cmd/upgrade/machinepool/cmd_test.go
Labels: approved, lgtm

#2541 OCM-11730 | ci: fix id:75534
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2523 OCM-11556 | fix: refactor multiple ca tests from getClusterRegistryConfig
  cmd/describe/cluster/cmd.go
  cmd/describe/cluster/cmd_test.go
Labels: approved, lgtm

#2546 OCM-6408 | fix: fix error in rosa init
  cmd/initialize/cmd.go
Labels: approved, lgtm

#2540 OCM-7782 | feat: support list access requests
  cmd/create/decision/cmd.go
  cmd/create/decision/cmd_test.go
  cmd/describe/accessrequest/cmd.go
  cmd/describe/accessrequest/cmd_test.go
  cmd/list/accessrequests/accessrequests_suite_test.go
  cmd/list/accessrequests/cmd.go
  cmd/list/accessrequests/cmd_test.go
  cmd/list/cmd.go
  cmd/rosa/structure_test/command_args/rosa/describe/access-request/command_args.yml
  cmd/rosa/structure_test/command_args/rosa/list/access-request/command_args.yml
  cmd/rosa/structure_test/command_structure.yml
  pkg/ocm/accessrequests.go
  pkg/output/output.go
  pkg/test/helpers.go
Labels: approved, lgtm

#2543 OCM-11732 | fix: AvailabilityZoneCount creates correct amount of resources
  cmd/create/network/templates/rosa-quickstart-default-vpc/cloudformation.yaml
Labels: approved, lgtm

#2549 OCM-11732 | fix: Reapplying tags
  cmd/create/network/templates/rosa-quickstart-default-vpc/cloudformation.yaml
Labels: approved, lgtm

#2552 OCM-11943 | chore: bump version to 1.2.47-RC1
  pkg/info/info.go
Labels: approved, lgtm

#2553 OCM-11943 | chore: Bump master to 1.2.48
  pkg/info/info.go
Labels: approved, lgtm

#2550 OCM-11480 | fix: not exit when user choosing N for registry config
  cmd/create/accountroles/creators_test.go
  cmd/edit/cluster/cmd.go
  cmd/edit/cluster/cmd_test.go
Labels: approved, lgtm

#2542 OCM-10874 | feat: validate role managed policies for cluster upgrade
  cmd/upgrade/cluster/cmd.go
  cmd/upgrade/operatorroles/cmd.go
  cmd/upgrade/roles/cmd.go
  pkg/helper/roles/helpers.go
  pkg/helper/roles/helpers_test.go
  pkg/ocm/helpers.go
  pkg/test/helpers.go
Labels: approved, lgtm

#2556 OCM-10017 | fix: revert adding EC2 policy to worker role
  pkg/aws/helpers.go
  pkg/aws/helpers_test.go
Labels: approved, lgtm

#2548 OCM-11868 | feat: Adding --template-dir flag & TEMPLATE_DIR env var
  cmd/create/network/cmd.go
  cmd/create/network/cmd_test.go
  cmd/login/cmd.go
  cmd/rosa/structure_test/command_args/rosa/create/network/command_args.yml
  pkg/aws/region/flag.go
  pkg/config/config.go
  pkg/constants/config.go
  pkg/network/helper.go
  pkg/network/helper_test.go
  pkg/options/network/create.go
  pkg/options/network/create_test.go
  pkg/options/network/suite_test.go
Labels: approved, lgtm

#2555 OCM-9310|ci: automated id:75921,75922
  tests/e2e/hcp_cluster_test.go
  tests/utils/constants/general.go
Labels: approved, lgtm

#2530 OCM-9183 | test: Get kubeconfig from env
  tests/ci/config/config.go
  tests/e2e/dummy_test.go
  tests/e2e/e2e_setup_test.go
  tests/utils/config/support.go
  tests/utils/exec/occli/cmd_client.go
Labels: approved, lgtm

#2560 OCM-10805 | test: automated ids:76394,76395
  tests/ci/data/profiles/rosa-hcp.yaml
  tests/e2e/hcp_cluster_test.go
  tests/utils/config/cluster.go
  tests/utils/exec/rosacli/cluster_service.go
  tests/utils/helper/certificate.go
  tests/utils/profilehandler/interface.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2564 OCM-12100 | fix: Only run oidcprovider command when mode=auto
  cmd/create/oidcconfig/cmd.go
Labels: approved, lgtm

#2566 OCM-12101 | fix: Adding log outputs for empty values
  cmd/create/network/cmd.go
Labels: approved, lgtm

#2574 OCM-11969 | fix: Rearranging creation order to fix endpoint issue
  cmd/create/network/templates/rosa-quickstart-default-vpc/cloudformation.yaml
Labels: approved, lgtm

#2575 OCM-12100 | fix: Exit with status 0
  cmd/create/oidcconfig/cmd.go
Labels: approved, lgtm

#2580 OCM-12118 | fix: Ask for oidc config ID for register/oidcconfig
  cmd/register/oidcconfig/cmd.go
  pkg/constants/oidc_config.go
Labels: approved, lgtm

#2581 OCM-12119 | fix: Env var regression with create/network
  cmd/create/network/cmd.go
  cmd/create/network/options.go
  pkg/options/network/create.go
  pkg/options/network/create_test.go
Labels: approved, lgtm

#2584 OCM-11943 | chore: Bump RC from 2 -> 3
  pkg/info/info.go
Labels: approved

#2585 OCM-12179 | feat: adding dmoskale to rosa cli approvers
  OWNERS
Labels: approved, lgtm

#2586 OCM-11578 | fix: skip validation of container registry policy for create cluster
  pkg/aws/policies.go
  pkg/aws/policies_test.go
Labels: approved, lgtm

#2587 OCM-11675 | ci: Expose some of the cluster configurations for profile override
  tests/ci/config/config.go
  tests/utils/helper/string.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2561 OCM-12036 | test: automated ids:38827,38829,35894,55701
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_cluster_post.go
  tests/e2e/test_rosacli_upgrade.go
  tests/utils/exec/rosacli/upgrade_service.go
Labels: approved, lgtm
