Repository openshift/rosa, pull requests merged in 2024-05, with the labels that each got.

#1990 OCM-7673 | fix: Provide the default value to the external auth
  pkg/externalauthprovider/flags.go
Labels: approved, lgtm

#1991 OCM-7729 | fix: check policy attached in detach manual mode
  cmd/detach/policy/cmd.go
  pkg/aws/client.go
  pkg/aws/mock_client.go
  pkg/aws/policies.go
  pkg/policy/policy_service.go
  pkg/policy/policy_service_test.go
Labels: approved, lgtm

#1989 OCM-6391 | fix: Add final disablement on final command in create cluster for region flag
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1987 OCM-4460 | test: automate id:OCP-73018 validations for breakglasscred
  tests/e2e/hcp_external_auth_test.go
Labels: approved, lgtm

#1995 prevents overwriting the client id if set for fedramp with keycloak
  cmd/login/cmd.go
Labels: approved, lgtm

#1992 OCM-6391 | fix: Add region deprecation disablement to sub-commands
  cmd/create/cluster/cmd.go
  cmd/create/ocmrole/cmd.go
  cmd/create/oidcconfig/cmd.go
  cmd/create/userrole/cmd.go
  cmd/dlt/cluster/cmd.go
  cmd/dlt/ocmrole/cmd.go
  cmd/dlt/oidcconfig/cmd.go
  cmd/dlt/userrole/cmd.go
  cmd/register/oidcconfig/cmd.go
  cmd/upgrade/cluster/cmd.go
  pkg/arguments/arguments.go
Labels: approved, lgtm

#1996 OCM-7738 | ci: Enhance the output of rosacli e2e testing
  tests/e2e/dummy_test.go
  tests/utils/exec/rosacli/cmd_client.go
  tests/utils/exec/rosacli/cmd_runner.go
  tests/utils/log/constants.go
  tests/utils/log/logger.go
Labels: approved, lgtm

#2000 OCM-7537 | ci: fix 45161,49137,66362,36128,43046
  go.mod
  tests/e2e/test_rosacli_network_verifier.go
  tests/e2e/test_rosacli_oidc_provider.go
  tests/e2e/test_rosacli_user.go
  tests/utils/common/idp.go
  tests/utils/config/cluster_command.go
Labels: approved, lgtm

#2002 OCM-6391 | fix: Remove duplicate oidcprovider cmd call
  cmd/create/cmd.go
Labels: approved, lgtm

#1964 OCM-7256 | feat: Move non-cmd funcs to pkg, split, test
  cmd/describe/machinepool/cmd.go
  cmd/list/machinepool/cmd.go
  cmd/list/machinepool/machinepool.go
  cmd/list/machinepool/nodepool.go
  pkg/machinepool/machinepool.go
  pkg/machinepool/machinepool_test.go
Labels: approved, lgtm

#1999 OCM-5576 | fix: Edit autoscaling max replicas of nodepool force to s…
  cmd/edit/machinepool/nodepool.go
  cmd/edit/machinepool/nodepool_test.go
Labels: approved, lgtm

#2003 OCM-7526 | fix: Display min/max in describe machinepool
  pkg/machinepool/output_test.go
  pkg/ocm/output/nodepools.go
Labels: approved, lgtm

#2004 OCM-7870 | fix: Display external-auth-providers-enabled flag
  cmd/create/cluster/cmd.go
  cmd/create/cluster/cmd_test.go
Labels: approved, lgtm

#2005 OCM-5085 | fix: lower mapAZcreated to 1
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#2014 OCM-7925 | ci: Fix ingress list result cannot be reflect issue
  tests/e2e/dummy_test.go
  tests/utils/exec/rosacli/ingress_service.go
Labels: approved, lgtm

#1966 OCM-7415 | feat: Ensure account roles have expected attached policies
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/roles/cmd.go
  pkg/aws/client.go
  pkg/aws/commandbuilder/helper/roles/roles.go
  pkg/aws/mock_client.go
  pkg/aws/policies.go
  pkg/helper/rolepolicybindings/helpers.go
  pkg/helper/rolepolicybindings/helpers_test.go
  pkg/ocm/rolepolicybinding.go
Labels: approved, lgtm

#2018 OCM-7801 | ci: Remove redundant cleaner to fix resource clean issue
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_idp.go
Labels: approved, lgtm

#2020 OCM-7927 | ci: Generate the junit file for report portal
  tests/ci/labels/runtime.go
  tests/e2e/e2e_report.go
  tests/utils/exec/rosacli/report_portal.go
Labels: approved, lgtm

#2021 OCM-7902 | ci: Bump ocm-common to support intellegient proxy
  go.mod
  go.sum
  tests/ci/config/config.go
  tests/ci/data/profiles/rosa-classic.yaml
  tests/e2e/dummy_test.go
  tests/utils/profilehandler/data_preparation.go
  tests/utils/profilehandler/profile_handler.go
  vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/image.go
  vendor/github.com/openshift-online/ocm-common/pkg/aws/consts/consts.go
  vendor/github.com/openshift-online/ocm-common/pkg/file/file.go
  vendor/github.com/openshift-online/ocm-common/pkg/test/vpc_client/bastion.go
  vendor/github.com/openshift-online/ocm-common/pkg/test/vpc_client/instance.go
  vendor/github.com/openshift-online/ocm-common/pkg/test/vpc_client/key_pair.go
  vendor/github.com/openshift-online/ocm-common/pkg/test/vpc_client/proxy.go
  vendor/modules.txt
Labels: approved, lgtm

#2017 OCM-7169 | fix: warn revoked break glass credential
  cmd/describe/breakglasscredential/cmd.go
  cmd/describe/breakglasscredential/cmd_test.go
Labels: approved, lgtm

#2023 OCM-7956 | ci: Added exclude label for tc-id OCP-60202
  tests/e2e/test_rosacli_iam_roles.go
  tests/e2e/test_rosacli_node_pool.go
Labels: approved, lgtm

#2025 OCM-7263 | chore: Updated OCM SDK to v0.1.419
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/hcp_kubelet_config_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/hcp_kubelet_config_resource_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/kubelet_config_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/kubelet_config_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/kubelet_config_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/kubelet_configs_client.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/kubelet_configs_resource_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/node_pool_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/node_pool_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/node_pool_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/metrics/path_tree_data.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm

#2013 OCM-7257 | feat: Refactor list machine pool cmd to use new default runner
  cmd/describe/machinepool/cmd.go
  cmd/list/cmd.go
  cmd/list/machinepool/cmd.go
  cmd/list/machinepool/cmd_test.go
  cmd/list/machinepool/main_test.go
Labels: approved, lgtm

#2015 OCM-7880 | ci: Automate cases 65799 and 64767
  tests/e2e/test_rosacli_ingress.go
  tests/utils/exec/rosacli/ingress_service.go
Labels: approved, lgtm

#2028 OCM-7937 | fix: allow 0 min replicas for classic cluster autoscaling mp
  cmd/edit/machinepool/machinepool.go
  cmd/edit/machinepool/machinepool_test.go
Labels: approved

#2029 OCM-7269 | feat: Added list of kubeletconfigs to describe HCP machinepool output
  cmd/describe/machinepool/cmd_test.go
  pkg/machinepool/output.go
  pkg/machinepool/output_test.go
  pkg/ocm/output/nodepools.go
Labels: approved, lgtm

#2027 OCM-7263 | feat: Add the ability to list KubeletConfigs for a cluster
  cmd/list/cmd.go
  cmd/list/kubeletconfig/cmd.go
  cmd/list/kubeletconfig/cmd_suite_test.go
  cmd/list/kubeletconfig/cmd_test.go
  pkg/kubeletconfig/output.go
  pkg/kubeletconfig/output_test.go
  pkg/ocm/kubeletconfig.go
  pkg/ocm/kubeletconfig_test.go
  pkg/output/output.go
  pkg/test/helpers.go
Labels: approved, lgtm

#2031 OCM-7927 | fix: Get the orgin junit file from ArtifactDir
  tests/utils/exec/rosacli/report_portal.go
Labels: approved, lgtm

#2032 OCM-7958 | ci: Update readme for tests folder
  tests/README.md
  tests/ci/data/profiles/rosa-classic.yaml
Labels: approved, lgtm

#1954 OCM-6318 | ci: Build up deprovision step
  tests/e2e/e2e_tear_down_test.go
  tests/utils/exec/rosacli/cluster_service.go
  tests/utils/profilehandler/data_cleaner.go
  tests/utils/profilehandler/parse_info.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2016 OCM-7924 | fix: list machinepool should show inline
  cmd/list/machinepool/cmd_test.go
  pkg/machinepool/machinepool.go
  pkg/ocm/output/nodepools.go
  pkg/ocm/output/nodepools_test.go
  pkg/ocm/output/output_test.go
Labels: approved, lgtm

#2036 OCM-7265 | feat: Added the ability to edit KubeletConfigs for HCP clusters
  cmd/create/kubeletconfig/cmd.go
  cmd/describe/kubeletconfig/cmd.go
  cmd/edit/cmd.go
  cmd/edit/kubeletconfig/cmd.go
  cmd/edit/kubeletconfig/cmd_test.go
  cmd/edit/kubeletconfig/kubeletconfig_suite_test.go
  pkg/kubeletconfig/config.go
  pkg/kubeletconfig/consts.go
  pkg/kubeletconfig/options.go
  pkg/kubeletconfig/options_test.go
  pkg/ocm/kubeletconfig.go
  pkg/ocm/kubeletconfig_test.go
Labels: approved, lgtm

#2012 OCM-6569 | fix: print role arn for hcp
  pkg/ocm/helpers.go
  pkg/ocm/helpers_test.go
Labels: approved, lgtm

#2040 OCM-7990 | fix: allow min_replicas 0 with edit machinepools
  cmd/edit/machinepool/machinepool.go
  cmd/edit/machinepool/machinepool_test.go
Labels: approved, lgtm

#2038 OCM-7266 | feat: Added support for delete of KubeletConfig for HCP clusters
  cmd/create/kubeletconfig/cmd.go
  cmd/dlt/cmd.go
  cmd/dlt/kubeletconfig/cmd.go
  cmd/dlt/kubeletconfig/cmd_test.go
  cmd/dlt/kubeletconfig/kubeletconfig_suite_test.go
  cmd/edit/kubeletconfig/cmd.go
  pkg/kubeletconfig/input.go
  pkg/kubeletconfig/input_test.go
  pkg/kubeletconfig/options.go
  pkg/kubeletconfig/options_test.go
  pkg/ocm/kubeletconfig.go
  pkg/ocm/kubeletconfig_test.go
Labels: approved, lgtm

#2042 OCM-8012 | docs: Add presubmit readme for rosa CLI testing
  tests/README.md
Labels: approved, lgtm

#2046 OCM-7264 | fix: Ensured that name is optional when creating a KubeletConfig
  pkg/ocm/kubeletconfig.go
  pkg/ocm/kubeletconfig_test.go
Labels: approved, lgtm

#2037 OCM-7860 | fix: add detach commands for arbitrary policies
  cmd/dlt/accountroles/cmd.go
  cmd/dlt/operatorrole/cmd.go
  pkg/aws/client.go
  pkg/aws/mock_client.go
  pkg/aws/policies.go
  pkg/aws/policies_test.go
Labels: approved, lgtm

#2045 OCM-7268 | feat: Update create machinepool command to support kubeletconfigs
  cmd/create/machinepool/cmd.go
  cmd/create/machinepool/nodepool.go
  pkg/ocm/kubeletconfig.go
  pkg/ocm/kubeletconfig_test.go
Labels: approved, lgtm

#2047 OCM-8020 | feat: Update rosa edit machinepool command for kubeletconfig support
  cmd/edit/machinepool/cmd.go
  cmd/edit/machinepool/nodepool.go
Labels: approved, lgtm

#2044 OCM-7267 | feat: Added ability to describe Kubeletconfigs for HCP clusters
  cmd/create/kubeletconfig/cmd.go
  cmd/describe/cmd.go
  cmd/describe/kubeletconfig/cmd.go
  cmd/describe/kubeletconfig/cmd_test.go
  cmd/describe/kubeletconfig/kubeletconfig_suite_test.go
  cmd/dlt/kubeletconfig/cmd.go
  cmd/edit/kubeletconfig/cmd.go
  pkg/interactive/flag.go
  pkg/kubeletconfig/config.go
  pkg/kubeletconfig/consts.go
  pkg/kubeletconfig/output.go
  pkg/kubeletconfig/output_test.go
  pkg/ocm/nodepools.go
  pkg/test/helpers.go
Labels: approved, lgtm

#2039 OCM-7258 | feat: Move delete machinepool/nodepool funcs to pkg
  cmd/dlt/machinepool/cmd.go
  cmd/dlt/machinepool/machinepool.go
  cmd/dlt/machinepool/nodepool.go
  pkg/machinepool/machinepool.go
  pkg/machinepool/machinepool_test.go
Labels: lgtm

#2035 OCM-6729 | test: automate id:OCP-73492 create/describe nodepool with tags
  tests/e2e/test_rosacli_node_pool.go
  tests/utils/common/string.go
  tests/utils/exec/rosacli/machinepool_service.go
  tests/utils/exec/rosacli/ocm_resource_service.go
Labels: approved, lgtm

#2024 SDA-4329 | feat: Validation for user creating account-roles
  tests/e2e/test_rosacli_iam_roles.go
Labels: approved, lgtm

#1997 Add support for ListInstanceTypes method
  tests/e2e/test_rosacli_machine_pool.go
  tests/utils/exec/rosacli/ocm_resource_service.go
Labels: approved, lgtm

#2050 OCM-7263 | chore: Added additional aliases to the `rosa list kubeletconfig` command
  cmd/list/kubeletconfig/cmd.go
  cmd/list/kubeletconfig/cmd_test.go
Labels: approved, lgtm

#2048 OCM-7993 | test: Automated id:38835 List/Edit the default ingress on ROSA cluster via rosa-cli will succeed
  tests/e2e/test_rosacli_ingress.go
  tests/utils/common/string.go
Labels: approved, lgtm

#2026 OCM-7960 | ci: Automated id:38770,38778,72162,46187,45176,44511
  tests/ci/labels/features.go
  tests/ci/labels/runtime.go
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_iam_roles.go
  tests/e2e/test_rosacli_token.go
  tests/utils/config/cluster_command.go
  tests/utils/exec/rosacli/cmd_runner.go
  tests/utils/exec/rosacli/ocm_resource_service.go
  tests/utils/profilehandler/parse_yaml.go
Labels: approved, lgtm

#2055 OCM-8054 | fix: add region parameters for deleting oidc config command
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2049 OCM-4458 | test: automate id:71946 validation for create/list/delete idp and admin for exteranl auth cluster
  tests/e2e/hcp_external_auth_test.go
Labels: approved, lgtm

#2056 OCM-8045 | test: Automated cases id:73753,73754 for kubeletconfig porting on HCP
  tests/e2e/test_rosacli_ingress.go
  tests/e2e/test_rosacli_kubelet_config.go
  tests/utils/exec/rosacli/kubelet_config_service.go
Labels: approved, lgtm

#2057 OCM-8058 | fix: Ensure --name option is required for working with KubeletConfigs on HCP clusters
  cmd/create/kubeletconfig/cmd.go
  cmd/create/kubeletconfig/cmd_test.go
  cmd/describe/kubeletconfig/cmd.go
  cmd/describe/kubeletconfig/cmd_test.go
  cmd/dlt/kubeletconfig/cmd.go
  cmd/dlt/kubeletconfig/cmd_test.go
  cmd/edit/kubeletconfig/cmd.go
  cmd/edit/kubeletconfig/cmd_test.go
  pkg/kubeletconfig/config.go
  pkg/kubeletconfig/consts.go
Labels: approved, lgtm

#2058 OCM-8057 | fix: Ensure the ID of the KubeletConfig is printed by `rosa describe kubeletconfig`
  pkg/kubeletconfig/output.go
  pkg/kubeletconfig/output_test.go
Labels: approved, lgtm

#2060 OCM-8082 | fix: Ensure --kubelet-configs flag is not supported for ROSA Classic MachinePools
  cmd/create/machinepool/machinepool.go
  cmd/edit/machinepool/machinepool.go
Labels: approved, lgtm

#2061 OCM-8075 | fix: Ensure users can only supply a single kubeletconfig for HCP MachinePools
  cmd/create/machinepool/cmd.go
  cmd/create/machinepool/nodepool.go
  cmd/edit/machinepool/cmd.go
  cmd/edit/machinepool/nodepool.go
  pkg/machinepool/validation.go
  pkg/machinepool/validation_test.go
Labels: approved, lgtm

#2062 OCM-8076 | fix: Ensure the user is prompted if they change the kubeletconfig on their HCP MachinePool
  cmd/edit/machinepool/nodepool.go
  cmd/edit/machinepool/nodepool_test.go
  pkg/kubeletconfig/input.go
Labels: approved, lgtm

#2063 OCM-8055 | fix: Check kubeletconfig exists by name if user specifies it for Classic cluster
  cmd/describe/kubeletconfig/cmd.go
  cmd/describe/kubeletconfig/cmd_test.go
  cmd/dlt/kubeletconfig/cmd.go
  cmd/edit/kubeletconfig/cmd.go
  cmd/edit/kubeletconfig/cmd_test.go
Labels: approved, lgtm

#2064 OCM-7855 | fix: return message if there is no breakglass can be revoked
  cmd/revoke/breakglasscredential/breakglasscredential_suite_test.go
  cmd/revoke/breakglasscredential/cmd.go
  cmd/revoke/breakglasscredential/cmd_test.go
Labels: approved, lgtm

#2067 OCM-8059 | fix: Allow users to use positional args for specifying the name of kubeletconfig
  cmd/create/kubeletconfig/cmd.go
  cmd/describe/kubeletconfig/cmd.go
  cmd/dlt/kubeletconfig/cmd.go
  cmd/edit/kubeletconfig/cmd.go
  pkg/kubeletconfig/options.go
  pkg/kubeletconfig/options_test.go
Labels: approved, lgtm

#2069 OCM-8121 | fix: Show correct describe message for expired breakglass
  cmd/describe/breakglasscredential/cmd.go
  cmd/describe/breakglasscredential/cmd_test.go
Labels: approved, lgtm

#2071 OCM-8133 | ci: Update readme for test folder of how to destroy resources
  tests/README.md
Labels: approved, lgtm

#1988 Enable releases via goreleaser
  .bingo/Variables.mk
  .bingo/goreleaser.mod
  .bingo/goreleaser.sum
  .bingo/variables.env
  .gitignore
  .goreleaser.yaml
  Makefile
  cmd/create/idp/cmd.go
  cmd/create/idp/mocks/identityprovider.go
  hack/README.md
  hack/release-build.sh
  hack/release-generate-changelog.sh
  pkg/aws/client_mock.go
  pkg/aws/mocks/cloudformation_api_client_mock.go
  pkg/aws/mocks/ec2_api_client_mock.go
  pkg/aws/mocks/iam_api_client_mock.go
  pkg/aws/mocks/organizations_api_client_mock.go
  pkg/aws/mocks/s3_api_client_mock.go
  pkg/aws/mocks/secretsmanager_api_client_mock.go
  pkg/aws/mocks/servicequotas_api_client_mock.go
  pkg/aws/mocks/sts_api_client_mock.go
  pkg/kubeletconfig/capability_checker_mock.go
  pkg/machinepool/machinepool.go
  pkg/machinepool/machinepool_mock.go
Labels: approved, lgtm

#2070 OCM-6569 | fix: Hide the duplicate output of operator roles
  cmd/create/cluster/cmd.go
  cmd/create/operatorroles/by_clusterkey.go
  cmd/create/operatorroles/by_prefix.go
  pkg/ocm/helpers.go
Labels: approved, lgtm

#2073 OCM-6900 | chore: bump version to 1.2.41
  pkg/info/info.go
Labels: approved

#2059 OCM-8045 | test: automated ids:73765,73766 to support machinepool with kubeletconfig
  tests/e2e/test_rosacli_kubelet_config.go
  tests/e2e/test_rosacli_node_pool.go
  tests/utils/exec/rosacli/machinepool_service.go
Labels: approved, lgtm

#2074 SDA-7166 | test: automate id:56782 removed validation checkpoint
  tests/e2e/test_rosacli_node_pool.go
Labels: approved, lgtm

#2052 OCM-7985 | fix: add attach policy command for rosa upgrade roles
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/roles/cmd.go
  pkg/aws/commandbuilder/helper/roles/roles.go
  pkg/aws/sts.go
Labels: approved, lgtm

#2078 OCM-8080 | fix: fix problem in delete operator roles manual mode
  cmd/dlt/operatorrole/cmd.go
Labels: approved, lgtm

#2066 SDA-4924 | test: automated id:53031 Validation for Create/Delete the …
  tests/e2e/test_rosacli_idp.go
Labels: approved, lgtm

#2081 OCM-8186 | test: fixed id:68835,68836 for kubeletconfig testing on classic
  tests/e2e/test_rosacli_kubelet_config.go
Labels: approved, lgtm

#2077 OCM-8153 | ci: fix rosa-hcp-external-auth profile cluster preparation failure
  tests/ci/data/profiles/rosa-hcp.yaml
Labels: approved, lgtm

#2087 OCM-8165 | fix: Only list kubeletconfigs when absolutely necessary when creating a machinepool
  cmd/create/machinepool/nodepool.go
Labels: approved, lgtm

#2083 OCM-3701 | feat: Remove version from editing machinepool
  cmd/edit/machinepool/cmd.go
  cmd/edit/machinepool/machinepool.go
  cmd/edit/machinepool/nodepool.go
  cmd/edit/machinepool/nodepool_test.go
Labels: approved, lgtm

#2092 OCM-6544 | feat: display attached policies for sts roles
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm

#2053 OCM-8053 | test: Automated id:43252 validating inputs for creating spot machinepools
  tests/e2e/test_rosacli_machine_pool.go
Labels: approved, lgtm

#2088 OCM-8221 | test: fixed id:43067,70859,45161,43070,61322 and enhanceme…
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_iam_roles.go
  tests/utils/exec/rosacli/version_service.go
Labels: approved, lgtm

#2082 OCM-8142 | test: Fix the rosa-private-link and rosa-non-sts-advanced creation issue
  tests/ci/data/profiles/rosa-classic.yaml
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2051 OCM-7488 | test: Automated id:73743 checking rosa version while logged out
  tests/ci/labels/features.go
  tests/e2e/test_rosacli_version.go
  tests/utils/common/file.go
  tests/utils/exec/rosacli/cmd_runner.go
Labels: approved, lgtm

#2095 OCM-8198 | fix: always add attach command for managed policy during r…
  cmd/upgrade/roles/cmd.go
  pkg/aws/commandbuilder/helper/roles/roles.go
Labels: approved, lgtm

#2084 OCM-8136 | fix: Delete should exit 1 if fails
  cmd/describe/breakglasscredential/cmd_test.go
  cmd/dlt/machinepool/cmd.go
Labels: approved, lgtm

#2097 OCM-8202 | fix: remove redudant empty lines in manual mode
  cmd/dlt/operatorrole/cmd.go
Labels: lgtm

#2054 OCM-7259 | feat: E2E delete machinepool cmd tests; new runner
  cmd/describe/machinepool/cmd.go
  cmd/describe/machinepool/cmd_test.go
  cmd/describe/machinepool/options.go
  cmd/describe/machinepool/options_test.go
  cmd/dlt/cmd.go
  cmd/dlt/machinepool/cmd.go
  cmd/dlt/machinepool/cmd_test.go
  cmd/dlt/machinepool/main_test.go
  cmd/dlt/machinepool/options.go
  cmd/dlt/machinepool/options_test.go
Labels: approved, lgtm

#2099 OCM-8276 | fix: don't show empty lines when filtering version on acc roles
  pkg/aws/policies.go
  pkg/aws/policies_test.go
Labels: approved

#2091 OCM-8072 | test: automated ids:60082,42188
  tests/e2e/dummy_test.go
  tests/e2e/test_rosacli_verify.go
Labels: approved, lgtm

#2096 OCM-8257 | ci: Split creation out and split cluster waiting out and make autoscaler value to 10
  tests/ci/config/config.go
  tests/e2e/e2e_setup_test.go
  tests/utils/exec/rosacli/cmd_runner.go
  tests/utils/log/logger.go
  tests/utils/profilehandler/data_preparation.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2100 OCM-8290 | ci: Fix 61139,73743,53031
  tests/e2e/test_rosacli_idp.go
  tests/e2e/test_rosacli_node_pool.go
  tests/e2e/test_rosacli_version.go
Labels: approved, lgtm

#2068 OCM-4458 | test: automate id:73755 validation for create cluster with external_auth_config
  tests/e2e/hcp_external_auth_test.go
Labels: approved, lgtm

#2101 SDA-4924 | fix: error message for invalid username validation for idp creation
  tests/e2e/test_rosacli_idp.go
Labels: approved, lgtm

#2086 OCM-8187 | test: Automated case id:56440 validations for the '--tags'
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2102 OCM-8283 | fix: kubelet-config edit prompt no longer shows up when kubelet-configs are not targeted
  cmd/edit/machinepool/nodepool.go
Labels: approved, lgtm

#2103 OCM-5530 | test: automate id:73725,73814 validation of network type for hcp cluster creation
  tests/e2e/test_rosacli_cluster.go
  tests/utils/exec/rosacli/cluster_service.go
Labels: approved, lgtm

#2108 OCM-8336 | fix: only check redhat managed policies when upgrade roles
  pkg/aws/policies.go
Labels: approved, lgtm

#2072 OCM-8134 | test: automated id:71945,64491,60083,71050
  tests/e2e/e2e_pre_check_test.go
  tests/e2e/hcp_cluster_test.go
  tests/utils/config/cluster.go
  tests/utils/exec/rosacli/pr_check.go
  tests/utils/profilehandler/data_preparation.go
  tests/utils/profilehandler/interface.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2111 OCM-8352 | fix: use aws default http client
  pkg/aws/client.go
Labels: approved, lgtm

#2105 OCM-8129 | fix: hide unnecessary kubeconfig info
  cmd/describe/breakglasscredential/cmd.go
  cmd/describe/breakglasscredential/cmd_test.go
Labels: approved, lgtm

#2112 OCM-8330 | fix: Fix delete oidc provider failed
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2115 OCM-8332 | test: automated id:68751
  tests/e2e/test_rosacli_network_verifier.go
Labels: approved, lgtm

#1998 OCM-7647 | test: automate id:OCP-72899 Updated the checkpoints for tc
  tests/e2e/hcp_external_auth_test.go
  tests/utils/exec/rosacli/break_glass_credential_service.go
Labels: approved, lgtm

#2119 OCM-8388 | ci: Remove `FeatureNodePool` label
  tests/ci/labels/features.go
  tests/e2e/test_rosacli_node_pool.go
Labels: approved, lgtm

#2120 OCM-8072 | test: fixing id:60082,42188 ci failures
  tests/e2e/test_rosacli_verify.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2123 OCM-8419 | test: Automate case id: OCP-52692 Validation for availability zones
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2126 OCM-8435 | chore: bump gci version to correctly handle newer golang versions
  .bingo/Variables.mk
  .bingo/gci.mod
  .bingo/gci.sum
  .bingo/variables.env
  cmd/attach/policy/cmd.go
  cmd/detach/policy/cmd.go
  cmd/edit/machinepool/nodepool.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/helper/rolepolicybindings/helpers.go
  pkg/ocm/kubeletconfig_test.go
  pkg/policy/policy_service.go
  pkg/version/version.go
Labels: approved, lgtm
