Repository openshift/rosa, pull requests merged in 2024-06, with the labels that each got.

#2114 OCM-8299 | fix: id:53031 update the error message
  tests/e2e/test_rosacli_idp.go
Labels: approved, lgtm

#2125 OCM-4459 | test: automate id:72536 create/list/describe/delete external_auth_provider for hcp cluster
  tests/e2e/hcp_external_auth_test.go
  tests/utils/exec/rosacli/cmd_client.go
  tests/utils/exec/rosacli/external_auth_provider_service.go
Labels: approved, lgtm

#2127 OCM-8418 | test: apply the automation labels on testing
  tests/ci/labels/category.go
  tests/ci/labels/features.go
  tests/ci/labels/importance.go
  tests/ci/labels/misc.go
  tests/ci/labels/runtime.go
  tests/e2e/e2e_pre_check.go
  tests/e2e/e2e_setup_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/e2e_tear_down_test.go
  tests/e2e/hcp_cluster_test.go
  tests/e2e/hcp_external_auth_test.go
  tests/e2e/hcp_machine_pool_test.go
  tests/e2e/hcp_tuning_config_test.go
  tests/e2e/test_rosacli_account_roles.go
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_cluster_post.go
  tests/e2e/test_rosacli_iam_roles.go
  tests/e2e/test_rosacli_idp.go
  tests/e2e/test_rosacli_idp_user.go
  tests/e2e/test_rosacli_ingress.go
  tests/e2e/test_rosacli_kubelet_config.go
  tests/e2e/test_rosacli_machine_pool.go
  tests/e2e/test_rosacli_network_verifier.go
  tests/e2e/test_rosacli_node_pool.go
  tests/e2e/test_rosacli_ocm_role.go
  tests/e2e/test_rosacli_oidc_config.go
  tests/e2e/test_rosacli_oidc_provider.go
  tests/e2e/test_rosacli_operator_roles.go
  tests/e2e/test_rosacli_region.go
  tests/e2e/test_rosacli_token.go
  tests/e2e/test_rosacli_user_role.go
  tests/e2e/test_rosacli_version.go
  tests/e2e/utils.go
Labels: approved, lgtm

#2128 OCM-6706 | ci: Use CLI logger
  tests/README.md
  tests/e2e/dummy_test.go
  tests/e2e/e2e_tear_down_test.go
  tests/utils/log/constants.go
  tests/utils/log/logger.go
  tests/utils/log/sensitive_hook.go
Labels: approved, lgtm

#2129 OCM-8145 | test: Fix the non-oidc cluster preparation issue due to parser error
  tests/utils/exec/rosacli/cluster_service.go
  tests/utils/exec/rosacli/version_service.go
  tests/utils/profilehandler/data_preparation.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2130 OCM-8440 | ci: add a customized profile rosa-hcp-pl-kms-proxy for MCS support team
  tests/ci/data/profiles/external.yaml
Labels: approved, lgtm

#2132 SDA-2922 | test: fixing id:35878 ci failures
  tests/e2e/test_rosacli_idp.go
Labels: approved, lgtm

#2134 OCM-8145 | test: Fix account role path in profile
  tests/ci/data/profiles/rosa-hcp.yaml
Labels: approved, lgtm

#2135 SDA-3007 | test: fixing id:38838 ci failures
  tests/e2e/test_rosacli_machine_pool.go
Labels: approved, lgtm

#2136 OCM-8418 | test: update readme.md according to the latest label change
  tests/README.md
  tests/ci/labels/runtime.go
  tests/e2e/e2e_setup_test.go
Labels: approved, lgtm

#2133 OCM-8466 | ci: Fix classic checks
  tests/e2e/test_rosacli_kubelet_config.go
Labels: approved, lgtm

#2124 OCM-8337 | fix: [HCP] always set replicas when updating machinepools
  cmd/edit/machinepool/nodepool.go
  cmd/edit/machinepool/nodepool_test.go
Labels: approved, lgtm

#2141 OCM-8530 | ci: Fix readme typo error
  tests/README.md
Labels: approved, lgtm

#2137 OCM-8418 | test: update readme for automation labels usage
  tests/README.md
  tests/ci/labels/features.go
  tests/ci/labels/labels.md
  tests/ci/labels/runtime.go
Labels: approved, lgtm

#2146 OCM-7828 | chore: update download name for image testing pipeline
  images/Dockerfile.release
Labels: approved, lgtm

#2147 OCM-8623 | test: fixed id:73753,45161 in HCP pipeline
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_kubelet_config.go
  tests/utils/config/cluster.go
Labels: approved, lgtm

#2104 OCM-7871 | fix: Mandatory fields should enter interactive mode if not provided
  cmd/create/externalauthprovider/cmd_test.go
  cmd/create/externalauthprovider/externalauthprovider_suite_test.go
  pkg/externalauthprovider/flags.go
Labels: approved, lgtm

#2109 OCM-7587 | feat: removing interactive mode as default for prefix prompt
  cmd/list/operatorroles/cmd.go
Labels: approved, lgtm

#2116 OCM-8390 | test: automate id:38788 [rosacli] Validation for IDP creation commands
  tests/e2e/test_rosacli_idp.go
Labels: approved, lgtm

#2144 OCM-8587 | fix: colon not present in some field for describing autoscaler to a cluster
  pkg/clusterautoscaler/output.go
  pkg/clusterautoscaler/output_test.go
Labels: approved, lgtm

#2110 OCM-8350 | fix: Enable VPC total clean
  tests/utils/profilehandler/data_cleaner.go
Labels: approved, lgtm

#2140 OCM-7289 | feat: create/update of maxUnavailable and maxSurge for NodePool
  cmd/create/machinepool/cmd.go
  cmd/create/machinepool/nodepool.go
  cmd/describe/machinepool/cmd_test.go
  cmd/edit/machinepool/cmd.go
  cmd/edit/machinepool/nodepool.go
  pkg/helper/machinepools/helpers.go
  pkg/helper/machinepools/helpers_test.go
  pkg/machinepool/output.go
  pkg/machinepool/output_test.go
  pkg/ocm/output/nodepools.go
  pkg/ocm/output/nodepools_test.go
Labels: approved, lgtm

#2145 OCM-8569 | test: automated cases id:70970,72657
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2131 OCM-7918 | fix: use space delimiter in AWS tags error msg to avoid confusion
  pkg/aws/helpers.go
  pkg/aws/helpers_test.go
Labels: approved, lgtm

#2151 OCM-8269 | feat: hide attach/detach commands
  cmd/attach/cmd.go
  cmd/attach/policy/cmd.go
  cmd/detach/cmd.go
  cmd/detach/policy/cmd.go
Labels: approved, lgtm

#2152 OCM-8648 | feat: handle 412 response in upgrade commands
  cmd/upgrade/roles/cmd.go
Labels: approved, lgtm

#2149 OCM-8636 | test: automate id:67275 create/describe/edit/delete cluster autoscaler by rosacli
  tests/e2e/rosa_autoscaler_test.go
  tests/utils/exec/rosacli/autoscaler_service.go
  tests/utils/exec/rosacli/cmd_client.go
Labels: approved, lgtm

#2154 OCM-8662 | test: fixing id:45161,68751,73492 ci failures
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_network_verifier.go
  tests/e2e/test_rosacli_node_pool.go
Labels: approved, lgtm

#2156 OCM-8680 | fix: err not being caught on rosa version
  cmd/version/cmd.go
Labels: approved, lgtm

#2153 OCM-8315 | feat: add additional allowed principals config for hcp clusters
  cmd/create/cluster/cmd.go
  cmd/describe/cluster/cmd.go
  cmd/describe/cluster/cmd_test.go
  cmd/edit/cluster/cmd.go
  pkg/helper/roles/helpers.go
  pkg/helper/roles/helpers_test.go
  pkg/ocm/clusters.go
Labels: approved, lgtm

#2159 OCM-7289 | feat: revert maxUnavailable and maxSurge for NodePool
  cmd/create/machinepool/cmd.go
  cmd/create/machinepool/nodepool.go
  cmd/describe/machinepool/cmd_test.go
  cmd/edit/machinepool/cmd.go
  cmd/edit/machinepool/nodepool.go
  pkg/helper/machinepools/helpers.go
  pkg/helper/machinepools/helpers_test.go
  pkg/machinepool/output.go
  pkg/machinepool/output_test.go
  pkg/ocm/output/nodepools.go
  pkg/ocm/output/nodepools_test.go
Labels: approved, lgtm

#2160 OCM-8691 | ci: Move latest to 4.15 version of sts classic profiles e to known HIVE issue
  tests/ci/data/profiles/rosa-classic.yaml
  tests/e2e/test_rosacli_node_pool.go
Labels: approved, lgtm

#2079 OCM-8051 | test: Automated id:66372 create cluster with invalid volume sizes
  tests/e2e/e2e_setup_test.go
Labels: approved, lgtm

#2148 OCM-8632 | test: automate id:74225,73449 attach/detach/describe arbit…
  tests/ci/labels/features.go
  tests/e2e/test_rosacli_policy.go
  tests/utils/common/arn.go
  tests/utils/exec/rosacli/cluster_service.go
  tests/utils/exec/rosacli/cmd_client.go
  tests/utils/exec/rosacli/policies_service.go
Labels: approved, lgtm

#2158 OCM-8680 | fix: use a tmp file per username
  pkg/cache/cache.go
Labels: approved, lgtm

#2162 OCM-8706 | chore: Update to version 1.2.42 in master branch
  pkg/info/info.go
Labels: approved, lgtm

#2150 OCM-6477 | fix: fetch subnets for availability zone
  cmd/create/machinepool/helper_test.go
  cmd/create/machinepool/nodepool.go
Labels: approved, lgtm

#2094 OCM-8220 | test: Automated case id:52691 User can set availability zones
  tests/ci/data/profiles/rosa-classic.yaml
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2164 OCM-7289 | feat: create/update of maxUnavailable and maxSurge for HCP nodepools
  cmd/create/machinepool/cmd.go
  cmd/create/machinepool/nodepool.go
  cmd/describe/machinepool/cmd_test.go
  cmd/edit/machinepool/cmd.go
  cmd/edit/machinepool/nodepool.go
  pkg/helper/machinepools/helpers.go
  pkg/helper/machinepools/helpers_test.go
  pkg/machinepool/output.go
  pkg/machinepool/output_test.go
  pkg/ocm/output/nodepools.go
  pkg/ocm/output/nodepools_test.go
Labels: approved, lgtm

#2165 OCM-8664 | ci: define override_rosacli_build to support CI running on indicated rosacli binary
  images/Dockerfile.e2e
  tests/prow_ci.sh
Labels: approved, lgtm

#2168 OCM-8291 | chore: bump ocm-sdk-go to v0.1.425
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/azure_node_pool_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/azure_node_pool_list_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/azure_node_pool_list_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/azure_node_pool_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/azure_node_pool_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/node_pool_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/node_pool_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/node_pool_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/internal/system_cas_windows.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm

#2155 OCM-8640 | test: automated case id:71329
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2172 OCM-8776 | test: Automated case id:35420，74399 Create cluster with channel group
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_cluster_post.go
Labels: approved, lgtm

#2113 OCM-8867 | fix: include prefix check for clusters running registered oidc configs
  .gitignore
  cmd/list/operatorroles/cmd.go
  pkg/aws/client.go
  pkg/aws/client_mock.go
  pkg/aws/policies.go
  pkg/aws/policies_test.go
Labels: approved, lgtm

#2175 OCM-8853 | ci: Mask sensitive info from the log to avoid security issue
  tests/utils/log/constants.go
Labels: approved, lgtm

#2176 OCM-8855 | tests: Fixed the test cases for CI failure
  tests/e2e/e2e_suite_test.go
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_idp.go
  tests/e2e/test_rosacli_ingress.go
  tests/e2e/test_rosacli_policy.go
  tests/utils/config/cluster.go
  tests/utils/exec/rosacli/ingress_service.go
Labels: approved, lgtm

#2178 OCM-8761 | test: Exclude 64040
  tests/e2e/test_rosacli_cluster_post.go
Labels: approved, lgtm

#2171 OCM-8796 | test: fixing id:67275 test case enhancement
  tests/e2e/rosa_autoscaler_test.go
  tests/utils/exec/rosacli/autoscaler_service.go
Labels: approved, lgtm

#2174 OCM-8848 | test: automate id:74402,74403,73731 upgrade/delete roles with attaching arbitrary policies
  go.mod
  go.sum
  tests/ci/labels/features.go
  tests/e2e/test_rosacli_policy.go
  tests/e2e/test_rosacli_upgrade.go
  tests/utils/exec/rosacli/ocm_resource_service.go
  tests/utils/exec/rosacli/version_service.go
  vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/client.go
  vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/policy.go
  vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/role.go
  vendor/modules.txt
Labels: approved, lgtm

#2019 OCM-7961 | chore: update the fips flag description
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#2167 OCM-8772 | test: Automated case id:46312,74436 Create cluster with fips
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_cluster_post.go
Labels: approved, lgtm

#2181 Hide the aws billing account getting exposed in cluster installation log
  tests/utils/log/constants.go
Labels: approved, lgtm

#2179 OCM-8952 | test: fixing id:35878
  tests/e2e/test_rosacli_idp.go
Labels: approved, lgtm

#2185 OCM-8985 | test: fixing id:66372,73725,72657,70970,56440 hcp ci fix
  tests/e2e/e2e_setup_test.go
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2188 OCM-9005 | fix: Update ocm-sdk-go to fix Windows SSL certificate issues
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/internal/system_cas.go
  vendor/github.com/openshift-online/ocm-sdk-go/internal/system_cas_windows.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm

#2189 [release_1.2.41] OCM-9005 | fix: Update ocm-sdk-go to fix Windows SSL certificate issues
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/internal/system_cas.go
  vendor/github.com/openshift-online/ocm-sdk-go/internal/system_cas_windows.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm

#2191 OCM-9008 | test: fixing id:45161,73755 hcp ci fix
  tests/ci/data/profiles/rosa-hcp.yaml
  tests/e2e/hcp_external_auth_test.go
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2187 OCM-8914 | test: Automated id:41549,52352,52764,66750
  tests/e2e/test_rosacli_cluster_post.go
  tests/e2e/test_rosacli_machine_pool.go
Labels: approved, lgtm

#2193 OCM-5092 | fix: remove empty line between mode descriptions in -h output
  pkg/interactive/mode.go
Labels: approved, lgtm

#2161 OCM-6708 | ci: Enable lint check on e2e tests
  Makefile
  tests/ci/config/config.go
  tests/e2e/dummy_test.go
  tests/e2e/e2e_report.go
  tests/e2e/hcp_cluster_test.go
  tests/e2e/hcp_external_auth_test.go
  tests/e2e/hcp_tuning_config_test.go
  tests/e2e/rosa_autoscaler_test.go
  tests/e2e/test_rosacli_account_roles.go
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_cluster_post.go
  tests/e2e/test_rosacli_idp.go
  tests/e2e/test_rosacli_idp_user.go
  tests/e2e/test_rosacli_ingress.go
  tests/e2e/test_rosacli_kubelet_config.go
  tests/e2e/test_rosacli_machine_pool.go
  tests/e2e/test_rosacli_network_verifier.go
  tests/e2e/test_rosacli_node_pool.go
  tests/e2e/test_rosacli_ocm_role.go
  tests/e2e/test_rosacli_oidc_config.go
  tests/e2e/test_rosacli_operator_roles.go
  tests/e2e/test_rosacli_policy.go
  tests/e2e/test_rosacli_token.go
  tests/e2e/test_rosacli_upgrade.go
  tests/e2e/test_rosacli_user_role.go
  tests/utils/common/assert.go
  tests/utils/common/file.go
  tests/utils/common/helper.go
  tests/utils/common/oidc.go
  tests/utils/common/string.go
  tests/utils/exec/reportportal/report_portal.go
  tests/utils/exec/rosacli/autoscaler_service.go
  tests/utils/exec/rosacli/break_glass_credential_service.go
  tests/utils/exec/rosacli/cmd_parser.go
  tests/utils/exec/rosacli/cmd_runner.go
  tests/utils/exec/rosacli/external_auth_provider_service.go
  tests/utils/exec/rosacli/ingress_service.go
  tests/utils/exec/rosacli/kubelet_config_service.go
  tests/utils/exec/rosacli/machinepool_service.go
  tests/utils/exec/rosacli/machinepool_upgrade_service.go
  tests/utils/exec/rosacli/network_verifier_service.go
  tests/utils/exec/rosacli/ocm_resource_service.go
  tests/utils/exec/rosacli/tuning_config_service.go
  tests/utils/exec/rosacli/user_service.go
  tests/utils/exec/rosacli/version_service.go
  tests/utils/profilehandler/data_preparation.go
  tests/utils/profilehandler/parse_info.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2194 OCM-2730 | fix: Update error message for linking ocm-role/user-role with not existed entries
  cmd/link/ocmrole/cmd.go
  cmd/link/userrole/cmd.go
Labels: approved, lgtm

#1945 COM-7477 | feat: show state description for HCP upgrade policies
  cmd/describe/upgrade/cmd.go
  cmd/describe/upgrade/cmd_test.go
Labels: lgtm

#2199 OCM-9102 | ci: fix cluster name generated with suffix '-' issue
  tests/utils/common/string.go
  tests/utils/profilehandler/data_preparation.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2198 OCM-9140 | fix: Do not enable interactive for max-surge and max-available
  cmd/edit/machinepool/nodepool.go
Labels: approved, lgtm

#2197 OCM-8329 | fix: add password validator for create admin
  cmd/create/admin/cmd.go
Labels: approved, lgtm

#2196 OCM-7851 | fix: rosa create operator-roles should not support --cluster and --oidc-config-id at the same time
  cmd/create/operatorroles/cmd.go
Labels: approved, lgtm

#2184 OCM-8922 | test: Automated case id:65160 Htpasswd IDP admin flow vali…
  tests/e2e/test_rosacli_idp.go
Labels: approved, lgtm

#2204 OCM-7563 | fix: validate node drain grace period when edit node pools
  cmd/edit/machinepool/nodepool.go
Labels: lgtm

#2206 OCM-9178 | test: automate id:74430,74387 create/edit/describe nodepool with maxsurge/maxunavailable
  tests/e2e/test_rosacli_node_pool.go
  tests/utils/exec/rosacli/machinepool_service.go
Labels: approved, lgtm

#2201 OCM-8986 | test: Automated id:68173,66874,67057
  tests/e2e/hcp_machine_pool_test.go
  tests/e2e/test_rosacli_machine_pool.go
Labels: approved, lgtm

#2207 OCM-9094 | chore: bump ocm-sdk-go
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/modules.txt
Labels: approved, lgtm

#2186 OCM-8285 | test: implement no-cni(cilium) supporting
  tests/ci/config/config.go
  tests/ci/data/resources/cilium.yaml
  tests/e2e/e2e_setup_test.go
  tests/e2e/test_rosacli_cluster.go
  tests/utils/config/support.go
  tests/utils/exec/occli/cmd_client.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2203 OCM-9191 | fix: typo in logger info message for output of command
  tests/utils/exec/rosacli/cmd_runner.go
Labels: approved, lgtm, ok-to-test

#2210 Revert "OCM-9094 | feat: support multi-arch-enabled parameter"
  cmd/create/cluster/cmd.go
  cmd/describe/cluster/cmd.go
  pkg/ocm/clusters.go
Labels: approved, lgtm

#2211 OCM-9166 | fix: prevent same role arns for IAM roles of the same cluster
  cmd/create/cluster/cmd.go
  cmd/create/cluster/cmd_test.go
Labels: approved, lgtm
