Repository openshift/rosa, pull requests merged in 2024-04, with the labels that each got.

#1892 Revert "OCM-6119 | fix: block users from passing region flag when creating an oidc provider"
  cmd/create/oidcprovider/cmd.go
Labels: approved, lgtm

#1893 OCM-6926 | fix: Added back the condition to check for empty env flag
  cmd/login/cmd.go
  cmd/login/cmd_test.go
Labels: approved, lgtm

#1884 OCM-6820 | fix: add checks for mandatory parameters
  pkg/externalauthprovider/flags.go
  pkg/externalauthprovider/flags_test.go
Labels: approved, lgtm

#1895 OCM-7110 | fix: GitHub IDP validation
  cmd/create/idp/github.go
  go.mod
  pkg/interactive/validation.go
  pkg/interactive/validation_test.go
Labels: approved, lgtm, ok-to-test

#1888 OCM-7098 | chore: request to add 'davidleerh' to the list of approvers
  OWNERS
Labels: approved, lgtm

#1896 OCM-6955 | fix: provide better message for external auth creation
  cmd/create/externalauthprovider/cmd.go
Labels: approved, lgtm

#1877 OCM-5942 | feat: allow users set delete protection on cluster
  cmd/describe/cluster/cmd.go
  cmd/edit/cluster/cmd.go
  pkg/input/consts.go
  pkg/ocm/clusters.go
Labels: approved, lgtm

#1894 Display AWS Billing Account on non-HCP
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm, ok-to-test

#1897 OCM-7136 | fix: support create breakglasscredential without optional flags
  cmd/create/breakglasscredential/cmd.go
  pkg/breakglasscredential/flags.go
  pkg/breakglasscredential/flags_test.go
Labels: approved, lgtm

#1878 OCM-6697 | fix: upgrade role error should print extra info when invoke from upgrade cluster
  cmd/upgrade/roles/cmd.go
  cmd/upgrade/roles/cmd_test.go
Labels: approved, lgtm

#1899 OCM-6840 | fix: Add json output test for external auth
  cmd/describe/externalauthprovider/cmd.go
  cmd/describe/externalauthprovider/cmd_test.go
  cmd/list/externalauthprovider/cmd.go
  cmd/list/externalauthprovider/cmd_test.go
  cmd/revoke/breakglasscredential/cmd.go
  pkg/test/helpers.go
Labels: approved, lgtm

#1898 OCM-6161 | ci: Automate HCP machinepool creation with security groups
  tests/e2e/e2e_suite_test.go
  tests/e2e/hcp_machine_pool_test.go
  tests/utils/common/file.go
  tests/utils/exec/rosacli/machinepool_service.go
Labels: approved, lgtm

#1901 OCM-7168 | fix: Add info after successfully created breakglasscredentials
  cmd/create/breakglasscredential/cmd.go
  cmd/describe/breakglasscredential/cmd.go
  cmd/describe/breakglasscredential/cmd_test.go
  cmd/list/externalauthprovider/cmd.go
  cmd/list/externalauthprovider/cmd_test.go
  pkg/test/helpers.go
Labels: approved, lgtm

#1907 OCM-7318 | chore: update the list jira helper to ignore reverts when listing release jiras
  hack/release-list-jiras.sh
Labels: approved, lgtm

#1905 OCM-7169 | fix: error message when describe credential that status is revoked
  cmd/describe/breakglasscredential/cmd.go
  cmd/describe/breakglasscredential/cmd_test.go
Labels: approved, lgtm

#1861 OCM-6314 | ci: Refactor day1 creation function for test
  .gitignore
  tests/ci/config/config.go
  tests/ci/data/profiles/external.yaml
  tests/ci/data/profiles/rosa-classic.yaml
  tests/ci/data/profiles/rosa-hcp.yaml
  tests/e2e/dummy_test.go
  tests/e2e/e2e_setup_test.go
  tests/utils/common/constants/cluster.go
  tests/utils/common/file.go
  tests/utils/common/helper.go
  tests/utils/common/string.go
  tests/utils/config/cluster.go
  tests/utils/exec/rosacli/cluster_service.go
  tests/utils/exec/rosacli/cmd_parser.go
  tests/utils/exec/rosacli/cmd_runner.go
  tests/utils/exec/rosacli/ocm_resource_service.go
  tests/utils/exec/rosacli/version_service.go
  tests/utils/profilehandler/data_preparation.go
  tests/utils/profilehandler/interface.go
  tests/utils/profilehandler/parse_yaml.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#1904 OCM-6309 | ci: Verify test case(s) 55729/56782/60202/63178/61139/67414
  .gitignore
  tests/e2e/test_rosacli_node_pool.go
  tests/e2e/test_rosacli_region.go
Labels: approved, lgtm

#1910 OCM-6309 | ci: Verify test cases 68828|68835|68836|38787|66872
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_kubelet_config.go
  tests/e2e/test_rosacli_machine_pool.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#1911 OCM-6309 | ci: Verify test case 45159
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#1914 OCM-7346 | chore: increment master version (to 1.2.39)
  pkg/info/info.go
Labels: approved, lgtm

#1890 OCM-6391 | feat: Deprecate the region flag in commands which do not utilize it
  cmd/create/cmd.go
  cmd/describe/cmd.go
  cmd/dlt/cmd.go
  cmd/edit/cmd.go
  cmd/grant/cmd.go
  cmd/install/cmd.go
  cmd/link/cmd.go
  cmd/list/cmd.go
  cmd/logs/cmd.go
  cmd/register/cmd.go
  cmd/revoke/cmd.go
  cmd/uninstall/cmd.go
  cmd/unlink/cmd.go
  cmd/upgrade/cmd.go
  pkg/arguments/arguments.go
  pkg/arguments/arguments_test.go
  pkg/aws/region/flag.go
Labels: approved, lgtm

#1863 OCM-6079 | feat: support cluster admin day-1 creation for HCP cluster
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1909 OCM-7188: GitHub IDP Add hostname validation
  pkg/interactive/validation.go
  pkg/interactive/validation_test.go
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#1915 OCM-7340 | fix: Add poll length for break glass credential
  pkg/ocm/break_glass_credential.go
Labels: approved, lgtm

#1916 OCM-7365 | ci: Automated cases 38838 and 68172 and verified 43251
  tests/e2e/test_rosacli_machine_pool.go
  tests/e2e/test_rosacli_verify.go
  tests/utils/common/string.go
  tests/utils/config/cluster.go
  tests/utils/exec/rosacli/machinepool_service.go
Labels: approved, lgtm

#1920 OCM-7358 | fix: invert describe out for cluster delete protection
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm

#1923 OCM-7401 | fix: allow empty GitHub IDP hostname
  pkg/interactive/validation.go
  pkg/interactive/validation_test.go
Labels: approved, lgtm, ok-to-test

#1917 OCM-6729 | feat: Show user tags on describe machine pool for HCP
  cmd/describe/machinepool/cmd_test.go
  cmd/describe/machinepool/nodepool.go
  pkg/ocm/output/machinepools.go
Labels: approved, lgtm

#1921 OCM-6309 | ci: Verify test case(s) 43051|57441|62083|52580|43046|66359|57056|57570
  tests/e2e/test_rosacli_iam_roles.go
  tests/e2e/test_rosacli_idp.go
  tests/e2e/test_rosacli_oidc_config.go
  tests/e2e/test_rosacli_oidc_provider.go
  tests/e2e/test_rosacli_verify.go
Labels: approved, lgtm

#1924 OCM-7412 | fix: list instance types filter by region requires installer role arn
  cmd/list/instancetypes/cmd.go
  cmd/list/instancetypes/cmd_test.go
Labels: approved, lgtm

#1922 OCM-7252 | feat: Move describe machinepool funcs to pkg, test, split up, make interface
  cmd/describe/machinepool/cmd.go
  cmd/describe/machinepool/machinepool.go
  cmd/describe/machinepool/nodepool.go
  pkg/machinepool/machinepool.go
  pkg/machinepool/machinepool_suite_test.go
  pkg/machinepool/machinepool_test.go
  pkg/machinepool/output.go
  pkg/machinepool/output_test.go
Labels: approved, lgtm

#1926 OCM-6309: Verify test case 52419
  tests/e2e/test_rosacli_iam_roles.go
Labels: approved, lgtm, jira/valid-reference

#1925 OCM-6309 | ci: Verify test case(s) 45161|35878|35896|49137|46187|38850|34102|66362|36128
  tests/ci/data/profiles/rosa-classic.yaml
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_iam_roles.go
  tests/e2e/test_rosacli_idp.go
  tests/e2e/test_rosacli_user.go
  tests/utils/log/constants.go
  tests/utils/log/logger.go
Labels: approved, lgtm

#1927 OCM-6501 | fix: Adjust describe machine pool output
  cmd/describe/machinepool/cmd_test.go
  pkg/machinepool/output.go
  pkg/machinepool/output_test.go
Labels: approved, lgtm

#1930 OCM-7340 | fix: Add info msg for empty case
  cmd/describe/breakglasscredential/cmd.go
  cmd/describe/breakglasscredential/cmd_test.go
Labels: approved, lgtm

#1931 OCM-6391 | fix: Fixed bug where deprecation shows for parent cmd
  cmd/create/cmd.go
  pkg/arguments/arguments.go
  pkg/arguments/arguments_test.go
Labels: approved, lgtm

#1929 OCM-6309 | ci: Verify test case(s) 63323|64917|64040|61138
  tests/e2e/test_rosacli_ingress.go
  tests/e2e/test_rosacli_network_verifier.go
  tests/e2e/test_rosacli_node_pool.go
  tests/e2e/test_rosacli_verify.go
Labels: approved, lgtm

#1933 [OCM-7442] Get the test case IDs
  tests/ci/config/config.go
  tests/ci/labels/runtime.go
  tests/e2e/e2e_pre_check_test.go
  tests/utils/exec/rosacli/cmd_runner.go
  tests/utils/exec/rosacli/pr_check.go
Labels: approved, lgtm

#1932 OCM-4806 | fix: align list users with list idps
  cmd/list/user/cmd.go
Labels: approved, lgtm

#1935 OCM-6309 | ci: Verify test case(s) 43070|60971
  tests/e2e/test_rosacli_iam_roles.go
  tests/e2e/test_rosacli_machine_pool.go
  tests/utils/exec/rosacli/ocm_resource_service.go
Labels: approved, lgtm

#1936 OCM-6391 | fix: only show message when region is changed and no output mode set
  pkg/arguments/arguments.go
  pkg/arguments/arguments_test.go
Labels: approved, lgtm

#1934 OCM-6199 | ci: migrate the Dockerfile from the repo release to rosa
  images/Dockerfile.e2e
Labels: approved, lgtm

#1777 OCM-4624 | feat: add cache for fetching versions from mirror
  cmd/download/rosa/cmd.go
  cmd/rosa/main.go
  cmd/verify/cmd.go
  cmd/verify/rosa/cmd.go
  cmd/verify/rosa/cmd_mock.go
  cmd/verify/rosa/cmd_suite_test.go
  cmd/verify/rosa/cmd_test.go
  cmd/version/cmd.go
  cmd/version/cmd_suite_test.go
  cmd/version/cmd_test.go
  cmd/version/options.go
  cmd/version/options_test.go
  codecov.yml
  go.mod
  go.sum
  pkg/cache/cache.go
  pkg/cache/cache_mock.go
  pkg/cache/cache_suite_test.go
  pkg/cache/cache_test.go
  pkg/cache/item.go
  pkg/cache/item_test.go
  pkg/cache/service.go
  pkg/cache/service_mock.go
  pkg/cache/service_test.go
  pkg/cache/utils.go
  pkg/cache/utils_test.go
  pkg/clients/http.go
  pkg/clients/http_mock.go
  pkg/constants/config.go
  pkg/kubeletconfig/capability_checker_mock.go
  pkg/kubeletconfig/config_test.go
  pkg/version/retriever.go
  pkg/version/retriever_mock.go
  pkg/version/retriever_test.go
  pkg/version/version.go
  pkg/version/version_mock.go
  pkg/version/version_suite_test.go
  pkg/version/version_test.go
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/modules.txt
Labels: approved, lgtm

#1942 OCM-6199 | ci: fix can not find go.mod
  images/Dockerfile.e2e
Labels: approved, lgtm

#1928 OCM-7451 | test: automate id:OCP-63179 create nodepool with tuning config will validate well
  tests/e2e/test_rosacli_node_pool.go
Labels: approved, lgtm

#1943 OCM-7483 | ci: Mask AWS account from the automation log
  tests/utils/log/constants.go
Labels: approved, lgtm

#1913 OCM-7079 | feat: select security groups interactive - filtering
  cmd/create/cluster/cmd.go
  cmd/create/machinepool/helper.go
  pkg/interactive/securitygroups/security_groups.go
  pkg/interactive/securitygroups/security_groups_test.go
Labels: approved, lgtm

#1944 OCM-6595| chore: 1.2.38-RC2 cut with cherrypicked release blocker
  cmd/describe/cluster/cmd.go
  cmd/list/instancetypes/cmd.go
  cmd/list/instancetypes/cmd_test.go
  pkg/info/info.go
Labels: approved

#1948 OCM-7498 | test: automate id:OCP-72715 create/edit nodepool with node…
  tests/e2e/test_rosacli_node_pool.go
  tests/utils/exec/rosacli/machinepool_service.go
Labels: approved, lgtm

#1940 OCM-5186 | fix: align nodepool actions with machinepools
  cmd/edit/machinepool/cmd.go
  cmd/edit/machinepool/machinepool.go
  cmd/edit/machinepool/machinepool_test.go
  cmd/edit/machinepool/main_test.go
  cmd/edit/machinepool/nodepool.go
  cmd/edit/machinepool/nodepool_test.go
Labels: approved, lgtm

#1947 OCM-5247 | fix: block HCP operator-roles with unmanaged policies acco…
  cmd/create/operatorroles/by_prefix.go
Labels: approved, lgtm

#1570 Warn users if not using latest release.
  cmd/rosa/main.go
  pkg/version/version.go
  pkg/version/version_test.go
Labels: approved, lgtm

#1938 OCM-7253 | feat: Refactor describe machine pool cmd to use new default runner
  cmd/describe/cmd.go
  cmd/describe/machinepool/cmd.go
  cmd/describe/machinepool/cmd_test.go
  cmd/describe/machinepool/options.go
  cmd/describe/machinepool/options_test.go
  pkg/machinepool/machinepool_test.go
  pkg/test/helpers.go
  pkg/test/helpers_suite_test.go
  pkg/test/helpers_test.go
Labels: approved, lgtm

#1952 OCM-7533 | ci: add Dockerfile for rosa-aws-cli:release
  images/Dockerfile.release
Labels: approved, lgtm

#1841 OCM-6527 | feat: add describe ingress command
  cmd/describe/cmd.go
  cmd/describe/ingress/cmd.go
  cmd/describe/ingress/cmd_test.go
  cmd/describe/ingress/main_test.go
  cmd/describe/ingress/options.go
  cmd/edit/ingress/cmd.go
  pkg/ingress/ingress.go
  pkg/ingress/ingress_test.go
  pkg/ocm/ingresses.go
  pkg/output/output.go
Labels: approved, lgtm

#1850 OCM-6723 | feat: allow to supply user tags on creation of hcp machine pool
  cmd/create/machinepool/cmd.go
  cmd/create/machinepool/helper_test.go
  cmd/create/machinepool/machinepool.go
  cmd/create/machinepool/nodepool.go
  pkg/helper/machinepools/helpers.go
Labels: approved, lgtm

#1956 OCM-7307 | fix: remove older attributes for component routes
  cmd/edit/ingress/cmd.go
  cmd/edit/ingress/flags.go
Labels: approved, lgtm

#1950 OCM-1308 | fix: filter empty subnet id
  cmd/create/cluster/cmd.go
  pkg/helper/helpers.go
  pkg/helper/helpers_test.go
Labels: approved, lgtm

#1941 OCM-6542 | feat: add cmd to attach policy
  cmd/attach/cmd.go
  cmd/attach/policy/cmd.go
  cmd/attach/policy/cmd_test.go
  cmd/rosa/main.go
  pkg/aws/client.go
  pkg/aws/client_test.go
  pkg/aws/mock_client.go
  pkg/aws/quota.go
  pkg/ocm/helpers.go
  pkg/policy/policy_service.go
  pkg/policy/policy_service_test.go
  pkg/test/helpers.go
Labels: approved, lgtm

#1959 OCM-7593 | test: automate id:OCP-36128 Updated a new checkpoint
  tests/e2e/test_rosacli_user.go
Labels: approved, lgtm

#1951 OCM-7531 | test: automate id:OCP-61322,OCP-63164 create/delete tuning…
  tests/e2e/hcp_tuning_config_test.go
  tests/e2e/test_rosacli_iam_roles.go
  tests/utils/exec/rosacli/tuning_config_service.go
Labels: approved, lgtm

#1946 OCM-6391 | fix: Ability to disable region flag deprecation manually
  cmd/create/cluster/cmd.go
  pkg/arguments/arguments.go
  pkg/arguments/arguments_test.go
Labels: approved, lgtm

#1963 OCM-5247 | fix: error message for unmanaged policies
  cmd/create/operatorroles/by_prefix.go
Labels: approved, lgtm

#1971 OCM-7669 | fix: valide rolename and policyarn in rosa attach/detach cmd
  cmd/attach/policy/cmd.go
  cmd/attach/policy/cmd_test.go
  cmd/detach/policy/cmd.go
  cmd/detach/policy/cmd_test.go
  pkg/aws/helpers.go
  pkg/policy/policy_service.go
  pkg/policy/policy_service_test.go
Labels: approved, lgtm

#1970 OCM-7647 | test: automate id:OCP-72899 create/list/describe/delete br…
  tests/e2e/hcp_external_auth_test.go
  tests/utils/exec/rosacli/break_glass_credential_service.go
  tests/utils/exec/rosacli/cluster_service.go
  tests/utils/exec/rosacli/cmd_client.go
Labels: approved, lgtm

#1972 OCM-7619 | ci: Automated 73469 for tags supporting on classic
  tests/e2e/test_rosacli_machine_pool.go
  tests/utils/exec/rosacli/break_glass_credential_service.go
  tests/utils/exec/rosacli/machinepool_service.go
Labels: approved, lgtm

#1973 OCM-4597 | test: automate id:OCP-73391 validations for editing machinepool
  tests/e2e/test_rosacli_node_pool.go
Labels: approved, lgtm

#1965 OCM-7614 | fix: Get the merged commit but not the pull request commit
  images/Dockerfile.e2e
  tests/e2e/e2e_pre_check_test.go
  tests/utils/exec/rosacli/pr_check.go
Labels: approved, lgtm

#1976 OCM-6899 | chore: increment master version (to 1.2.40)
  pkg/info/info.go
Labels: approved, lgtm

#1974 OCM-6391 | fix: Fix deprecation warn printing when creating cluster
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1960 OCM-7573 | fix: ensure version option args are initialised
  cmd/rosa/main.go
  cmd/version/cmd_test.go
  cmd/version/options.go
Labels: approved, lgtm

#1980 OCM-7811 | fix: hide attach and detach commands
  cmd/attach/cmd.go
  cmd/attach/policy/cmd.go
  cmd/detach/cmd.go
  cmd/detach/policy/cmd.go
Labels: approved, lgtm

#1982 OCM-7792 | fix: unhide breakglass and externalauth
  cmd/create/breakglasscredential/cmd.go
  cmd/create/externalauthprovider/cmd.go
  cmd/describe/breakglasscredential/cmd.go
  cmd/describe/externalauthprovider/cmd.go
  cmd/dlt/externalauthprovider/cmd.go
  cmd/list/breakglasscredential/cmd.go
  cmd/list/externalauthprovider/cmd.go
  cmd/revoke/breakglasscredential/cmd.go
Labels: approved, lgtm

#1984 OCM-6527 | fix: adjust describe ingress binding
  cmd/describe/ingress/cmd.go
  cmd/describe/ingress/cmd_test.go
Labels: approved, lgtm
