Repository openshift/rosa, pull requests merged in 2024-09, with the labels that each got.

#2401 OCM-10812 | ci: Generate common functions of rosacli CI steps to prow_ci.sh
  tests/prow_ci.sh
Labels: approved, lgtm

#2353 OCM-9773 | test: Automate id:45745
  tests/e2e/test_rosacli_account_roles.go
  tests/e2e/test_rosacli_operator_roles.go
Labels: approved, lgtm

#2372 OCM-10538 | ci: Add dawang to reviewers of tests package
  tests/OWNERS
Labels: approved, lgtm

#2386 OCM-10636 | chore: update goreleaser config to ignore merge commits
  .goreleaser.yaml
Labels: approved

#2407 OCM-10676 | fix: Assign cluster ID var in create/oidc_provider
  cmd/create/oidcprovider/cmd.go
Labels: approved, lgtm

#2409 OCM-10852 | fix bash syntax error in prow_ci.sh
  tests/prow_ci.sh
Labels: approved, lgtm

#2411 OCM-10854 | test: fix id:57094
  tests/e2e/test_rosacli_upgrade.go
Labels: approved, lgtm

#2412 OCM-10837 | test: Automated ids:37177,38857,37176,38837,68219
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_cluster_post.go
  tests/e2e/test_rosacli_ingress.go
  tests/e2e/test_rosacli_machine_pool.go
Labels: approved, lgtm

#2408 OCM-10712 | test: fix id:75210
  tests/e2e/test_rosacli_cluster_post.go
Labels: approved, lgtm

#2413 OCM-10638 | test: Automated ids:54864,73672,66761
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_version.go
  tests/utils/exec/rosacli/version_service.go
Labels: approved, lgtm

#2402 OCM-10815 | test: automated ids:75904,75925,75927
  tests/e2e/test_rosacli_account_roles.go
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_ocm_role.go
  tests/e2e/test_rosacli_operator_roles.go
  tests/e2e/test_rosacli_user_role.go
  tests/utils/common/constants/general.go
Labels: approved, lgtm

#2414 OCM-10866 | test: automated ids:75603,52693
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_user_role.go
Labels: approved, lgtm

#2263 OCM-9299 | test: Automate ids:57444,75445
  tests/e2e/test_rosacli_upgrade.go
Labels: approved, lgtm

#2415 OCM-10856 | test: fix id:55883 fixes ci job "e2e-rosa-sts-upgrade-y-stream-prod-f3"
  tests/e2e/test_rosacli_upgrade.go
Labels: approved, lgtm

#2420 OCM-10897 | ci: Enhance the functions detection about the parameter in prow_ch.sh
  tests/prow_ci.sh
Labels: approved, lgtm

#2421 OCM-10903 | test: fix ids:57441,62083,38770,45161,45742,43053,71329,43053,75603,75925,75927,59551,60956,75504,45745,57408 enhancement to random prefix and name in test cases
  tests/e2e/test_rosacli_account_roles.go
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_operator_roles.go
Labels: approved, lgtm

#2417 OCM-10777 | fix: fixing OCM-10777 + OCM-10818
  pkg/helper/machinepools/helpers.go
  pkg/helper/machinepools/helpers_test.go
  pkg/machinepool/helper.go
  pkg/machinepool/helper_test.go
  pkg/machinepool/machinepool.go
  pkg/machinepool/machinepool_test.go
Labels: approved, lgtm

#2423 OCM-10897 | ci: fix the unbound FOCUS variable
  tests/prow_ci.sh
Labels: approved, lgtm

#2419 OCM-10868 | test: Automate id:56224
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2424 OCM-10897 | ci: replace all ENV variable to parameter passing when call function
  tests/prow_ci.sh
Labels: approved, lgtm

#2422 OCM-10512 | fix: Fixing OCM-10512 bug
  tests/e2e/test_rosacli_machine_pool.go
Labels: approved, lgtm

#2425 OCM-9804 | fix: Add etcd to reduce confusion
  cmd/describe/cluster/cmd.go
Labels: lgtm

#2426 OCM-9882 | feat: print custom worker disk size in describe nodepool
  pkg/machinepool/output.go
  pkg/machinepool/output_test.go
Labels: approved, lgtm

#2429 OCM-10943 | feat: show disk size in output for list node pools
  cmd/list/machinepool/cmd_test.go
  pkg/machinepool/machinepool.go
  pkg/machinepool/machinepool_test.go
  pkg/ocm/output/nodepools.go
  tests/utils/exec/rosacli/machinepool_service.go
Labels: approved, lgtm

#2432 OCM-9804 | fix: Fix etcd kms key arn space
  cmd/describe/cluster/cmd.go
Labels: approved, lgtm

#2438 OCM-10990 | test: fix id:67057
  tests/e2e/test_rosacli_machine_pool.go
Labels: approved, lgtm

#2416 OCM-10628 | ci: Make NAME_PREFIX required for cluster creation
  tests/README.md
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2441 OCM-7568 | feat: Clarify that 'billing-account' expects an account ID
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#2439 OCM-10998 | test: fix id:57094
  tests/e2e/test_rosacli_upgrade.go
Labels: approved, lgtm

#2434 OCM-10952 | test: Automated ids:45502,46308,45509,46310 for proxy supporting
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_cluster_post.go
  tests/utils/common/constants/cluster.go
  tests/utils/exec/rosacli/cluster_service.go
Labels: approved, lgtm

#2442 OCM-11028 | test: fix id:38837 for ingress validation
  tests/e2e/test_rosacli_ingress.go
Labels: approved, lgtm

#2393 OCM-10690 | test: updated id:34102
  tests/e2e/test_rosacli_cluster.go
  tests/utils/common/constants/general.go
  tests/utils/common/helper.go
Labels: approved, lgtm

#2433 OCM-9774 | ci: Automate ids:54413,56783,56786,63169,63174,76056
  tests/e2e/classic_tuning_config_test.go
  tests/e2e/hcp_machine_pool_test.go
  tests/e2e/hcp_tuning_config_test.go
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_node_pool.go
  tests/utils/config/cluster_command.go
  tests/utils/exec/rosacli/machinepool_service.go
  tests/utils/exec/rosacli/tuning_config_service.go
Labels: approved, lgtm

#2436 OCM-8760 | fix: update test ids: 43070, 74661
  tests/e2e/test_rosacli_account_roles.go
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_ocm_role.go
  tests/e2e/test_rosacli_operator_roles.go
Labels: approved, lgtm

#2443 OCM-11019 | fix: Do not accept clusterID for thumbprint if programmatic
  cmd/create/oidcprovider/cmd.go
Labels: approved, lgtm

#2351 OCM-10374 | fix: Add Limited Support Reason Override support
  pkg/ocm/limited_support.go
Labels: approved, lgtm, ok-to-test

#2447 OCM-11019 | fix: Fix issue with classic clusters without --oidc-config-id flag
  cmd/create/oidcprovider/cmd.go
Labels: approved, lgtm

#2448 OCM-11054 | fix: add unit to disk size on describe nodepool
  cmd/describe/machinepool/cmd_test.go
  pkg/machinepool/output.go
  pkg/machinepool/output_test.go
Labels: approved, lgtm

#2451 OCM-11096 | ci: Fix the result reporting issue
  tests/prow_ci.sh
  tests/utils/exec/reportportal/report_portal.go
Labels: approved, lgtm

#2446 OCM-11027 | ci: fix id:37176
  tests/e2e/test_rosacli_cluster_post.go
Labels: approved, lgtm

#2437 OCM-10674 | test: automated ids:59547,62161
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_upgrade.go
Labels: approved, lgtm

#2445 OCM-11026 | test: automate id 38775
  tests/e2e/test_rosacli_machine_pool.go
  tests/utils/exec/rosacli/machinepool_service.go
Labels: approved, lgtm

#2453 OCM-11019 | fix: Fix creating provider with cluster ID
  cmd/create/oidcprovider/cmd.go
Labels: approved, lgtm

#2454 OCM-11113 | feat: bump ocm-common to lower np min disk size to 75
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-common/pkg/machinepool/validations/disk_size.go
  vendor/modules.txt
Labels: approved, lgtm

#2452 OCM-11097 | test: automated id:76093
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2459 OCM-11135 | ci: Fix id:67414
  tests/e2e/test_rosacli_node_pool.go
Labels: approved, lgtm

#2461 OCM-11158 | ci: Fix id:75150
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2463 OCM-11156 | test: fix id:60275
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2462 OCM-10679 | fix: use default user agent
  pkg/aws/client.go
Labels: approved, lgtm

#2460 OCM-11069 | test: Automate OCP-38780 and OCP-38783
  tests/e2e/test_rosacli_ingress.go
  tests/e2e/test_rosacli_machine_pool.go
  tests/utils/exec/rosacli/ingress_service.go
  tests/utils/exec/rosacli/machinepool_service.go
Labels: approved, lgtm

#2464 OCM-11198 | test: fix ids:46310,38788,38850
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_idp.go
Labels: approved, lgtm

#2465 OCM-11201 | fix : fix make target ensuring release builds and publishes to github
  Makefile
Labels: approved, lgtm

#2473 OCM-11249 | ci: Make rosacli running based on stable channel group
  tests/ci/data/profiles/external.yaml
  tests/ci/data/profiles/rosa-classic.yaml
  tests/ci/data/profiles/rosa-hcp.yaml
Labels: approved, lgtm

#2474 OCM-11254 | ci: Fix pre-submit job destroy-post failure
  tests/e2e/e2e_setup_test.go
  tests/e2e/e2e_tear_down_test.go
Labels: approved, lgtm

#2471 OCM-11241 | fix: update description for 36293
  tests/e2e/test_rosacli_machine_pool.go
Labels: approved, lgtm

#2475 OCM-11229 | ci: fix add temporary step for 4.17 HCP cluster
  tests/utils/profilehandler/data_preparation.go
  tests/utils/profilehandler/interface.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2472 OCM-7315 | feat: describe client support for configurable registries
  cmd/describe/cluster/cmd.go
  cmd/describe/cluster/cmd_test.go
Labels: approved, lgtm

#2479 OCM-11264 | test: automated cases id:71174
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2480 OCM-10922 | test: Automated ids:60083 check for etcd encryption
  tests/e2e/hcp_cluster_test.go
  tests/utils/exec/rosacli/cluster_service.go
Labels: approved, lgtm

#2482 OCM-11295 | fix: adjust check for policy tags
  pkg/aws/policies.go
  pkg/aws/policies_test.go
Labels: approved, lgtm

#2477 OCM-11260 | ci: Move constants and rename common-helper package
  tests/ci/config/config.go
  tests/e2e/classic_tuning_config_test.go
  tests/e2e/dummy_test.go
  tests/e2e/e2e_setup_test.go
  tests/e2e/hcp_cluster_test.go
  tests/e2e/hcp_external_auth_test.go
  tests/e2e/hcp_machine_pool_test.go
  tests/e2e/hcp_tuning_config_test.go
  tests/e2e/test_rosacli_account_roles.go
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_cluster_post.go
  tests/e2e/test_rosacli_idp.go
  tests/e2e/test_rosacli_ingress.go
  tests/e2e/test_rosacli_machine_pool.go
  tests/e2e/test_rosacli_network_verifier.go
  tests/e2e/test_rosacli_node_pool.go
  tests/e2e/test_rosacli_oidc_config.go
  tests/e2e/test_rosacli_operator_roles.go
  tests/e2e/test_rosacli_policy.go
  tests/e2e/test_rosacli_upgrade.go
  tests/e2e/test_rosacli_user_role.go
  tests/e2e/test_rosacli_version.go
  tests/utils/constants/cluster.go
  tests/utils/constants/general.go
  tests/utils/constants/machinepool.go
  tests/utils/exec/rosacli/cmd_runner.go
  tests/utils/exec/rosacli/idp_service.go
  tests/utils/exec/rosacli/ingress_service.go
  tests/utils/exec/rosacli/machinepool_service.go
  tests/utils/exec/rosacli/machinepool_upgrade_service.go
  tests/utils/exec/rosacli/pr_check.go
  tests/utils/exec/rosacli/tuning_config_service.go
  tests/utils/exec/rosacli/user_service.go
  tests/utils/exec/rosacli/version_service.go
  tests/utils/helper/arn.go
  tests/utils/helper/assert.go
  tests/utils/helper/file.go
  tests/utils/helper/helper.go
  tests/utils/helper/idp.go
  tests/utils/helper/oidc.go
  tests/utils/helper/role.go
  tests/utils/helper/slice.go
  tests/utils/helper/string.go
  tests/utils/profilehandler/data_preparation.go
  tests/utils/profilehandler/parse_info.go
  tests/utils/profilehandler/profile_handler.go
Labels: approved, lgtm

#2430 OCM-7315 | feat: create and edit client support for configurable registries
  cmd/create/cluster/cmd.go
  cmd/edit/cluster/cmd.go
  cmd/rosa/structure_test/command_args/rosa/create/cluster/command_args.yml
  cmd/rosa/structure_test/command_args/rosa/edit/cluster/command_args.yml
  pkg/clusterregistryconfig/flags.go
  pkg/clusterregistryconfig/flags_test.go
  pkg/clusterregistryconfig/registryconfig_suite_test.go
  pkg/clusterregistryconfig/specRegistryAdditionalTrustedCa.json
  pkg/clusterregistryconfig/specRegistryAdditionalTrustedCaInvalid.json
  pkg/ocm/clusters.go
  pkg/ocm/clusters_test.go
  pkg/ocm/helpers.go
  pkg/ocm/helpers_test.go
  pkg/ocm/registry_config.go
  pkg/ocm/registry_config_test.go
Labels: approved, lgtm

#2487 OCM-11356 | ci: fix id:56786,73638
  tests/e2e/hcp_machine_pool_test.go
Labels: approved, lgtm

#2484 OCM-7315 | fix: when classic topology return nil
  pkg/clusterregistryconfig/flags.go
  pkg/clusterregistryconfig/flags_test.go
Labels: approved

#2410 OCM-9508 | chore: bump version info to 1.2.46
  pkg/info/info.go
Labels: approved, lgtm

#2466 OCM-11202 | chore : add output to release script for errata jira list
  hack/release-list-jiras.sh
Labels: approved, lgtm

#2481 OCM-11001 | ci: Automate id:71319,73814
  tests/e2e/hcp_machine_pool_test.go
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2490 OCM-11364 | fix: Regression, HCP nodepool creation validation used for classic
  pkg/machinepool/helper.go
  pkg/machinepool/helper_test.go
  pkg/machinepool/machinepool.go
  pkg/machinepool/machinepool_test.go
Labels: approved, lgtm

#2489 OCM-10846 | fix: adjust error message for ingress identifier
  cmd/describe/ingress/cmd_test.go
  cmd/describe/ingress/options.go
  cmd/dlt/ingress/cmd.go
  cmd/edit/ingress/cmd.go
  tests/e2e/test_rosacli_ingress.go
Labels: approved, lgtm

#2491 OCM-9515 | chore: adjust goreleaser to use openshift/rosa
  .goreleaser.yaml
Labels: approved, lgtm

#2476 OCM-11000 | ci: Automate ids:67149,76200
  tests/e2e/hcp_machine_pool_test.go
  tests/e2e/test_rosacli_machine_pool.go
  tests/utils/constants/cluster.go
  tests/utils/exec/rosacli/cluster_service.go
  tests/utils/exec/rosacli/machinepool_upgrade_service.go
Labels: approved, lgtm

#2485 OCM-11350 | ci: fix id:67275
  tests/e2e/rosa_autoscaler_test.go
Labels: approved, lgtm

#2496 OCM-11407 | fix: Error msg for editing nodepool; autoscaling+ 0 replicas
  pkg/machinepool/machinepool.go
  pkg/machinepool/machinepool_test.go
Labels: approved, lgtm

#2468 OCM-9879 | test: Automated ids:66359,66372,66872,66874 for disk size
  tests/e2e/hcp_machine_pool_test.go
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_cluster_post.go
  tests/e2e/test_rosacli_machine_pool.go
  tests/utils/constants/cluster.go
  tests/utils/exec/rosacli/machinepool_service.go
Labels: approved, lgtm

#2501 OCM-11407 | ci: fix nil value return for editNodepoolValidation
  pkg/machinepool/machinepool.go
Labels: approved, lgtm

#2502 OCM-10846 | test: update id:38837 error message with the fix
  tests/e2e/test_rosacli_cluster_post.go
  tests/e2e/test_rosacli_ingress.go
Labels: approved, lgtm

#2488 OCM-11199 | test: fix id:38775
  tests/e2e/test_rosacli_machine_pool.go
Labels: approved, lgtm

#2469 OCM-9878 | ci: include volume_size for profile rosa-hcp-advanced
  tests/ci/data/profiles/rosa-hcp.yaml
Labels: approved, lgtm

#2493 OCM-11297 | test: automated cases id:38810
  tests/e2e/test_rosacli_version.go
Labels: approved, lgtm

#2510 OCM-11464 | ci: update some cases importance
  tests/e2e/test_rosacli_cluster.go
  tests/e2e/test_rosacli_oidc_provider.go
  tests/e2e/test_rosacli_operator_roles.go
  tests/e2e/test_rosacli_policy.go
  tests/e2e/test_rosacli_user_role.go
Labels: approved, lgtm

#2500 OCM-11405 | fix: A few bug fixes for registry config
  cmd/describe/cluster/cmd.go
  cmd/describe/cluster/cmd_test.go
  cmd/edit/cluster/cmd.go
  pkg/clusterregistryconfig/flags.go
  pkg/ocm/registry_config.go
  pkg/ocm/registry_config_test.go
Labels: approved, lgtm

#2499 OCM-7780 | feat: support approve/deny access request in ROSA CLI
  cmd/create/cmd.go
  cmd/create/decision/cmd.go
  cmd/create/decision/cmd_test.go
  cmd/create/decision/decision_suite_test.go
  cmd/rosa/structure_test/command_args/rosa/create/decision/command_args.yml
  cmd/rosa/structure_test/command_structure.yml
  go.mod
  pkg/ocm/accessrequests.go
  pkg/test/helpers.go
Labels: approved, lgtm

#2512 OCM-11467 | fix: A few more bug fixes for registry config
  cmd/create/cluster/cmd.go
  cmd/describe/cluster/cmd.go
  cmd/describe/cluster/cmd_test.go
  cmd/edit/cluster/cmd.go
  pkg/clusterregistryconfig/flags.go
  pkg/clusterregistryconfig/flags_test.go
Labels: approved, lgtm

#2515 OCM-11482 | fix: loosen registry regex check
  pkg/ocm/helpers.go
Labels: approved, lgtm

#2503 OCM-11429 | ci: fix id:74225,73449,60278,74403
  tests/e2e/hcp_machine_pool_test.go
  tests/e2e/test_rosacli_policy.go
Labels: approved, lgtm
