Repository openshift/rosa, pull requests merged in 2024-02, with the labels that each got.

#1744 OCM-2780 | feat: Bump SDK release to 0.1.398
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-sdk-go/CHANGES.md
  vendor/github.com/openshift-online/ocm-sdk-go/Makefile
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/generic_notify_details_response_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/generic_notify_details_response_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/generic_notify_details_response_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/accountsmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cloud_provider_data_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cloud_provider_data_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cloud_provider_data_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/cluster_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/external_auth_config_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/external_auth_config_list_builder.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/external_auth_config_list_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/external_auth_config_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/external_auth_config_type_json.go
  vendor/github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1/openapi.go
  vendor/github.com/openshift-online/ocm-sdk-go/connection.go
  vendor/github.com/openshift-online/ocm-sdk-go/internal/check_content_type.go
  vendor/github.com/openshift-online/ocm-sdk-go/rh_region.go
  vendor/github.com/openshift-online/ocm-sdk-go/token.go
  vendor/github.com/openshift-online/ocm-sdk-go/version.go
  vendor/modules.txt
Labels: approved, lgtm

#1734 OCM-5798 | chore: bump and use ocm-commons
  cmd/create/oidcprovider/cmd.go
  cmd/version/cmd_test.go
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-common/pkg/rosa/oidcconfigs/oidcconfigs.go
  vendor/github.com/openshift-online/ocm-common/pkg/utils/consts.go
  vendor/modules.txt
Labels: approved, lgtm

#1750 OCM-3178 | add passed disk size to error message
  cmd/create/cluster/cmd.go
  cmd/create/cluster/cmd_test.go
  cmd/create/machinepool/machinepool.go
  pkg/interactive/validation.go
Labels: approved, lgtm

#1746 HOSTEDCP-1412 | refactor: pkg/ocm: expose upgrade policy on creation
  cmd/upgrade/cluster/cmd.go
  pkg/ocm/controlplane_upgrades.go
Labels: approved, lgtm

#1748 OCM-5862 | fix: default version computation should be done only once
  pkg/helper/versions/helpers.go
  pkg/helper/versions/helpers_test.go
  pkg/test/helpers.go
Labels: approved, lgtm

#1759 OCM-1366 | fix: update description on link user roles command
  cmd/link/userrole/cmd.go
Labels: approved, lgtm

#1760 OCM-5949 | chore: Prepare 1.2.35 release
  pkg/info/info.go
Labels: approved, lgtm

#1755 build: *: use bingo for versioning binary deps
  .bingo/.gitignore
  .bingo/README.md
  .bingo/Variables.mk
  .bingo/bingo.mod
  .bingo/bingo.sum
  .bingo/gci.mod
  .bingo/gci.sum
  .bingo/go-bindata.mod
  .bingo/go-bindata.sum
  .bingo/go.mod
  .bingo/golangci-lint.mod
  .bingo/golangci-lint.sum
  .bingo/mockgen.mod
  .bingo/mockgen.sum
  .bingo/variables.env
  .golangci.yml
  Makefile
  cmd/create/cluster/cmd.go
  cmd/create/idp/cmd.go
  cmd/create/idp/ldap.go
  cmd/create/idp/openid.go
  cmd/describe/cluster/cmd.go
  pkg/ocm/helpers.go
  pkg/ocm/versions_test.go
Labels: approved, lgtm

#1762 OCM-5935 | chore: updates for golang 1.21
  .bingo/bingo.mod
  .bingo/gci.mod
  .bingo/go-bindata.mod
  .bingo/golangci-lint.mod
  .bingo/mockgen.mod
  .golangci.yml
  Makefile
  assets/bindata.go
  go.mod
  pkg/helper/versions/helpers_test.go
Labels: approved, lgtm

#1758 OCM-5827 | fix: detailed throttle retry message
  pkg/aws/client.go
  pkg/aws/client_test.go
Labels: approved, lgtm

#1764 HOSTEDCP-1412 | fix: add the diff target to Makefile
  Makefile
Labels: approved, lgtm

#1766 OCM-5978 | fix: Ensure rosa is the default Makefile target
  Makefile
Labels: approved, lgtm

#1765 OCM-5974 | fix: update correct values for subnet count validation
  pkg/ocm/helpers.go
  pkg/ocm/helpers_test.go
Labels: approved, lgtm

#1767 OCM-5978 | fix: Make rosa the default goal in the Makefile
  Makefile
Labels: approved, lgtm

#1757 OCM-4458 | feat: add new parameter to enable external auth config
  cmd/create/cluster/cmd.go
  cmd/describe/cluster/cmd.go
  cmd/describe/cluster/cmd_test.go
  pkg/ocm/clusters.go
Labels: approved, lgtm

#1761 OCM-1109 | fix: Move logic only related to auto into ModeAuto check
  cmd/create/operatorroles/by_clusterkey.go
Labels: approved, lgtm

#1770 OCM-5983 | chore: clean up old TODO
  pkg/ocm/idps.go
Labels: approved, lgtm

#1772 OCM-1109 | fix: Check if op roles exist always again
  cmd/create/operatorroles/by_clusterkey.go
Labels: lgtm

#1740 pkg/ocm: remove AWS client from create cluster call
  cmd/create/cluster/cmd.go
  cmd/create/cluster/cmd_test.go
  cmd/create/cluster/spec_test.go
  go.mod
  go.sum
  pkg/aws/client.go
  pkg/ocm/clusters.go
  pkg/test/matchers.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/modules.txt
Labels: approved, lgtm

#1769 OCM-5828 | fix: Correct the message shown in interactive mode when creating a MachinePool
  cmd/create/machinepool/machinepool.go
  codecov.yml
Labels: approved, lgtm

#1775 OCM-5972 | fix: triggering retries associated with 'InvalidClientTokenId'
  pkg/aws/client.go
Labels: approved, lgtm

#1776 OCM-6057 | fix: Ensure codecov reports are being published for master
  codecov.yml
Labels: approved, lgtm

#1778 updating OWNERS file
  OWNERS
Labels: approved, lgtm

#1763 OCM-5958 | chore: Move release scripts from Wiki to Git repository
  hack/README.md
  hack/commit-release.sh
  hack/list-jiras.sh
  hack/release-build.sh
  hack/release-generate-changelog.sh
  hack/release-list-jiras.sh
  hack/tag-release.sh
Labels: approved, lgtm

#1782 HOSTEDCP-1412 | refactor: pkg/aws: expose the Creator transform from …
  cmd/create/cluster/cmd_test.go
  cmd/create/cluster/spec_test.go
  pkg/aws/client.go
  pkg/aws/client_test.go
  pkg/test/matchers/matchers.go
Labels: approved, lgtm

#1773 OCM-5963 | fix: add more instruction in billing account error
  cmd/create/cluster/cmd.go
  cmd/create/cluster/cmd_test.go
Labels: approved, lgtm

#1738 OCM-5815 | feat: Add Device Code Flow
  cmd/login/cmd.go
Labels: approved, lgtm

#1785 OCM-6120 | fix: mark --no-cni flag as hidden
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#1784 HOSTEDCP-1412 | Extract hypershift version validation to a separate function
  cmd/create/cluster/cmd_test.go
  pkg/helper/versions/helpers_test.go
  pkg/ocm/versions.go
  pkg/ocm/versions_test.go
Labels: lgtm

#1783 OCM-5830 | feat: removing duplicate err msg output
  cmd/upgrade/roles/cmd.go
Labels: approved, lgtm

#1788 OCM-6243 | fix: validate aws region within .WithAWS
  pkg/ocm/regions.go
  pkg/rosa/runtime.go
Labels: approved, lgtm

#1736 OCM-1794 | feat: --verbose option to version command
  cmd/verify/rosa/cmd.go
  cmd/version/cmd.go
  cmd/version/cmd_test.go
Labels: approved, lgtm

#1793 HOSTEDCP-1412 | cleanup: use the version constant
  pkg/ocm/versions.go
Labels: approved, lgtm

#1792 HOSTEDCP-1412 | refactor: expose nodepool upgrades on creation
  cmd/upgrade/machinepool/cmd.go
  pkg/ocm/nodepools_upgrades.go
Labels: approved, lgtm

#1742 OCM-1733 | feat: list instance-types by region
  cmd/list/instancetypes/cmd.go
  cmd/list/instancetypes/cmd_test.go
  cmd/list/instancetypes/instancetypes_suite_test.go
  codecov.yml
  pkg/aws/client.go
  pkg/aws/mock_client.go
Labels: approved, lgtm

#1791 OCM-1012 | feat: Add filtering by config ID for `list oidc-providers`
  cmd/list/oidcprovider/cmd.go
  pkg/aws/client.go
  pkg/aws/client_test.go
  pkg/aws/mock_client.go
  pkg/aws/sts.go
  pkg/aws/test_helpers.go
Labels: approved, lgtm

#1797 OCM-6055 | feat: describe node pools with additional security groups
  cmd/describe/machinepool/cmd_test.go
  cmd/describe/machinepool/nodepool.go
  pkg/ocm/output/nodepools.go
Labels: approved, lgtm

#1799 OCM-6279 | fix: Temporarily remove build output from rosa version command
  cmd/version/cmd.go
  cmd/version/cmd_test.go
Labels: approved, lgtm

#1798 OCM-5963 | fix: align error messages for billing accounts
  cmd/create/cluster/cmd.go
  cmd/create/cluster/cmd_test.go
Labels: approved, lgtm

#1802 OCM-6351 | chore: Prepare 1.2.36 release
  pkg/info/info.go
Labels: approved, lgtm

#1779 OCM-5829 | feat: Supressing help message when error is thrown
  CONTRIBUTING.md
  cmd/create/operatorroles/cmd.go
  cmd/dlt/ocmrole/cmd.go
  cmd/link/ocmrole/cmd.go
  cmd/link/userrole/cmd.go
  cmd/unlink/ocmrole/cmd.go
  cmd/unlink/userrole/cmd.go
  cmd/upgrade/accountroles/cmd.go
  cmd/upgrade/operatorroles/cmd.go
  cmd/upgrade/roles/cmd.go
  cmd/verify/quota/cmd.go
Labels: lgtm

#1803 OCM-1388 | fix: revert spinner on upgrade account role policies
  cmd/upgrade/accountroles/cmd.go
Labels: approved, lgtm

#1806 Change 'RunE' calls to just 'Run'
  cmd/create/accountroles/cmd.go
  cmd/create/cluster/cmd.go
  cmd/create/ocmrole/cmd.go
  cmd/create/userrole/cmd.go
  cmd/dlt/ocmrole/cmd.go
  cmd/dlt/userrole/cmd.go
  cmd/initialize/cmd.go
  cmd/upgrade/cluster/cmd.go
Labels: approved, lgtm

#1780 OCM-5804 | feat: Add token and config commands
  cmd/config/cmd.go
  cmd/config/cmd_test.go
  cmd/config/get/get.go
  cmd/config/set/set.go
  cmd/rosa/main.go
  cmd/token/cmd.go
  cmd/token/cmd_test.go
  pkg/config/config.go
  pkg/ocm/client.go
Labels: approved, lgtm, ok-to-test

#1809 OCM-6376 | feat: Remove shorthand for --oidc-config-id
  cmd/list/oidcprovider/cmd.go
Labels: approved, lgtm

#1810 OCM-6435 | fix: Bound math.MaxInt64 to avoid overflow on non-64bit arch
  pkg/ocm/helpers.go
Labels: approved, lgtm, jira/valid-reference

#1808 OCM-5935 | fix: remove toolchain from go.mod
  go.mod
Labels: approved, lgtm

#1794 OCM-6054 | feat: Create node pool with SG IDs
  cmd/create/machinepool/helper.go
  cmd/create/machinepool/helper_test.go
  cmd/create/machinepool/machinepool.go
  cmd/create/machinepool/nodepool.go
Labels: approved, lgtm
