Repository openshift/rosa, pull requests merged in 2025-07, with the labels that each got.

#2932 OCM-15737 | ci: add a new func rosa_login_with_clinet()
  go.mod
  go.sum
  tests/prow_ci.sh
  tests/utils/handler/resources_handler_clean.go
  vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/client.go
  vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/eip.go
  vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/network_interface.go
  vendor/github.com/openshift-online/ocm-common/pkg/test/kms_key/kms.go
  vendor/github.com/openshift-online/ocm-common/pkg/test/vpc_client/instance.go
  vendor/github.com/openshift-online/ocm-common/pkg/test/vpc_client/nat_gateway.go
  vendor/github.com/openshift-online/ocm-common/pkg/test/vpc_client/vpc.go
  vendor/modules.txt
Labels: approved, lgtm

#2926 OCM-15992 | fix: Remove check stopping private ingress changes
  cmd/create/cluster/cmd.go
  pkg/interactive/validation.go
  pkg/ocm/clusters.go
  pkg/ocm/helpers.go
  pkg/ocm/helpers_test.go
Labels: approved

#2935 OCM-16864 | fix: Introduce private API to private STS validation
  cmd/create/cluster/cmd.go
Labels: approved

#2938 OCM-17038 | test: fix id: 60688 add unmanaged tag on the testing subnets
  tests/e2e/e2e_day2_conf_test.go
  tests/e2e/hcp_machine_pool_test.go
  tests/e2e/test_rosacli_machine_pool.go
Labels: approved, lgtm

#2937 OCM-16933 | test: automate id:83155 as day1 and day1-post of api and ingress private
  tests/ci/data/profiles/rosa-hcp.yaml
  tests/e2e/test_rosacli_cluster_post.go
  tests/utils/handler/cluster_handler.go
  tests/utils/handler/interface.go
Labels: approved, lgtm

#2939 OCM-17058 | feat: Update mirror and base releases folder URI
  pkg/version/version.go
Labels: approved, lgtm

#2940 OCM-16081 | ci: Add new attribute default_ingress_private for HCP profiles
  tests/ci/data/profiles/external.yaml
Labels: approved, lgtm

#2941 Revert "OCM-17058 | feat: Update mirror and base releases folder URI"
  pkg/version/version.go
Labels: approved, lgtm

#2942 OCM-16902 | fix: Pass in non-args privteIngress value
  cmd/create/cluster/cmd.go
Labels: approved, lgtm

#2944 OCM-16902 | fix: Fix private+privateIngress clusters + validation
  cmd/create/cluster/cmd.go
  cmd/create/cluster/validation.go
  pkg/interactive/validation.go
  pkg/interactive/validation_test.go
Labels: approved, lgtm

#2946 OCM-17244 | test: fix id: 68971 and fix preparation to not use private-link flag anymore for hcp cluster
  tests/e2e/test_rosacli_cluster.go
  tests/utils/handler/cluster_handler.go
Labels: approved, lgtm

#2948 OCM-16905 | feat: Introduce `--private-ingress` to cluster cmd
  cmd/create/cluster/cmd.go
Labels: approved

#2951 OCM-17311 | chore: Bump CLI version on master to 1.2.55
  pkg/info/info.go
Labels: approved, lgtm

#2956 OCM-17311 | fix: Fix broken map for loop
  pkg/fedramp/config.go
Labels: approved, lgtm

#2959 OCM-17372 | chore: bump ocm-common dependency
  go.mod
  go.sum
  vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/client.go
  vendor/github.com/openshift-online/ocm-common/pkg/aws/aws_client/network_interface.go
  vendor/github.com/openshift-online/ocm-common/pkg/ocm/consts/custom_headers.go
  vendor/github.com/openshift-online/ocm-common/pkg/test/vpc_client/key_pair.go
  vendor/github.com/openshift-online/ocm-common/pkg/test/vpc_client/proxy.go
  vendor/github.com/openshift-online/ocm-common/pkg/test/vpc_client/security_group.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#2952 OCM-17372 | feat: Add support for handling deprecation headers in ROSA CLI
  pkg/ocm/client.go
  vendor/github.com/openshift-online/ocm-common/pkg/deprecation/transport_wrapper.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test
