Repository openshift/rosa, pull requests merged in 2025-04, with the labels that each got.

#2837 OCM-14948| fix: Fix AZ conditions
  cmd/create/network/cloudformation.go
  cmd/create/network/templates/rosa-quickstart-default-vpc/cloudformation.yaml
Labels: approved, lgtm

#2839 OCM-14781 | feat: Bump jwt version, to avoid security flaw
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm

#2841 OCM-15005 | feat: sort CF template parameters in help output
  cmd/create/network/cmd.go
  pkg/options/network/create.go
Labels: approved, lgtm

#2840 OCM-14567 | ci: Add ocpe2e-rosa-hcp-shared-vpc profile for OCPE2E
  tests/ci/data/profiles/external.yaml
Labels: approved, lgtm

#2832 OCM 6929 | fix: Improved UX for error handling in private clusters
  cmd/create/cluster/cmd.go
Labels: approved, needs-ok-to-test, lgtm

#2857 OCM-15097 | feat: Un-hide `channel-group` flag in create/cluster
  cmd/create/cluster/cmd.go
Labels: approved

#2855 OCM-15096 | feat: Introduce `channel-group` in edit/cluster
  cmd/edit/cluster/cmd.go
  cmd/rosa/structure_test/command_args/rosa/edit/cluster/command_args.yml
  pkg/ocm/clusters.go
Labels: approved, lgtm

#2861 OCM-14567 | feat: Bump konflux to check for release_1.2.53
  .tekton/rosa-pull-request.yaml
  .tekton/rosa-push.yaml
Labels: approved, lgtm

#2862 OCM-15172 | fix: Do not enable interactive if channel group is edited
  cmd/edit/cluster/cmd.go
Labels: approved, lgtm

#2863 OCM-15159 | feat: Introduce `-y` for migrating cluster network type
  cmd/edit/cluster/cmd.go
Labels: approved, lgtm

#2856 OCM-14567 | ci: Move all the OCPE2E profiles to new file
  tests/ci/data/profiles/external.yaml
Labels: approved, lgtm, ok-to-test

#2864 OCM-15192 | test: automate id:81399 edit cluster channel group
  tests/e2e/test_rosacli_cluster.go
Labels: approved, lgtm

#2859 OCM-13071 | fix: Bump Go version to 1.23
  .bingo/Variables.mk
  .bingo/golangci-lint.mod
  .bingo/golangci-lint.sum
  .bingo/variables.env
  .golangci.yml
  .golangciversion
  cmd/create/machinepool/cmd_test.go
  go.mod
  images/Dockerfile.e2e
  images/Dockerfile.release
  pkg/machinepool/machinepool_mock.go
Labels: approved, lgtm

#2865 OCM-00000 | chore: Disable konflux bot PR checks
  OWNERS
Labels: approved

#2866 OCM-15190 | feat: Remove default channelgroup from edit/cluster
  cmd/edit/cluster/cmd.go
Labels: approved, lgtm

#2867 OCM-4667 | feat: added new warnings and validations to account-role
  cmd/create/cluster/cmd.go
  pkg/helper/roles/helpers.go
Labels: approved, lgtm

#2874 OCM-15397 | ci: Support cluster autoscaler day2 action for HCP cluster
  tests/ci/config/config.go
  tests/ci/data/profiles/external.yaml
  tests/e2e/e2e_day2_conf_test.go
  tests/e2e/e2e_setup_test.go
  tests/utils/handler/interface.go
  tests/utils/handler/profile.go
Labels: approved, lgtm

#2876 OCM-15275 | chore: Bump ROSA version to 1.2.53
  pkg/info/info.go
Labels: approved, lgtm
